### ISSUE TITLE
Add health check endpoint

### ISSUE THREAD

**Issue by anjia0532** [dragonflyoss/Dragonfly2#1157]
### Feature request:

1. cdn (self,disk usage,depond on manager)
2. manager (self,depond on db,redis)
3. scheduler (self,depond on manager,job,cdn)
4. dfget/dfdaemon (self,disk usage,depond on file server,scheduler)

Add health check endpoint.

1. Configuration k8s  liveness readiness startup probes
2. Monitoring and Alert

**Comment by gaius-qi** [comment]
1. Add GRPC health-checking.
2. If the preheat failure is caused by redis, explicitly display the redis unavailable error code.
3. FAQ records redis unavailable information.
4. Charts already have monitoring, need to add alert resource

**Comment by anjia0532** [comment]
> 3. FAQ records redis unavailable information.

https://d7y.netlify.app/docs/reference/preheat/console#faq
