### ISSUE TITLE
Error: no available port to listen, port: 65001 - 65001

### ISSUE THREAD

**Issue by eadou** [dragonflyoss/Dragonfly2#1171]
在部署过程中，dragonfly-dfdaemon一直在报错重启
**
[root@csp-test-master01 ~]# kubectl  logs -n dragonfly-system dragonfly-dfdaemon-qsfcc
Error: no available port to listen, port: 65001 - 65001

**
其他组件pod都是running状态

**Comment by eadou** [comment]
![1](https://user-images.githubusercontent.com/42600775/159224187-1dbe0efa-459e-4b8e-884d-d19955e57af4.png)

**Comment by KubeStacker** [comment]
可以看下 dfdaemon 宿主机有啥服务占用了65001 端口
netstat -antp | grep 65001

另外也提供下docker 和 K8s version

**Comment by anjia0532** [comment]
@KubeStacker 在容器环境里，netstat 可能差不出端口占用来，建议用iptables

**Comment by eadou** [comment]
docker 版本是  19.03.0
k8s版本是：1.17.4
使用netstat -antp | grep 65001 没有结果
**
[root@csp-test-master01 ~]# ss -antp | grep 65001
[root@csp-test-master01 ~]# netstat -antp | grep 65001
[root@csp-test-master01 ~]#
**
![image](https://user-images.githubusercontent.com/42600775/159226232-3183b181-e6e8-4900-a27a-6e19de44bfde.png)

**Comment by anjia0532** [comment]
有log么？ kubectl logs -f xxx -n xxx

**Comment by eadou** [comment]
@anjia0532  Telnet结果如下：
![image](https://user-images.githubusercontent.com/42600775/159226457-d9d4092d-0fa9-4b95-8084-1a063e1f5c70.png)

log：
![image](https://user-images.githubusercontent.com/42600775/159226567-5cfe0327-2ad2-458c-8349-d0b4ca1b28e7.png)

**Comment by anjia0532** [comment]
贴下你的values.yml

**Comment by KubeStacker** [comment]
> @KubeStacker 在容器环境里，netstat 可能差不出端口占用来，建议用iptables，或者用telnet

你执行 kubectl get po -o wide -n dragonfly-system 看到那个宿主机是哪台，然后ssh 到那个机器上执行 telnet 试试

**Comment by eadou** [comment]
@KubeStacker 在节点上看到如下：
![image](https://user-images.githubusercontent.com/42600775/159228836-9c7a199e-9fe0-46ec-a301-ccd6ef08cb23.png)

**Comment by eadou** [comment]
@anjia0532 values.yaml:

[root@csp-test-master01 dragonfly]# grep -Ev '^$|^\s*#' values.yaml
nameOverride: ""
fullnameOverride: ""
clusterDomain: "cluster.local"
containerRuntime:
  docker:
    enable: true
    restart: false
    skipHosts:
      - "127.0.0.1"
      - "docker.io"
    injectHosts: true
    insecure: true
    registryDomains:
      - "10.243.206.124:30012"
    registryPorts:
      - 30012
    caCert:
      countryName: CN
      stateOrProvinceName: Hangzhou
      localityName: Hangzhou
      organizationName: Dragonfly
      commonName: "Dragonfly Authority CA"
  containerd:
    enable: false
    injectConfigPath: false
    configPathDir: /etc/containerd
    registries:
      - "https://ghcr.io"
      - "https://quay.io"
      - "https://harbor.example.com:8443"
  crio:
    enable: false
    registries:
      - "https://ghcr.io"
      - "https://quay.io"
      - "https://harbor.example.com:8443"
  initContainerImage: dragonflyoss/openssl
  extraInitContainers: []
scheduler:
  enable: true
  name: scheduler
  nameOverride: ""
  fullnameOverride: ""
  replicas: 3
  image: dragonflyoss/scheduler
  tag: v2.0.2-rc.24
  pullPolicy: IfNotPresent
  hostAliases: []
  resources:
    requests:
      cpu: "0"
      memory: "0"
    limits:
      cpu: "4"
      memory: "8Gi"
  priorityClassName: ""
  nodeSelector: {}
  terminationGracePeriodSeconds:
  tolerations: []
  podAnnotations: {}
  podLabels: {}
  statefulsetAnnotations: {}
  containerPort: 8002
  extraVolumes:
    - name: logs
      emptyDir: {}
  extraVolumeMounts:
    - name: logs
      mountPath: "/var/log/dragonfly/scheduler"
  initContainer:
    image: busybox
    tag: latest
    pullPolicy: IfNotPresent
  config:
    server:
      cacheDir: ""
      logDir: ""
    scheduler:
      algorithm: default
      backSourceCount: 3
      retryBackSourceLimit: 5
      retryLimit: 10
      retryInterval: 50ms
      gc:
        peerGCInterval: 10m
        peerTTL: 24h
        taskGCInterval: 10m
        taskTTL: 24h
    dynconfig:
      type: manager
      refreshInterval: 1m
    host:
      idc: ""
      netTopology: ""
      location: ""
    manager:
      schedulerClusterID: 1
      keepAlive:
        interval: 5s
    cdn:
      enable: true
    console: false
    verbose: false
    pprofPort: -1
    jaeger: ""
  metrics:
    enable: false
    enablePeerHost: false
    service:
      type: ClusterIP
      labels: {}
      annotations: {}
    serviceMonitor:
      enable: false
      additionalLabels: {}
      interval: 30s
      scrapeTimeout: 10s
    prometheusRule:
      enable: false
      additionalLabels: {}
      rules: []
cdn:
  enable: true
  name: cdn
  nameOverride: ""
  fullnameOverride: ""
  replicas: 3
  image: dragonflyoss/cdn
  tag: v2.0.2-rc.24
  pullPolicy: IfNotPresent
  hostAliases: []
  resources:
    requests:
      cpu: "0"
      memory: "0"
    limits:
      cpu: "4"
      memory: "8Gi"
  priorityClassName: ""
  nodeSelector: {}
  terminationGracePeriodSeconds:
  tolerations: []
  podAnnotations: {}
  podLabels: {}
  statefulsetAnnotations: {}
  extraVolumes:
    - name: logs
      emptyDir: {}
  extraVolumeMounts:
    - name: logs
      mountPath: "/var/log/dragonfly/cdn"
  containerPort: 8003
  nginxContiainerPort: 8001
  initContainer:
    image: busybox
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8003
    targetPort: 8003
    extraPorts:
      - name: http-nginx
        port: 8001
        targetPort: 8001
  persistence:
    enable: true
    annotations: {}
    accessModes:
      - ReadWriteOnce
    size: 8Gi
    storageClass: "glusterfs"
  config:
    base:
      systemReservedBandwidth: 20M
      maxBandwidth: 200M
      enableProfiler: false
      failAccessInterval: 3m
      gcInitialDelay: 6s
      gcMetaInterval: 2m
      gcStorageInterval: 15s
      taskExpireTime: 3m
      storagePattern: disk
      logDir: ""
      manager:
        cdnClusterID: 1
        keepAlive:
          interval: 5s
    plugins:
      storageDriver:
        - name: disk
          enable: true
          config:
            baseDir: /tmp/cdn
      storageManager:
        - name: disk
          enable: true
          config:
            gcInitialDelay: 5s
            gcInterval: 15s
            driverConfigs:
              disk:
                gcConfig:
                  youngGCThreshold: 100G
                  fullGCThreshold: 5G
                  cleanRatio: 1
                  intervalThreshold: 2h
    console: false
    verbose: false
    pprofPort: -1
    jaeger: ""
  metrics:
    enable: false
    service:
      type: ClusterIP
      labels: {}
      annotations: {}
    serviceMonitor:
      enable: false
      additionalLabels: {}
      interval: 30s
      scrapeTimeout: 10s
    prometheusRule:
      enable: false
      additionalLabels: {}
      rules: []
dfdaemon:
  enable: true
  name: dfdaemon
  nameOverride: ""
  fullnameOverride: ""
  image: dragonflyoss/dfdaemon
  tag: v2.0.2-rc.24
  pullPolicy: IfNotPresent
  hostAliases: []
  resources:
    requests:
      cpu: "0"
      memory: "0"
    limits:
      cpu: "2"
      memory: "2Gi"
  priorityClassName: ""
  nodeSelector: {}
  terminationGracePeriodSeconds:
  tolerations: []
  podAnnotations: {}
  podLabels: {}
  daemonsetAnnotations: {}
  extraVolumes:
    - name: logs
      emptyDir: {}
  extraVolumeMounts:
    - name: logs
      mountPath: "/var/log/dragonfly/daemon"
  containerPort: 65001
  hostPort: 65001
  hostNetwork: false
  mountDataDirAsHostPath: false
  config:
    aliveTime: 0s
    gcInterval: 1m0s
    keepStorage: false
    workHome: "/usr/local/dragonfly"
    cacheDir: ""
    logDir: ""
    dataDir: "/var/lib/dragonfly"
    console: false
    verbose: false
    pprofPort: -1
    metrics: ""
    jaeger: ""
    host:
      listenIP: 0.0.0.0
      advertiseIP: 0.0.0.0
      location: ""
      idc: ""
      securityDomain: ""
      netTopology: ""
    scheduler:
      manager:
        enable: true
        netAddrs:
        refreshInterval: 5m
      scheduleTimeout: 30s
      disableAutoBackSource: false
    download:
      totalRateLimit: 200Mi
      perPeerRateLimit: 100Mi
      calculateDigest: true
      downloadGRPC:
        security:
          insecure: true
        unixListen:
          socket: /tmp/dfdamon.sock
      peerGRPC:
        security:
          insecure: true
        tcpListen:
          listen: 0.0.0.0
          port: 65000
    upload:
      rateLimit: 100Mi
      security:
        insecure: true
      tcpListen:
        listen: 0.0.0.0
        port: 65002
    storage:
      taskExpireTime: 6h
      strategy: io.d7y.storage.v2.simple
      multiplex: true
      diskGCThreshold: 50Gi
    proxy:
      defaultFilter: "Expires&Signature"
      security:
        insecure: true
      tcpListen:
        namespace: /run/dragonfly/net
        listen: 0.0.0.0
      registryMirror:
        dynamic: true
        url: https://index.docker.io
        insecure: false
      proxies:
        - regx: blobs/sha256.*
manager:
  enable: true
  name: manager
  nameOverride: ""
  fullnameOverride: ""
  replicas: 3
  image: dragonflyoss/manager
  tag: v2.0.2-rc.24
  pullPolicy: IfNotPresent
  hostAliases: []
  resources:
    requests:
      cpu: "0"
      memory: "0"
    limits:
      cpu: "2"
      memory: "4Gi"
  priorityClassName: ""
  nodeSelector: {}
  terminationGracePeriodSeconds:
  tolerations: []
  podAnnotations: {}
  podLabels: {}
  deploymentAnnotations: {}
  extraVolumes:
    - name: logs
      emptyDir: {}
  extraVolumeMounts:
    - name: logs
      mountPath: "/var/log/dragonfly/manager"
  restPort: 8080
  grpcPort: 65003
  service:
    type: ClusterIP
    labels: {}
    annotations: {}
  initContainer:
    image: busybox
    tag: latest
    pullPolicy: IfNotPresent
  ingress:
    enable: false
    annotations: {}
    path: /
    hosts: []
    tls: []
  config:
    console: false
    verbose: false
    pprofPort: -1
    jaeger: ""
  metrics:
    enable: false
    service:
      type: ClusterIP
      labels: {}
      annotations: {}
    serviceMonitor:
      enable: false
      additionalLabels: {}
      interval: 30s
      scrapeTimeout: 10s
    prometheusRule:
      enable: false
      additionalLabels: {}
      rules: []
externalManager:
  host:
  restPort: 8080
  grpcPort: 65003
mysql:
  enable: true
  clusterDomain: "cluster.local"
  migrate: true
  auth:
    host: ""
    rootPassword: dragonfly-root
    username: dragonfly
    password: dragonfly
    database: manager
  primary:
    service:
      port: 3306
externalMysql:
  migrate: true
  host:
  username: dragonfly
  password: dragonfly
  database: manager
  port: 3306
redis:
  enable: true
  clusterDomain: "cluster.local"
  host: ""
  usePassword: true
  password: dragonfly
  service:
    port: 6379
externalRedis:
  host: ""
  password: dragonfly
  port: 6379
jaeger:
  enable: false
[root@csp-test-master01 dragonfly]#

**Comment by eadou** [comment]
@anjia0532 values.yaml太长了，贴出来不方便阅读，我把docker那一块的配置截图了：

![1647852594(1)](https://user-images.githubusercontent.com/42600775/159229385-7e9ab6cf-8809-45f1-b507-f1b94880a95a.png)

**Comment by KubeStacker** [comment]
> 行 kubectl get po -o wide -n dragonfly-system 看到那个宿主机是哪台，然后ssh 到那个机器上执行 t

能大概描述下你的环境信息么？ 从你提供的信息上看，这个节点上已经有dfdaemon在运行（一个节点仅允许一个daemon），pid是220722。 可以看下他的ppid是谁？如果实在不行，可以先kill掉在看下pod是否running。

**Comment by anjia0532** [comment]
@eadou 看了values应该没问题，issues贴代码，最好是用 

![image](https://user-images.githubusercontent.com/15098916/159229892-8523649a-1d6d-4ba5-9914-5939b16283a1.png)

包起来

看你 telnet结果，应该是所在主机已经有在运行的 dfdaemon 了

**Comment by anjia0532** [comment]
你试试把values.yaml 的 65001 全部替换成别的端口，比如 55001 试试

**Comment by eadou** [comment]
>
 docker 版本是 19.03.0
k8s版本是：1.17.4
奇怪的是，我使用helm unintall dragonfly后，这个进程依旧存在。

![image](https://user-images.githubusercontent.com/42600775/159230528-b74f3472-c548-483d-aa82-13c340b384ce.png)

**Comment by eadou** [comment]
@anjia0532 @KubeStacker 
通过进程找到父进程如下：

![image](https://user-images.githubusercontent.com/42600775/159231369-d993ac7f-8c9f-4701-bdcc-321716e14384.png)

**Comment by anjia0532** [comment]
> 奇怪的是，我使用helm unintall dragonfly后，这个进程依旧存在。

那应该是你集群内还有一组 dfdaemon 吧？
