### ISSUE TITLE
Difference between pkg/cache and go-cache?

### ISSUE THREAD

**Issue by cwdsuzhou** [dragonflyoss/Dragonfly2#1215]
https://github.com/patrickmn/go-cache/blob/master/cache.go
https://github.com/dragonflyoss/Dragonfly2/blob/main/pkg/cache/cache.go

**Comment by gaius-qi** [comment]
1. Refactoring cache using interface
2. Can get expired data，nn the case of unreliable P2P network, expired data can be obtained for fallback. 
https://github.com/patrickmn/go-cache/blob/master/cache.go#L120 => https://github.com/dragonflyoss/Dragonfly2/blob/main/pkg/cache/cache.go#L141
3. Remove unused features https://github.com/patrickmn/go-cache/blob/master/cache.go#L187
