### ISSUE TITLE
预热时候，提示http error。

### ISSUE THREAD

**Issue by eadou** [dragonflyoss/Dragonfly2#1280]
预热时候，提示http error。文档说是redis读写权限问题，我从宿主机远程登录了redis数据库，测试redis读写没有问题。Dragonfly Manager也没有报错出现。相关如下图：
报错：
![image](https://user-images.githubusercontent.com/42600775/165207682-661ff42d-8458-435a-ada2-6f713f7e1aa1.png)

Dragonfly Manager日志：
![image](https://user-images.githubusercontent.com/42600775/165207852-d25a2a7e-8eea-4e76-96d2-35ba7a690946.png)

redis读写测试：
![image](https://user-images.githubusercontent.com/42600775/165207891-25fba4cf-4a7d-402b-921b-af8ffbe0e13d.png)

另外还有几个问题：
1、在创建预热的窗口里，这个url指的是什么，是harbor仓库还是redis的服务。
2、有没有dragonfly2的相关使用指导，https://d7y.io/zh/docs 里面更多的是介绍和部署配置，相关使用配置方面的说明较少，这对我来说有点吃力。

**Comment by gaius-qi** [comment]
1. URL 指的是镜像的 manifest，如果是预热 harbor 仓库的镜像，应该在 harbor 配置。文档参考 https://goharbor.io/docs/2.4.0/administration/p2p-preheat/
2. 后面我们会补下各个功能模块的使用文档。

**Comment by gaius-qi** [comment]
可以发一下 manager 输出到文的日志么? Linux => /var/log/dragonfly/manager/core.log

**Comment by eadou** [comment]
> 可以发一下 manager 输出到文的日志么? Linux => /var/log/dragonfly/manager/core.log

我截取了末尾几行：
`.415","caller":"rpcserver/rpcserver.go:407","msg":"manager:schedulers:dragonfly-dfdaemon-znxlw-5.243.27.215 cache miss","hostname":"dragonfly-dfdaemon-znxlw","ip":"5.243.
.418","caller":"rpcserver/rpcserver.go:414","msg":"list scheduler clusters [scheduler-cluster-1] with hostInfo map[string]string{\"idc\":\"\", \"location\":\"\", \"net_to
.418","caller":"searcher/searcher.go:110","msg":"dfdaemon dragonfly-dfdaemon-znxlw 5.243.27.215 have empty security domain"}
.418","caller":"rpcserver/rpcserver.go:420","msg":"find matching scheduler cluster [scheduler-cluster-1]","hostname":"dragonfly-dfdaemon-znxlw","ip":"5.243.27.215"}
.149","caller":"rpcserver/rpcserver.go:407","msg":"manager:schedulers:dragonfly-dfdaemon-t296t-5.243.166.63 cache miss","hostname":"dragonfly-dfdaemon-t296t","ip":"5.243.
.152","caller":"rpcserver/rpcserver.go:414","msg":"list scheduler clusters [scheduler-cluster-1] with hostInfo map[string]string{\"idc\":\"\", \"location\":\"\", \"net_to
.152","caller":"searcher/searcher.go:110","msg":"dfdaemon dragonfly-dfdaemon-t296t 5.243.166.63 have empty security domain"}
.152","caller":"rpcserver/rpcserver.go:420","msg":"find matching scheduler cluster [scheduler-cluster-1]","hostname":"dragonfly-dfdaemon-t296t","ip":"5.243.166.63"}
.183","caller":"rpcserver/rpcserver.go:407","msg":"manager:schedulers:dragonfly-dfdaemon-6bfrs-5.243.161.225 cache miss","hostname":"dragonfly-dfdaemon-6bfrs","ip":"5.243
.184","caller":"rpcserver/rpcserver.go:414","msg":"list scheduler clusters [scheduler-cluster-1] with hostInfo map[string]string{\"idc\":\"\", \"location\":\"\", \"net_to
.184","caller":"searcher/searcher.go:110","msg":"dfdaemon dragonfly-dfdaemon-6bfrs 5.243.161.225 have empty security domain"}
.184","caller":"rpcserver/rpcserver.go:420","msg":"find matching scheduler cluster [scheduler-cluster-1]","hostname":"dragonfly-dfdaemon-6bfrs","ip":"5.243.161.225"}
.582","caller":"rpcserver/rpcserver.go:218","msg":"manager:scheduler:dragonfly-scheduler-0.scheduler.dragonfly-system.svc.cluster.local-1 cache miss"}
.817","caller":"rpcserver/rpcserver.go:407","msg":"manager:schedulers:dragonfly-dfdaemon-rx88p-5.243.39.29 cache miss","hostname":"dragonfly-dfdaemon-rx88p","ip":"5.243.3
.819","caller":"rpcserver/rpcserver.go:414","msg":"list scheduler clusters [scheduler-cluster-1] with hostInfo map[string]string{\"idc\":\"\", \"location\":\"\", \"net_to
.819","caller":"searcher/searcher.go:110","msg":"dfdaemon dragonfly-dfdaemon-rx88p 5.243.39.29 have empty security domain"}
.819","caller":"rpcserver/rpcserver.go:420","msg":"find matching scheduler cluster [scheduler-cluster-1]","hostname":"dragonfly-dfdaemon-rx88p","ip":"5.243.39.29"}
.879","caller":"rpcserver/rpcserver.go:218","msg":"manager:scheduler:dragonfly-scheduler-2.scheduler.dragonfly-system.svc.cluster.local-1 cache miss"}
.616","caller":"rpcserver/rpcserver.go:407","msg":"manager:schedulers:dragonfly-dfdaemon-xk98v-5.243.88.130 cache miss","hostname":"dragonfly-dfdaemon-xk98v","ip":"5.243.
.618","caller":"rpcserver/rpcserver.go:414","msg":"list scheduler clusters [scheduler-cluster-1] with hostInfo map[string]string{\"idc\":\"\", \"location\":\"\", \"net_to
.618","caller":"searcher/searcher.go:110","msg":"dfdaemon dragonfly-dfdaemon-xk98v 5.243.88.130 have empty security domain"}
.618","caller":"rpcserver/rpcserver.go:420","msg":"find matching scheduler cluster [scheduler-cluster-1]","hostname":"dragonfly-dfdaemon-xk98v","ip":"5.243.88.130"}
.336","caller":"rpcserver/rpcserver.go:407","msg":"manager:schedulers:dragonfly-dfdaemon-lsp86-5.243.0.10 cache miss","hostname":"dragonfly-dfdaemon-lsp86","ip":"5.243.0.
.339","caller":"rpcserver/rpcserver.go:414","msg":"list scheduler clusters [scheduler-cluster-1] with hostInfo map[string]string{\"idc\":\"\", \"location\":\"\", \"net_to
.339","caller":"searcher/searcher.go:110","msg":"dfdaemon dragonfly-dfdaemon-lsp86 5.243.0.10 have empty security domain"}
.339","caller":"rpcserver/rpcserver.go:420","msg":"find matching scheduler cluster [scheduler-cluster-1]","hostname":"dragonfly-dfdaemon-lsp86","ip":"5.243.0.10"}
.167","caller":"rpcserver/rpcserver.go:218","msg":"manager:scheduler:dragonfly-scheduler-1.scheduler.dragonfly-system.svc.cluster.local-1 cache miss"}
.581","caller":"rpcserver/rpcserver.go:218","msg":"manager:scheduler:dragonfly-scheduler-0.scheduler.dragonfly-system.svc.cluster.local-1 cache miss"}
.878","caller":"rpcserver/rpcserver.go:218","msg":"manager:scheduler:dragonfly-scheduler-2.scheduler.dragonfly-system.svc.cluster.local-1 cache miss"}
.166","caller":"rpcserver/rpcserver.go:218","msg":"manager:scheduler:dragonfly-scheduler-1.scheduler.dragonfly-system.svc.cluster.local-1 cache miss"}
.580","caller":"rpcserver/rpcserver.go:218","msg":"manager:scheduler:dragonfly-scheduler-0.scheduler.dragonfly-system.svc.cluster.local-1 cache miss"}
.877","caller":"rpcserver/rpcserver.go:218","msg":"manager:scheduler:dragonfly-scheduler-2.scheduler.dragonfly-system.svc.cluster.local-1 cache miss"}
.165","caller":"rpcserver/rpcserver.go:218","msg":"manager:scheduler:dragonfly-scheduler-1.scheduler.dragonfly-system.svc.cluster.local-1 cache miss"}
.579","caller":"rpcserver/rpcserver.go:218","msg":"manager:scheduler:dragonfly-scheduler-0.scheduler.dragonfly-system.svc.cluster.local-1 cache miss"}
.875","caller":"rpcserver/rpcserver.go:218","msg":"manager:scheduler:dragonfly-scheduler-2.scheduler.dragonfly-system.svc.cluster.local-1 cache miss"}
`

**Comment by gaius-qi** [comment]
所有的都贴上来吧，这部分没有包括预热的日志。

**Comment by eadou** [comment]
> .415
日志比较大，已经用邮件形式发送到您的邮箱。麻烦了

**Comment by eadou** [comment]
您好：
    日志请看附件



***@***.***
 
发件人： Gaius
发送时间： 2022-04-26 13:41
收件人： dragonflyoss/Dragonfly2
抄送： eadou; Author
主题： Re: [dragonflyoss/Dragonfly2]预热时候，提示http error。 (Issue #1280)
所有的都贴上来吧，这部分没有包括预热的日志。

**Comment by gaius-qi** [comment]
我没有收到，邮箱地址是: gaius.qi@gmail.com

**Comment by eadou** [comment]
> 我没有收到，邮箱地址是: [gaius.qi@gmail.com](mailto:gaius.qi@gmail.com)

你好，重新发了，请问收到邮件了吗。
我拉取了一个大小约1.2G左右的test镜像，然后删除了。再去拉取此镜像，在dfdaemon的/var/log/dragonfly/daemon/core.log日志中并没有看见peer task done的相关信息，所以没有经过dragonfly拉取是吗。部署时候的values.yaml文件里，containerRuntime.docker.restart我配置的是true，是不是没有部署成功。

**Comment by gaius-qi** [comment]
钉钉加我聊吧 v14zp0l
