### ISSUE TITLE
peer_task_cache_hit_total metric is not calculated normally. 

### ISSUE THREAD

**Issue by sungjunyoung** [dragonflyoss/Dragonfly2#1295]
### Bug report:

I found `peer_task_cache_hit_total` metric is too low in my grafana system. 

### Expected behavior:
`peer_task_cache_hit_total` should count normally

### How to reproduce it:
Always, 
https://github.com/dragonflyoss/Dragonfly2/blob/655d450f0a14605750d50d17885b947abea0c1c3/client/daemon/peer/peertask_manager.go#L209-L224

in `peertask_manager.go:210`, I think we should count one more `peer_task_cache_hit_total` before double check. Is it normal behavior? if not, I'll create pull request about this.

### Environment:
- Dragonfly version: -
- OS: -
- Kernel (e.g. `uname -a`): -
- Others: -

**Comment by gaius-qi** [comment]
Can you describe how to download task?

**Comment by sungjunyoung** [comment]
I just using dragonfly with basic installation via helm chart. 
This is only about metric collection logic, not about bug of features
If it is not a issue, you can close it :)

**Comment by gaius-qi** [comment]
If it is the first download task in the same dfdaemon, it is normal that the cache is not hit. If it is not the first download task in the same dfdaemon, it is not normal that the cache is not hit.

**Comment by jim3ma** [comment]
We count every request in one of `metrics.PeerTaskCacheHitCount` and `metrics.PeerTaskCount`.

**Comment by sungjunyoung** [comment]
> If it is the first download task in the same dfdaemon, it is normal that the cache is not hit. If it is not the first download task in the same dfdaemon, it is not normal that the cache is not hit.

I understood, when logic arrived to `getOrCreatePeerTaskConductor` function, dragonfly don't know that task is cached or not. that is why double-check that task is cached. I'll close issue, thanks for reply
