### ISSUE TITLE
Use TLS whenever possible in Manager <-> MySQL connection

### ISSUE THREAD

**Issue by embroede** [dragonflyoss/Dragonfly2#1299]
### Feature request:

For communication from manager to mysql server, use `tls=preferred` parameter to enable TLS whenever possible. This should not be a breaking change, as per the [library documentation](https://pkg.go.dev/github.com/go-sql-driver/mysql#section-readme) the client will only attempt to use TLS if supported by the server. But this will fix the case where the manager cannot connect to a server that requires TLS.

### Use case:

Currently Manager cannot connect to a MySQL database that requires TLS, without fully configuring certs/keys (functionality added in https://github.com/dragonflyoss/Dragonfly2/pull/1015). By adding this new default, TLS will be used whenever possible (even with only password), without breaking any existing functionality.

**Comment by gaius-qi** [comment]
Thx 🚀🚀🚀
