### ISSUE TITLE
Make dfget proxy's mutual TLS authentication optional

### ISSUE THREAD

**Issue by hulucc** [dragonflyoss/Dragonfly2#1320]
### Feature request:
When dfget proxy configure as secure, mutual TLS authentication are mandatory,
which makes deployment complicated with little earnings, because proxy is exposing port at localhost.
So it would be nice to have a option, let the user to decide worth or not.
### Use case:
Configure dfget proxy with self signed certificate, and registry client can use https://127.0.0.1:65001 just with skip_verify.

**Comment by gaius-qi** [comment]
I will remove `tls.RequireAndVerifyClientCert` in `proxy` and `upload` server.
