### ISSUE TITLE
2022 Alibaba Summer of Code

### ISSUE THREAD

**Issue by gaius-qi** [dragonflyoss/Dragonfly2#1328]
## 2022 Alibaba Summer of Code

Welcome to the open source world! If you haven't planned how to spend this summer, come to the Alibaba Summer of Code and code with us! 💻
Alibaba Summer of Code is a global program focused on engaging students directly in open source software development. Under the guidance of the mentor in the Alibaba open source project, students can experience software development in the real world. Alibaba Summer of code will begin from May 30th to September 1st. Students can use the summertime to participate in the open source project and work with the core members of the project.

## What you can get?

On this exclusive developer journey, students will have the opportunity to:
- Participate in the top projects of the International Open Source Foundation;
- Get a scholarship from Alibaba;
- Obtain an open source contributor certificate;
- Get a fast pass of Alibaba Internship
- Get your code adopted and used by the open source project！

## Our Mentor

Gaius ([@gaius-qi](https://github.com/gaius-qi) ), ASoC Mentor, Dragonfly Maintainer.
Jim ([@jim3ma](https://github.com/jim3ma) ), ASoC Mentor, Dragonfly Maintainer.
Sunwp ([@jim3ma](https://github.com/244372610) ), ASoC Mentor, Dragonfly Maintainer.

## Timeline

![image](https://user-images.githubusercontent.com/15955374/170172134-56b76233-f598-4651-a782-d692e19eb5e0.png)

## Apply Now!

Browse open idea list here:
- Dragonfly 中基于机器学习的多场景自适应智能 P2P 节点调度算法及优: https://github.com/dragonflyoss/Dragonfly2/issues/1329
- Dragonfly 中 P2P 传输协议优化: https://github.com/dragonflyoss/Dragonfly2/issues/1330
- 通信框架的高并发、高可用、高性能提升: https://github.com/dragonflyoss/Dragonfly2/issues/1331

Upload your CV and project proposal via ASOC 2022 official website：[ASOC2022](https://opensource.alibaba.com/asoc2022)

## Contact the Organizer

If you have any questions, visit the event website:https://opensource.alibaba.com/asoc2022
Email address: [dragonfly-maintainers@googlegroups.com](mailto:dragonfly-maintainers@googlegroups.com)

**Comment by shubham-cmyk** [comment]
@gaius-qi Is there any project left for ASOC 2022  ?
