### ISSUE TITLE
Dragonfly 中基于机器学习的多场景自适应智能 P2P 节点调度算法及优化

### ISSUE THREAD

**Issue by gaius-qi** [dragonflyoss/Dragonfly2#1329]
## 内容

Dragonfly 项目中，基于机器学习针对不同场景寻找最优节点打分规则，为待调度节点寻找最优父节点。对当前场景所遇到的调度问题带来的下载瓶颈进行数据收集、数据分析、建模、算法调研、监控及优化。构建面向下一代的更加智能的 P2P 调度算法。

## 项目产出

完整参与 P2P 节点调度算法实现，并在现有场景下比现阶段基于规则调度算法，提高 P2P 网络内各节点下载效率、利用率以及稳定性。

## 项目要求

- 基于 P2P 的文件分发协议。
- 机器学习调度算法。

## 难度

进阶

## 导师

Github: @gaius-qi 
Email Address: gaius.qi@gmail.com

**Comment by Y-J-9** [comment]
[Uploading Dragonfly初步设计文档.pdf…]()

**Comment by Y-J-9** [comment]
[Dragonfly初步设计文档.pdf](https://github.com/dragonflyoss/Dragonfly2/files/8964613/Dragonfly.pdf)

**Comment by Y-J-9** [comment]
[初步设计文档.pdf](https://github.com/dragonflyoss/Dragonfly2/files/8964615/default.pdf)

**Comment by gaius-qi** [comment]
1. 需要线性回归公式，并划哪些是离散特征，哪些是连续特征。
2. Location、IDC 以及 NetTopology 是不需要舍弃的，当作特征值的时候，可以作为离散特征值。用最终匹配结果 0 或 1 来代表其值。
3. HostType 同样也不需要被舍弃, 当作离散特征值来做。
4. Scheduler 模块增加 Training package，Training package 依赖 Storage package，不要 Storage 里面耦合训练相关内容。
5. Training 写成一个策略类: 包括线性回归和深度学习两个实现, 深度学习这部分暂且不看，这么实现就是让 Training 可扩展。
```golang
type Training interface{
  Serve() error
  Stop() error
  ...
}
```
6. Training Serve 中再对应策略(线性回归)中实现就包括数据相关、训练、回归。
7. 训练结束后模型如何保存? => 对象存储保存模型。且只保存回归成功的模型。
  a. 对象存储的 AK 等 manager 里面有。存储的时候要约定存储 path，根据 scheduler id，日期等。
  b. manager 提供 rest api，能够 CURD 对应 scheduler 的模型。
  c. manager 要提供 rest api 去更换对应 scheduler 的模型。更换模型的链路走 redis 的 mq 通知 scheduler，可以参考 manager 内 job 里面 preheat 如何实现的。 
8. 提供两种替换模型的方式 1. 手动替换对应模型(手动替换走上面提到的 manager rest api) 2. 回归成功后自动替换
9. 训练的时间间隔，需要可配置，但是有最小值 1 week。
10. 在没有训练出模型的时候，使用规则的方式(evaluator_base.go)兜底。

**Comment by gaius-qi** [comment]
1. 实际数据集 @gaius-qi
2. 更新 scheduler 模型通过 manager 操作 redis，而非走异步任务。

**Comment by Y-J-9** [comment]
[初步设计文档_v2.pdf](https://github.com/dragonflyoss/Dragonfly2/files/9016326/_v2.pdf)

**Comment by gaius-qi** [comment]
Peer 下载数据:
[record.csv](https://github.com/dragonflyoss/Dragonfly2/files/9024803/record.csv)

**Comment by gaius-qi** [comment]
1. 特征值，举例:

```text
离散特征值:
1. IDC: Peer IDC 与 Parent IDC 字符串完全匹配，匹配值为 0，不匹配值为 1.
2. Parent Peer Type: Parent 的类型，非 CDN 值为 0， CDN 值为 1。

连续特征值:
1. Parent Piece 下载百分比: Parent Piece Total / TotalPieceCount
```

2. 模型 API 设计, 要遵守 REST 标准，并且缺少 Redis 存储 Key 设计:

`/model/:id` CURD 就可以了

3. 配置命名有了，但是具体描述没有，并且缺少配置具体值是什么？ 如果是枚举，枚举值是什么？举例:

**RefreshMode**
描述: 模型刷新模式
枚举值: 0 代表手动、1 代表自动。

然后最后列出 scheduler 整体配置列表。

4. 实现两个 package pipeline 和 training，文件目录结构列下

**Comment by Y-J-9** [comment]
[初步设计文档_v3.pdf](https://github.com/dragonflyoss/Dragonfly2/files/9037480/_v3.pdf)

**Comment by gaius-qi** [comment]
1. 离散特征值：
state 四种状态, 其他都没问题。时间是否要做成离散特征值，做时间桶，按照 2小时划分。

2. REST API:

Models:

```text
GET `api/v1/models/:id`
GET `api/v1/models`
PATCH `api/v1/models/:id`
DELETE `api/v1/models/:id`
```

Vesions:

```text
GET `api/v1/models/:id/versions/:version_id`
GET `api/v1/models/:id/versions`
PATCH `api/v1/models/:id/versions/:version_id`
DELETE `api/v1/models/:id/versions/:version_id`
```

**Comment by wd665544** [comment]
* Y-J-9: 完成了training.go和training_test.go

**Comment by wd665544** [comment]
wd665544
* 修改pr的问题
* 补充pipeline的test
Y-J-9
* 根据pipeline改造train流程
* 阅读论文，拟定提纲

**Comment by Y-J-9** [comment]
### 8.2会议记录

- pipeline重构设计方案详解。
- 深度学习设计方案详解。
- Dragonfly项目详解。

1. manager负责配置管理，维护peer间的关联关系，负责稳定性相关，网络相关。manager启动scheduler调度集群，seed peer集群，集群和实例是一对多的关系。
2. scheduler负责核心调度，存储基于task的有向无环peer图，向manager上报配置，异步拉取并保持心跳。调度时优先进行filter，过滤后的peer进行打分后返回给下载peer。
3. seed peer负责回源下载，其前驱结点一定为源站，向manager上报配置，异步拉取并保持心跳。
4. peer负责主要的文件下载流程，先根据taskID向scheduler拉取可用peers列表，再根据每个piece向peer请求piece描述数据，优先返回的peer将作为该piece的parent peer进行下载。

## 下周任务

- pr功能完善。
- 列论文提纲。
- 准备科普类文章。

**Comment by wd665544** [comment]
@gaius-qi 
* storage增加list接口返回为readerCloser
* for select逻辑review
* scheduler dynamic config返回schedulerID  

@Y-J-9 
* 写dragonfly介绍文章
* 细化论文提纲

@wd665544 
* 提交pipeline和training的pr
* 解决ci问题

**Comment by Y-J-9** [comment]
### 8月29日会议记录

@gaius-qi 

- Dragonfly介绍文档在其他平台的投递

@wd665544 

- [WIP]手动和自动模式
- 剩余代码的完善

@Y-J-9 

- Dragonfly介绍文档的英文翻译

**Comment by wd665544** [comment]
## 8月29日会议记录
@wd665544
* [WIP]手动和自动模式  70%


@Y-J-9 
* Dragonfly介绍文档的英文翻译review
