### ISSUE TITLE
通信框架的高并发、高可用、高性能提升

### ISSUE THREAD

**Issue by gaius-qi** [dragonflyoss/Dragonfly2#1331]
## 内容

Dragonfly 是 CNCF 中用于文件分发的P2P产品，可以有效支撑海量规模的P2P文件下载。Dragonfly各个子系统间的通信框架是支撑整个P2P文件下载效率性能的核心，通过它连通了各个系统间的交互，保证系统间的高效通信和故障迁移。

## 项目产出

- 优化各子系统之间通信框架。

## 项目要求

- 熟悉 Golang 语言。
- 对 GRPC 有一定了解。

## 难度

进阶

## 导师

Github: @244372610 
Email Address: 244372610@qq.com

**Comment by richardoLee** [comment]
@244372610 Hi there! I'm wondering whether there is anyone working on it now? I want to give it a try.

**Comment by shubham-cmyk** [comment]
@richardoLee Are you up on this project or this one is still left.

**Comment by gaius-qi** [comment]
> @244372610 Hi there! I'm wondering whether there is anyone making a proposal or working on it now? I want to give it a try.

> @richardoLee Are you up on this project or this one is still left.

cc @244372610
