### ISSUE TITLE
Manager 's scheduler state become inconsistency after reboot

### ISSUE THREAD

**Issue by hulucc** [dragonflyoss/Dragonfly2#1336]
### Bug report:

If any scheduler offline while manager(single instance) rebooting, the scheduler active/inactive state will not sync any more.

### Expected behavior:

the scheduler state should always synced by keep alive.

### How to reproduce it:

Create 2 instance of scheduler and 1 manager. Shutdown the manager and any one of the scheduler, and restart the manager.

### Environment:
- Dragonfly version: 2.0.3-beta4

**Comment by gaius-qi** [comment]
I will recheck the keepalive when the manager restarts.

**Comment by gaius-qi** [comment]
I think it is necessary to ensure the stable operation of the manager.
