### ISSUE TITLE
dfdaemon support disable dynamic config refresh 

### ISSUE THREAD

**Issue by bigerous** [dragonflyoss/Dragonfly2#1372]
### Feature request:
When Scheduler.Manager.RefreshInterval == 0, daemon will only request manager once, not panic.

**Comment by gaius-qi** [comment]
If dynamic configuration is enabled, it will be refreshed regularly. If dynamic configuration is not used, you need to configure a fixed scheduler address.

It is not considered to support the case of only refreshing once.

**Comment by gaius-qi** [comment]
Dfdaemon will support the case of only refreshing once.

**Comment by gaius-qi** [comment]
Two situations will pull dynamic configuration:
1. Pull regularly according to the interval.
2. When the scheduler is unavailable, pull it again.

When interval is equal to 0, it is only pulled once at starting.

**Comment by bigerous** [comment]
increase interval to a large number can also meet our demand

**Comment by gaius-qi** [comment]
> increase interval to a large number can also meet our demand

That's great, no need to set a 0 value.
