### ISSUE TITLE
When page value is not 1, the count calculated by API “ jobs [get]” is 0.

### ISSUE THREAD

**Issue by LetFu** [dragonflyoss/Dragonfly2#1373]
### Bug report:
When I was using the task page pagination feature I found that when I selected a page number other than 1, the response header carried the wrong link.
```bash
The total number of data is 52.

Request url:
http://192.168.31.131:8081/api/v1/jobs?page=2&per_page=50

Response.headers.link:
</api/v1/jobs?page=1&per_page=50>;rel=prev,
</api/v1/jobs?page=3&per_page=50>;rel=next,
</api/v1/jobs?page=1&per_page=50>;rel=first,
</api/v1/jobs?page=1&per_page=50>;rel=last
```
#### Reason
Then I looked at the code and I found that the error should be here:
https://github.com/dragonflyoss/Dragonfly2/blob/main/manager/service/job.go#L180-L184
```go
if err := s.db.WithContext(ctx).Scopes(model.Paginate(q.Page, q.PerPage)).Where(&model.Job{
    Type:   q.Type,
    State:  q.State,
    UserID: q.UserID,
}).Find(&jobs).Count(&count).Error; err != nil {
```
When page is not 1, the offset calculated by the following code will not be 0
https://github.com/dragonflyoss/Dragonfly2/blob/main/manager/model/models.go#L40
```go
offset := (page - 1) * perPage
```
At this time, the SQL statement generated by the above SQL code is as follows:
```sql
{"elapsed": "2.223839ms", "rows": 2, "sql": "SELECT * FROM `job` WHERE `job`.`is_del` = 0 LIMIT 50 OFFSET 50"}
{"elapsed": "872.777µs", "rows": 0, "sql": "SELECT count(*) FROM `job` WHERE `job`.`is_del` = 0 LIMIT 50 OFFSET 50"}  # result 0
```
#### Fix
Then I changed the following line and the count looks like it's being fetched properly
https://github.com/dragonflyoss/Dragonfly2/blob/main/manager/service/job.go#L184
```go
}).Find(&jobs).Limit(-1).Offset(-1).Count(&count).Error; err != nil {
```
I've looked at the code and there may be more than just `jobs` with this problem.
And there also seems to be an error in this line:
https://github.com/dragonflyoss/Dragonfly2/blob/main/manager/handlers/handlers.go#L50
Get should be
```go
totalPage := totalCount/perPage + 1
```

### Expected behavior:
I think the normal situation should be like this:
```bash
The total number of data is 52.

Request url:
http://192.168.31.131:8081/api/v1/jobs?page=2&per_page=10

Response.headers.link:
</api/v1/jobs?page=1&per_page=10>;rel=prev,
</api/v1/jobs?page=3&per_page=10>;rel=next,
</api/v1/jobs?page=1&per_page=10>;rel=first,
</api/v1/jobs?page=6&per_page=10>;rel=last
```

### Environment:
- Dragonfly version: v2.0.3
- OS:
- Kernel (e.g. `uname -a`):
- Others:

**Comment by gaius-qi** [comment]
Thx
