### ISSUE TITLE
dfget 直接下载拉起来的daemon未使用指定的配置文件

### ISSUE THREAD

**Issue by ismewen** [dragonflyoss/Dragonfly2#1380]
### Bug report:

dfget 直接下载拉起来的daemon未使用指定的配置文件

<img width="892" alt="image" src="https://user-images.githubusercontent.com/30500262/173487934-ff854187-aa4e-4184-9c6b-28fdc34e0774.png">

### Expected behavior:

dfget 直接下载时拉起的daemon使用指定的config文件启动

### How to reproduce it:

./dfget --config ./config/dfget.yaml -u http://10.190.113.78:8001/15gfile.tgz

### Environment:
- Dragonfly version: 2.0.3
- OS: centos
- Kernel (e.g. `uname -a`): Linux VM-112-209-centos 4.14.105-1-tlinux3-0022 #1 SMP Wed Sep 29 11:01:45 CST 2021 x86_64 x86_64 x86_64 GNU/Linux
- Others:

**Comment by 1037husterljx** [comment]
`cmd := exec.Command(os.Args[0], "daemon", "--launcher", strconv.Itoa(os.Getpid()))`
config parameters are not passed to the daemon and dfget itself does not read the zone config，I will fix this bug
