### ISSUE TITLE
Wanted: Who is using Dragonfly | 如果贵司正在使用 Dragonfly 请留言

### ISSUE THREAD

**Issue by gaius-qi** [dragonflyoss/Dragonfly2#1383]
# Who is using Dragonfly

First of all, thanks sincerely for constantly using and supporting Dragonfly. We will try our best to keep Dragonfly better, and keep community and eco-system growing.

## The purpose of this issue
* We’d like to listen to the community to make Dragonfly better.
* We want to attract more people to contribute to Dragonfly.
* We're willing to learn more Dragonfly use scenarios for better planning.

## What we expect from you

Please submit a comment in this issue to include the following information:

* Your company, school or organization.
* Your city and country.
* Your contact info: blog, email or Twitter (at least one).
* For what business scenario do you use Dragonfly.

You can refer to the following sample answer for the format:

```
Orgnization/Company: Alibaba
Location: Hangzhou, China
Contact: abc@d.com
Purpose/Scenario: Large-scale image and file distribution.
```

Thanks again for your participation!
Dragonfly Community

**Comment by gaius-qi** [comment]
Orgnization/Company: Ant Group
Location: Hangzhou, China
Contact: [gaius.qi@gmail.com](mailto:gaius.qi@gmail.com)
Purpose/Scenario: Large-scale image and file distribution.

**Comment by bigerous** [comment]
Orgnization/Company: Alibaba Group
Location: Hangzhou,  China
Contact: cuidajun.cdj@alibaba-inc.com
Purpose/Scenario: Large-scale image and file distribution.

**Comment by Liuwenfan** [comment]
Orgnization/Company: ZTO-EXPRESS
Location: ShangHai, China
Contact: liuwenfan19950602@zto.com
Purpose/Scenario: now is Large-scale image distribution.

**Comment by guolifu** [comment]
Orgnization/Company: Cloudwise
Location: Beijing, China
Contact: [a631929063@gmail.com](mailto:a631929063@gmail.com)
Purpose/Scenario: Large-scale image and file distribution.

**Comment by auspiclzx** [comment]
Orgnization/Company: Wangyi
Location: Guangzhou, China
Contact: auspiclzx@163.com
Purpose/Scenario: Large-scale image and file distribution.

**Comment by czomo** [comment]
Orgnization/Company: Vewd, part of Xperi now
Location: Wrocław, Poland
Contact: [tdul@vewd.com](tdul@vewd.com)
Purpose/Scenario: Large-scale image distribution.

**Comment by Leo-Song** [comment]
Organization/Company: Yipitdata
Location：Guangzhou, china
Contact:  jsong@yipitdata.com
Purpose/Scenario: Large-scale image and file distribution.

**Comment by gaius-qi** [comment]
If you are using to dragonfly to improve your distribution, then please add your team and use-case to [ADOPTERS.md](https://github.com/dragonflyoss/Dragonfly2/blob/main/ADOPTERS.md).
