### ISSUE TITLE
下载的预编译二进制Dragonfly 默认不带manager-console UI

### ISSUE THREAD

**Issue by DeskyAki** [dragonflyoss/Dragonfly2#1387]
### Feature request:

下载的预编译二进制Dragonfly 默认不带manager-console UI。

希望大佬们能带上！:)

**Comment by gaius-qi** [comment]
I will fix this problem.

**Comment by gaius-qi** [comment]
Please try to use [v2.0.5](https://github.com/dragonflyoss/Dragonfly2/releases/tag/v2.0.5) version. I have embed the manager UI into the manager binary. The manager UI can be included using the installation package.
