### ISSUE TITLE
Running Dragonfly 2 without manager

### ISSUE THREAD

**Issue by ish-xyz** [dragonflyoss/Dragonfly2#1396]
### Feature request:
Is it possible to run Dragonfly 2 without the manager component?

Can you please provide a guide to install/configure Dragonfly 2 without the manager, MySQL, redis and UI?

While manager sounds useful it adds complexity to the overall architecture and all we're looking for in our team is to run dragonfly 2 as we were running the old dragonfly.

**Comment by gaius-qi** [comment]
There should be no plans to remove the manager deployment, because the manager is more important for cluster stability. If you are interested, you can try to submit a pull request and use the manager as a plugin.
