### ISSUE TITLE
dfget命令的递归下载文件列表功能

### ISSUE THREAD

**Issue by auspiclzx** [dragonflyoss/Dragonfly2#1429]
昨天在使用dfget的 -r 参数对带有文件列表的http文件服务器进行递归下载文件的时候，发现并不能成功，据群里的大佬说这里的source http的list func还没有实现，希望大佬们后期可以补充好~

这是我的dfget命令：
dfget --schedulers x.x.x.x:8002 -O /home/linzhaoxiang/output -u "[http://x.x.x.x:81/"](http://x.x.x.x:81/%22) --pattern source --workhome /home/ansible/dragonfly-workHome -r

### 环境:
- Dragonfly version:V2.0.3

**Comment by gaius-qi** [comment]
This week I will refactor the `pkg/source` package and fix this issue.
