### ISSUE TITLE
 exceeds the defaultDepthLimit depth limit of the tree

### ISSUE THREAD

**Issue by 1037husterljx** [dragonflyoss/Dragonfly2#1450]
### Bug report:

When the depth of candidateParent or peer is defaultDepthLimit (4), scheduling will fail no matter how and triggering RetryLimit returns 5006 error

### Expected behavior:

Regardless of the depth, it should be possible to schedule successfully.

### How to reproduce it:

Use 60 clients and three seed peers to start downloading 1G tasks at the same time, dyconfig loadlimit = 15

### Environment:
- Dragonfly version: 059ee11ed702fd4f8d9fdcaab4f819f1d6449a26
- OS: linux
- Kernel (e.g. `uname -a`):
- Others:
                parentDepth+peerDepth > defaultDepthLimit is Unreasonable.
                One of the depths should be down to calculate the child depth.

**Comment by gaius-qi** [comment]
Set `DepthLimit` to be dynamically configurable in manager.

**Comment by gaius-qi** [comment]
Quick Solution:
Deletes the current peer depth calculation for the depth limit.

Future Solution:
Task uses a DAG(Directed Acyclic Graph) for abstraction.
