### ISSUE TITLE
ManagerClient should embeded in SchedulerClient

### ISSUE THREAD

**Issue by bigerous** [dragonflyoss/Dragonfly2#1456]
### Feature request:
My scheduler can not be deployed as statefulSet(due to poor platform), which means the ips of scheduler will change everytime deploying scheduler. 

While the dfdaemon can't not get healthy scheduler in time until `sheduler.manager.refreshInterval`.

I suggest embeding a ManagerClient in schedulerClient. When get connect to all scheduler failed, refresh scheduler list from manager.

**Comment by gaius-qi** [comment]
![image](https://user-images.githubusercontent.com/15955374/178464751-c9d2c721-f5ca-42b3-8582-77aa4600f5d4.png)
![image](https://user-images.githubusercontent.com/15955374/178464775-8c5c2c7b-77c2-4189-9e5d-1d17d5bedc42.png)
