### ISSUE TITLE
error [4000] digest no set

### ISSUE THREAD

**Issue by 1037husterljx** [dragonflyoss/Dragonfly2#1464]
### Bug report:

In the case of p2p first and then back to the source to download the pieces, although going back to the source will re-download the pieces, but when t.pieces has piece information, it will skip GenMetadata resulting in downloadedPieceCount.Load() ! = pieceCount finally cannot GenMetadata return to false cannot generate PieceMd5Sign
![image](https://user-images.githubusercontent.com/39621720/179134325-9bf1092b-acf9-41b4-9253-9223f346ced9.png)
https://github.com/dragonflyoss/Dragonfly2/blob/7439b0e6c57d810b51ad0ba575b217ea88c78402/client/daemon/peer/piece_manager.go#L855
https://github.com/dragonflyoss/Dragonfly2/blob/7439b0e6c57d810b51ad0ba575b217ea88c78402/client/daemon/storage/local_storage.go#L186
### How to reproduce it:
Download with 50 machines, there will be a probability of p2p first and then back to the source, in this case the signature will be empty

### Environment:
- Dragonfly version: 
- OS:
- Kernel (e.g. `uname -a`):
- Others:

**Comment by 1037husterljx** [comment]
![image](https://user-images.githubusercontent.com/39621720/179135928-45d2257f-0b4c-46ed-950f-0cdd69445fff.png)
Calling GenMetadata in the WritePiece logic of the local_store can solve the situation where the final return is false
Is there a better solution?

**Comment by jim3ma** [comment]
Before back source, set the downloaded piece count ?
