### ISSUE TITLE
It appears that manager opens (and maintains) a connection to the DB for each client (dfdaemon)

### ISSUE THREAD

**Issue by embroede** [dragonflyoss/Dragonfly2#1475]
This seems that it would require an multiple instances of manager/mysql/redis/cdn/scheduler for large environments (>100k maybe based on https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_max_connections).

Is there any plan to change this so the number of connections doesn't scale with the number of dfdaemon clients?

Thanks!
Eddie

**Comment by bigerous** [comment]
The manager will not maintain massive connections with DB, see https://gorm.io/docs/generic_interface.html.Indeed the manager will maintain massive grpc connections with dfdaemons, so you need increase Manager server.
As for Scheduler and SeedPeer, you can divide you 100K daemons into several scheduler clusters.

**Comment by embroede** [comment]
Oh ok great, I have done a test and I am seeing this from my end as well. Sorry for the confusion, I thought I had observed this in the past.

Thanks!
