### ISSUE TITLE
您好 想咨询一下dragonfly如何使用s3标准的系统作为仓库

### ISSUE THREAD

**Issue by VertigoSHI** [dragonflyoss/Dragonfly2#1514]

**Comment by gaius-qi** [comment]
现在还没有适配 S3，适配了 OSS。需要在 `pkg/source/clients` 下实现 S3 适配或者通过 [Plugin](https://d7y.io/docs/contribute/development-guide/plugin/) 方式增加 S3 的 Plugin。

比较推荐在 `pkg/source/clients` 下实现 S3 适配, 因为 S3 算比较通用的源站。

**Comment by VertigoSHI** [comment]
好的 非常感谢您的时间

**Comment by embroede** [comment]
Just to confirm, as of now Dragonfly  does not support P2P/caching for S3 compliant storage backends, such as AWS S3?

**Comment by jim3ma** [comment]
> Just to confirm, as of now Dragonfly does not support P2P/caching for S3 compliant storage backends, such as AWS S3?

The http for s3 is okay. Generate the http url for s3 object, then let dragonfly downloads it.
