### ISSUE TITLE
前端service/task页面:点击下一页异常

### ISSUE THREAD

**Issue by orwithout** [dragonflyoss/Dragonfly2#1531]
### Bug report:
![image](https://user-images.githubusercontent.com/19142891/182991460-399bdb8b-eea3-4543-84b0-ab92921d3f64.png)

### Expected behavior:

预期，下一页会显示后续task信息

### How to reproduce it:

使用2.0.5版，
用类似命令提交操过10个任务：

curl --location --request POST 'http://1.2.3.4:8080/api/v1/jobs' \
--header 'Content-Type: application/json' \
--data-raw '{
    "type": "preheat",
    "args": {
        "type": "file",
        "url": "http://1.2.3.5/test.tar.gz"
    }
}' | jq

然后打开类似http://1.2.3.4:8080/service/task 页面进行查看

### Environment:
- Dragonfly version: 
2.0.5
- OS:
rocky8
- Kernel (e.g. `uname -a`):
Linux dfly 4.18.0-372.16.1.el8_6.0.1.x86_64 #1 SMP Thu Jul 14 21:39:58 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- Others:

**Comment by gaius-qi** [comment]
@bigerous
