### ISSUE TITLE
upload total rateLimit

### ISSUE THREAD

**Issue by hyy0322** [dragonflyoss/Dragonfly2#1552]
### Feature request:
Currently peer upload rate limit for per peer. In some case, we need to limit total upload rate for  one peer download by other peers .

**Comment by greenhandatsjtu** [comment]
I think now what we have is the total rateLimit just like you said.
All download requests from other peers will be handled by `*uploadManager.getDownload()` function in which they will go through the same rate limiter `*uploadManager.Limiter`:
https://github.com/dragonflyoss/Dragonfly2/blob/fbb6f1d081b4860760640cf345d0286c8b9c51f9/client/daemon/upload/upload_manager.go#L220-L226

**Comment by gaius-qi** [comment]
The total upload rate limit, not the upload rate limit of a single task.

**Comment by gaius-qi** [comment]
> Hi @hyy0322 , I think now what we have is the total rateLimit just like you said. All download requests from other peers will be handled by `*uploadManager.getDownload()` function in which they will go through the same rate limiter `*uploadManager.Limiter` regardless of their `peerID`, you can refer to code below:
> 
> https://github.com/dragonflyoss/Dragonfly2/blob/fbb6f1d081b4860760640cf345d0286c8b9c51f9/client/daemon/upload/upload_manager.go#L220-L226


The total upload rate limit, not the upload rate limit of a single task.

**Comment by gaius-qi** [comment]
You can use upload ratelimit in `dfget.yaml`.

`ratelimit` is 1MiB.
![image](https://user-images.githubusercontent.com/15955374/185417101-d7d80190-04c1-4502-ae91-9764a25c4ee9.png)

`ratelimit` is 2MiB.
![image](https://user-images.githubusercontent.com/15955374/185417153-50e01ed6-0920-4da1-8f30-7c097a120926.png)

`ratelimit` is 3MiB.
![image](https://user-images.githubusercontent.com/15955374/185417192-0d1b71f2-761e-4c58-abe6-b9e0651d0c9c.png)
