### ISSUE TITLE
On manager v2.0.5 deployed with helm is coming with outdated Console (mentions CDN)

### ISSUE THREAD

**Issue by embroede** [dragonflyoss/Dragonfly2#1568]
### Bug report:

I can see that the latest code for Console has been updated to refer only to Seed Peer instead of CDN, but we just installed v2.0.5 and have an older Console version that references CDN.

### Expected behavior:

A more recent Console version (as the changes to replace CDN with Seed Peer were released before v2.0.5).

### How to reproduce it:

Deploy manager.

### Environment:
- Dragonfly version: v2.0.5
- OS:
- Kernel (e.g. `uname -a`):
- Others:

**Comment by gaius-qi** [comment]
Can you send me a screenshot?

**Comment by embroede** [comment]
So the surprising thing is I went to check today, and it says Seed Peer. I'm wondering if the browser was caching certain pages, as this was previously running v2.0.2

Sorry for the confusion, I will re-open if I see this again, closing for now.
