### ISSUE TITLE
Dashboard-管理服务的go协程数量一直增长

### ISSUE THREAD

**Issue by Liuwenfan** [dragonflyoss/Dragonfly2#1622]
最近查看Dashboard，发现manager的协程数量一直呈上升趋势
最近已经达到1k的量，但查看机器负载并不高
metrics指标: go_goroutines
![image](https://user-images.githubusercontent.com/32165164/187835430-90948bfc-7c6e-47eb-87d4-a7287264613b.png)

**Comment by gaius-qi** [comment]
The `v2.0.8` version has fix this problem.
