### ISSUE TITLE
[dfget] 希望支持多线程从oss回源

### ISSUE THREAD

**Issue by CNjiego** [dragonflyoss/Dragonfly2#1664]
现在首次从oss回源有点慢，希望能支持多线程，回源速度更快
感谢~

**Comment by jim3ma** [comment]
我看了一眼代码，理论上应该是支持的，我这边有空验证一下。

**Comment by jim3ma** [comment]
> 我看了一眼代码，理论上应该是支持的，我这边有空验证一下。

少了一个接口实现，我这边补充一下
