### ISSUE TITLE
dfget peer的监听地址能否支持IPV4/IPV6双栈

### ISSUE THREAD

**Issue by MarukunPC1996** [dragonflyoss/Dragonfly2#1681]
### Feature request:

1.scheduler配置ipv6地址，加括号启动报错，但是不加括号，peer又无法通信

2.peer地址只能监听一个，但是实际需要监听多个：

peer 之间通信和下载配置
  peerGRPC:
    security:
      insecure: true
      cacert: ''
      cert: ''
      key: ''
      tlsVerify: true
    tcpListen:
      # 监听地址
   ### #listen: '[2003::a83a:147a]'                   ----能否支持双栈配置配置多个

**Comment by gaius-qi** [comment]
IPv6 is not currently supported, and support will be considered later. If you are interested, we can contribute together.
