### ISSUE TITLE
How to configure origin-pull download from HDFS

### ISSUE THREAD

**Issue by yjx723** [dragonflyoss/Dragonfly2#1682]
### Feature request:

From introduce guide,  scenarios support HDFS, OSS, NAS, etc.
Failed to get further details.

### Use case:

The storage is on HDFS, need to download from HDFS.

**Comment by jim3ma** [comment]
We will verify the capability with HDFS later. Please wait a while.

**Comment by yjx723** [comment]
Thanks, looking forward to it

**Comment by jim3ma** [comment]
@yjx723 #1702 has fix hdfs not work.

After the PR merged, you can use the follow command to have a try.

```
/opt/dragonfly/bin/dfget -u hdfs://hdfs-namenodes.hdfs.svc:8020/test.txt
```
