### ISSUE TITLE
dfget download through http scheme.

### ISSUE THREAD

**Issue by akashhr7** [dragonflyoss/Dragonfly2#1808]
Hi,

I just wanted to check whether dfget download through http scheme is not neglecting the SSL certificate as InsecureSkipVerify is set to true in http_source_client.go

```
transport := &http.Transport{
		DialContext: (&net.Dialer{
			Timeout:   30 * time.Second,
			KeepAlive: 30 * time.Second,
			DualStack: true,
		}).DialContext,
		IdleConnTimeout:       90 * time.Second,
		ResponseHeaderTimeout: 30 * time.Second,
		ExpectContinueTimeout: 10 * time.Second,
		TLSClientConfig: &tls.Config{
			InsecureSkipVerify: true,
		},
	}

	if proxy != nil {
		transport.Proxy = http.ProxyURL(proxy)
	}

	_defaultHTTPClient = &http.Client{
		Transport: transport,
	}


```
If so, wouldn't it create security issues?

Thanks

**Comment by embroede** [comment]
@jim3ma That would be great if it could be made configurable. I see it is already configurable for `hijackHTTPS` and `registryMirror`.

Thanks,
Eddie

**Comment by embroede** [comment]
@akashhr7 I'm curious why this issue was closed, as [http_source_client.go#L86](https://github.com/dragonflyoss/Dragonfly2/blob/main/pkg/source/clients/httpprotocol/http_source_client.go#L86) is still hard-coded to skip certificate verification

**Comment by akashhr7** [comment]
Closing this issue as it is fixed in PR: https://github.com/dragonflyoss/Dragonfly2/pull/2008/files
