### ISSUE TITLE
Task need a Priority field

### ISSUE THREAD

**Issue by bigerous** [dragonflyoss/Dragonfly2#1883]
### Feature request:

`Task`  struct need a `priority` field to indicate the scheduler how important this task is. Scheduler will schedule according to priority when the resources are limited. 
There are three limited resources in a p2p cluster:
1.  Ability to backsource. 
Sometimes the image source bandwidth is limited, so the concurrent backsource count should be limited to get better performance. 
2. Ability to trigger SeedPeer
Comparing with normal dfdaemon peer, the SeedPeers usually have larger storage disk, longer task expire time and larger bandwith. But the resource of SeedPeer is also limited. When there is too many concurrent task, scheduler need to dicide which task is more important to get the ability to trigger seedPeer.
3. The GC priority in seedPeer storage
SeedPeer's storage is also limited. When the disk is full, SeedPeer need to GC less important task first.

I designed these priorities assocaited with different strategy with the above resources：

|priority Number|Priority Name|Back Source Ability| Seed Peer Trigger Strategy| Seed Peer Store Priority| 
|:-|:-:|:-:|:-:|:-:|
|0| DisableBacksource| disable| disable| disable|
|1| BackSourceLow| dynamically Judge| disable| disable|
|2| BackSourceMust| enable | disable| disable|
|3| SeedPeerLow| enable | dynamically judge| low|
|4| SeedPeerMid| enable | dynamically judge, but suggest to trigger| low|
|5| SeedPeerHigh| enable | dynamically judge, but Strongly suggest to trigger| low |
|6| SeedPeerMust| enable | enable| low |
|7| SeedPeerStoreLow| enable | enable | low |
|8| SeedPeerStoreMid| enable | enable | mid |
|9| SeedPeerStoreHigh| enable | enable| high |
|10| SeedPeerStoreReserve| enable | enable | other strategy |

### Use case:
Priority can be passed with a `--priority xxx` flag through `dfget` command or with `X-Dragonfly-Priority` header through http proxy mode.
If the priority is not set with task, use the DefaultPriority which can be set in `dfget.yaml`

**Comment by gaius-qi** [comment]
The application table adds a priority field, using the json type.
