### ISSUE TITLE
自动签发证书支持多IP/主机名 (Scheduler)

### ISSUE THREAD

**Issue by gzzchh** [dragonflyoss/Dragonfly2#1887]
### Feature request:

支持 Scheduler 在自动获取证书的时候通过 certSpec.ipAddresses 指定其他附加的 IP 或其他主机名.

### Use case:

适配运行环境有多个IP的情况,如直接运行于主机. 也适用于当schduler位于docker中的环境 (关于这点我会在下面补充).

### UI Example:

无

~~还是希望文档在关于TLS方面加点内容~~

**Comment by gaius-qi** [comment]
对于 Peer 和 Scheduler 证书，我都提供了 ipAddresses 和 dnsNames 的 SANs 配置，我把 AdvertiseIP 默认加入到 ipAddresses 内了。参考文档:

Peer 的 https://d7y.io/docs/next/reference/configuration/dfdaemon:
![image](https://user-images.githubusercontent.com/15955374/208409694-4680812c-efd2-4e38-a5e6-1c71f9b7c746.png)

Scheduler https://d7y.io/docs/next/reference/configuration/scheduler:
![image](https://user-images.githubusercontent.com/15955374/208409798-1a152904-a4da-45d8-b0c1-0a5cd95a9b69.png)
