### ISSUE TITLE
syncPieceViaHTTPS 未能使请求使用 https

### ISSUE THREAD

**Issue by gzzchh** [dragonflyoss/Dragonfly2#1980]
### Bug report:

开启 `syncPieceViaHTTPS` 后请求 Peer 下载并未走 HTTPS

### Expected behavior:

当然是走 HTTPS 下载啦

### How to reproduce it:

参考此处配置:

https://github.com/dragonflyoss/Dragonfly2/issues/1886#issuecomment-1374943408

### Environment:
- Dragonfly version: [v2.0.9-alpha.8](https://github.com/dragonflyoss/Dragonfly2/releases/tag/v2.0.9-alpha.8)
- OS: Fedora
- Kernel (e.g. `uname -a`): 6.0.16-300.fc37.x86_64
- Others:

**Comment by gaius-qi** [comment]
@jim3ma

**Comment by jim3ma** [comment]
@gzzchh 代码已经在 #2329 里修改了，你可以测试一下，目前可能没有对应的 E2E 测试，等当前 CI 过了，我们看看怎么添加一个。
