### ISSUE TITLE
Scheduler's conccurent map has performance problem

### ISSUE THREAD

**Issue by bigerous** [dragonflyoss/Dragonfly2#2058]
Now scheduler use third-party [conccurent-map](https://github.com/orcaman/concurrent-map) library in DAG engine.  conccurent-map is a high-performance conccurent map in most cases. But the DAG need frequently KEYS operation, which the conccurent-map library is not good at. It becomes the performance bottle when a Task have pretty much Peers. See the flame graph below:
![image](https://user-images.githubusercontent.com/56508337/217714788-d5d53b25-e732-4c0b-bd44-b5423e4dcb35.png)

**Comment by gaius-qi** [comment]
### [Concurrent Map](https://github.com/orcaman/concurrent-map) benchmark tests:
#### 12 CPU Core and 100 Goroutines
![image](https://user-images.githubusercontent.com/15955374/217743082-f455b84a-cd35-4de9-9f6c-6ac8bf7ccda5.png)

#### 12 CPU Core and 1000 Goroutines
![image](https://user-images.githubusercontent.com/15955374/217743145-6287aca3-a400-460d-8eff-120b40d14f08.png)

#### 12 CPU Core and 10000 Goroutines
![image](https://user-images.githubusercontent.com/15955374/217743650-037b684d-b7ce-4672-8e59-f640c9de80c1.png)

### Benchmark tests:
#### Concurrent Map
![image](https://user-images.githubusercontent.com/15955374/217740847-21bdf359-6b97-4576-a814-9f2dc2e28168.png)
![image](https://user-images.githubusercontent.com/15955374/217740882-f071500e-c771-4509-9b39-5c1e1cb5daf0.png)

#### sync.Map
![image](https://user-images.githubusercontent.com/15955374/217741462-43281834-ba7d-4c6f-95d4-2d4951d5173b.png)

![image](https://user-images.githubusercontent.com/15955374/217741090-98f38c65-648c-4ce6-930d-4052509734a4.png)
