### ISSUE TITLE
[Feature Request] Static network topology scheduler searcher

### ISSUE THREAD

**Issue by jim3ma** [dragonflyoss/Dragonfly2#2099]
### Feature request:

In many public cloud environment, there is only single VPC with multiple regions in production, and the network topology in multiple regions is static and mutually independent in most cases.

In this scenario, the scheduler searcher can just search scheduler clusters by network topology.

### Use case:

There is 3 regions in VPC 1, region A, B, C and D, network topology:

| Region | CIDR | Scheduler cluster |
| --- | --- | --- |
| A | 10.0.0.0/10 | S1 |
| B | 10.64.0.0/10 | S2 |
| C | 10.128.0.0/10 | S3 |
| D | 10.192.0.0/10 | S4 |

The searcher can search scheduler clusters by network topology CIDR instead of any other options.

**Comment by gaius-qi** [comment]
https://github.com/yl2chen/cidranger
