### ISSUE TITLE
 SHA256 checksum check for Oras resource client downloads.

### ISSUE THREAD

**Issue by akashhr** [dragonflyoss/Dragonfly2#2215]
### Bug report:

Consider a user has pulled the image using the oras plugin as :

``` dfget -u oras://hostname/image1:latest ```  

(let us assume image as **image1** and tag as **latest**)

let us assume a user  has made some changes in the docker file of image1 ,rebuild the image1, pushed it to the harbor registry
and tagged this newly re-build image as latest , moved the older  image which is present in the d7y cache now to tag v1 in harbor registry and dragonfly did not run the gc during this interval

now when user try to download the **latest** tag rebuild image using oras plugin ,then d7y won't be knowing there is a new re-build image in the harbor registry and it just serves the download request from the d7y cache which is the image1 tagged as v1 now .

### Expected behavior:

SHA256 check should be enabled for every image pull through the oras plugin.

@embroede

**Comment by akashhr** [comment]
we will recommend to check the manifest for each image pull as per the OCI registry https://github.com/opencontainers/image-spec/blob/main/manifest.md

**Comment by jim3ma** [comment]
To implement this feature, we need query very oras request with tag from registry for real-time.
Steps:
1. fetch metadata form registry, extract the sha256 like: `example.com/public/test:latest` to `example.com/public/test@sha256:ba4xxx`
2. rewrite original request with sha256 which will be sent to dfget daemon.
3. normal processes.
