### ISSUE TITLE
ARM64 images for manager and scheduler

### ISSUE THREAD

**Issue by bodgit** [dragonflyoss/Dragonfly2#2307]
### Feature request:

I've deployed Dragonfly 2.0.9 into my EKS cluster which currently has a mix of x86_64 and aarch64 nodes. It looks like the dfdaemon image is available for linux/arm64 so the seed-peer and dfdaemon Pods happily run anywhere but I found I had to pin the manager and scheduler Pods to only run on the x86_64 nodes.

It would be great to also have linux/arm64 images for the manager and scheduler components.

### Use case:

![image](https://user-images.githubusercontent.com/559268/235142359-f0e1ec11-1ee7-474a-b8e3-7f612fd4fb92.png)

**Comment by gaius-qi** [comment]
Fix https://github.com/dragonflyoss/Dragonfly2/actions/runs/4890363663
