### ISSUE TITLE
Permission of dataDir directory configured in the configuration files.

### ISSUE THREAD

**Issue by akashhr** [dragonflyoss/Dragonfly2#2317]
By default the permission of the **dataDir** directory configured in the configuration file in 755.

Which provides others users the read and execute permissions on the images (private images too)  stored in the cache which could lead to security issues 

so pls remove the read and execute permission of the dataDir for others or  provide the way to configure the permissions of the dataDir directory in the configuration files itself.

**Comment by embroede** [comment]
#2340 is merged, this can be closed now :+1:
