### ISSUE TITLE
客户端v2.0.9 使用dfstoe cp 下载报错

### ISSUE THREAD

**Issue by kids12138** [dragonflyoss/Dragonfly2#2326]
步骤1 使用dfstore cp本地上传文件到远端存储 成功
![image](https://user-images.githubusercontent.com/41765539/236617299-09957191-bfb7-480d-8f19-29e296030e75.png)

步骤2 使用dfstore 将远端文件下载到本地失败
![image](https://user-images.githubusercontent.com/41765539/236617329-e24333a6-87f5-4dd0-b362-cdd0e323adc7.png)
### 

>

**Comment by gaius-qi** [comment]
@kids12138 无法复现，请给出复现具体流程。
