### ISSUE TITLE
配置了全局proxy，但服务下载文件时未通过蜻蜓下载

### ISSUE THREAD

**Issue by ZhANGJNG** [dragonflyoss/Dragonfly2#2339]
### Bug report:

使用helm chart1.0.2版本部署dragonfly，暴露65001端口
其它机器设置全局代理，使用dragonfly 65001
其它服务中下载时连接到代理端口，但下载文件时走的是公网下载，未通过蜻蜓下载
dfget配置如下，部分私密信息已特殊处理
`    aliveTime: 0s
    gcInterval: 1m0s
    keepStorage: true
    workHome: 
    logDir: 
    cacheDir: 
    pluginDir: 
    dataDir: /var/lib/dragonfly
    console: true
    health:
      path: /server/ping
      tcpListen:
        port: 40901
    verbose: false
    metrics: ":8000"
    scheduler:
      manager:
        enable: true
        netAddrs:
        - type: tcp
          addr: dragonfly.manager:65003
        refreshInterval: 10m
        seedPeer:
          clusterID: 4
          enable: true
          keepAlive:
            interval: 5s
          type: super
      scheduleTimeout: 30s
      disableAutoBackSource: false
    host:
      idc: huawei-wulanchabu
      location: wulanchabu
    download:
      calculateDigest: true
      downloadGRPC:
        security:
          insecure: true
          tlsVerify: false
        unixListen:
          socket: ""
      peerGRPC:
        security:
          insecure: true
        tcpListen:
          port: 65000
      perPeerRateLimit: 1024Mi
      prefetch: false
      totalRateLimit: 2048Mi
    upload:
      rateLimit: 2048Mi
      security:
        insecure: true
        tlsVerify: false
      tcpListen:
        port: 65002
    storage:
      diskGCThresholdPercent: 90
      multiplex: true
      strategy: io.d7y.storage.v2.simple
      taskExpireTime: 24h
    proxy:
      defaultFilter: Expires&Signature&ns
      defaultTag: 
      tcpListen:
        namespace: /run/dragonfly/net
        port: 
      security:
        insecure: true
        tlsVerify: false
      registryMirror:
        dynamic: true
        insecure: true
        url: http://image.docker:5001
      proxies:
        - regx: ^http://.*obs:[0-9]*/(.*)
          redirect: http://myhuaweicloud.com/$1
        - regx: blobs/sha256.*
        - regx: https://myhuaweicloud.com/.*
    objectStorage:
      enable: false
      filter: Expires&Signature&ns
      maxReplicas: 3
      security:
        insecure: true
        tlsVerify: false
      tcpListen:
        port: 65004
    security:
      autoIssueCert: false
      caCert: ""
      certSpec:
        dnsNames:
        - dragonfly-seed-peer
        - dragonfly-seed-peer.dragonfly-system.svc
        - dragonfly-seed-peer.dragonfly-system.svc.cluster.local
        ipAddresses: null
        validityPeriod: 4320h
      tlsPolicy: prefer
      tlsVerify: false
    network:
      enableIPv6: false
    announcer:
      schedulerInterval: 30s`

### Expected behavior:

希望其它服务能通过蜻蜓代理下载文件

### Environment:

- Dragonfly version: helm chart version1.0.2 dragonfly2 version：v2.0.9
- OS:centos
- Kernel (e.g. `uname -a`):
- Others:

**Comment by gaius-qi** [comment]
@ZhANGJNG 请提供完整配置文件、日志、以及复现步骤。

你这个连配置 yaml 的格式，不能提供个正常的么，这个我没法看。

**Comment by gaius-qi** [comment]
@ZhANGJNG 请不要配置 hijackHTTPS

**Comment by ZhANGJNG** [comment]
删除 hijackHTTPS的配置，测试与上面的结果一样

**Comment by gaius-qi** [comment]
@ZhANGJNG 
`curl -x` 走 65001 下载，然后把配置文件和完整日志文件发我。不要截图！
