### ISSUE TITLE
AKS with containerD: Images pulling fails

### ISSUE THREAD

**Issue by JorTurFer** [dragonflyoss/Dragonfly2#2523]
### Bug report:

I’m trying out dragonfly and I have installed it using helm. My cluster is an AKS with containerD, so I have followed the documentation about containerD (I have tried both options). My problem is that after dragonfly-dfdaemon patches containerD, I can’t pull any image and I see this error all the time in pod events:

```bash
Failed to pull image "nginx": rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/library/nginx:latest": failed to unpack image on snapshotter overlayfs: unexpected media type text/html for sha256:723cc6bcc69478b1942d6796f2bcf2f67af9efa9974a3c8a0716d162721485bb: not found

or

Failed to pull image "busybox:latest": rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/library/busybox:latest": failed to unpack image on snapshotter overlayfs: unexpected media type text/html for sha256:723cc6bcc69478b1942d6796f2bcf2f67af9efa9974a3c8a0716d162721485bb: not found
```

TBH; I don’t have any idea about how to follow with this, could you give me any tip?

I’m setting these values in helm:
```yaml
containerRuntime:
  containerd:
    configFileName: ""
    configPathDir: /etc/containerd
    enable: true
    injectConfigPath: false # I have also tried with true here 
    injectRegistryCredencials:
      auth: ""
      enable: false
      identitytoken: ""
      password: ""
      username: ""
    registries:
    - https://ghcr.io
    - https://quay.io
    - https://docker.io
```
We are using latest helm version

### Expected behavior:

Images are pulled and the cluster works

### How to reproduce it:

Deploy Dragonfly using helm in AKS

### Environment:

- Dragonfly version: `dfdaemon:v2.1.0-alpha.6`
- OS: `linux`
- Kernel (e.g. `uname -a`): `5.15.0-1038-azure`
- Others: 
	- containerD: `containerd://1.7.1+azure-1`
	- kubelet: `v1.25.6`

**Comment by gaius-qi** [comment]
@JorTurFer Can you send me the dfdaemon logs => `/var/log/dragonfly/daemon/*.log`

**Comment by JorTurFer** [comment]
Sure, let me enable it again, I'll post it in a few minutes

**Comment by AleksuKey** [comment]
Interested!

**Comment by JorTurFer** [comment]
Any update @gaius-qi ?

**Comment by gaius-qi** [comment]
> Any update @gaius-qi ?

According to the log, p2p is downloaded successfully. You can check the containerd log and open the debug log of dragonfly dfdaemon with verbose set to true.

**Comment by JorTurFer** [comment]
Sure! Let me install dragonfly again and give another try. I'll post the logs in a few minutes

**Comment by gaius-qi** [comment]
Send me containerd’s logs and configuration files. Send me dragonfly's logs and configuration files.

**Comment by gaius-qi** [comment]
Dragonfly logs dir /var/log/dragonfly/，config file /etc/dragonfly/dfget.yaml

**Comment by JorTurFer** [comment]
I have sent you a zip package by slack, but I can upload here if you prefer this channel

**Comment by gaius-qi** [comment]
Sorry, I've fixed it 🙏

Fixed incorrect dockerhub domain name being injected when using containerd config_path, this refer to https://github.com/dragonflyoss/helm-charts/pull/198.

![image](https://github.com/dragonflyoss/Dragonfly2/assets/15955374/eca656c1-5f71-43db-b073-0f322777d81d)

**Comment by JorTurFer** [comment]
This is solved, sorry because I forgot to close it
