### ISSUE TITLE
使用helm charts部署的一些疑问

### ISSUE THREAD

**Issue by wangqu123456** [dragonflyoss/Dragonfly2#2620]
官网中的组件还有dfstore和dfcache，helm charts部署时没有这两个组件相关的内容，是去掉了，还是说跟其他组件做到一起了？

**Comment by gaius-qi** [comment]
dfstore 和 dfcache 直接使用 https://github.com/dragonflyoss/Dragonfly2/releases/tag/v2.1.0 二进制包就可以，helm charts 安装的是 dfdaemon，也就是每个 peer 的常驻 P2P 分发客户端。dfstore 和 dfcache本质就是命令行工具调用的 dfdameon 的 grpc 接口进行下载的。所有直接使用 release 的二进制包就可以。

**Comment by wangqu123456** [comment]
感谢解答！



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年08月09日 19:54 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [dragonflyoss/Dragonfly2] 使用helm charts部署的一些疑问 (Issue #2620) |

dfstore 和 dfcache 直接使用 https://github.com/dragonflyoss/Dragonfly2/releases/tag/v2.1.0 二进制包就可以，helm charts 安装的是 dfdaemon，也就是每个 peer 的常驻 P2P 分发客户端。dfstore 和 dfcache本质就是命令行工具调用的 dfdameon 的 grpc 接口进行下载的。所有直接使用 release 的二进制包就可以。
