### ISSUE TITLE
Dfdaemon tries to read from <cacheDir>/dynconfig/daemon/metadata

### ISSUE THREAD

**Issue by embroede** [dragonflyoss/Dragonfly2#2641]
### Bug report:

It appears dfdaemon expects `<cacheDir>/dynConfig/daemon` to be a directory, but we are observing that it is created as a file.

```json
{"level":"warn","ts":"2023-08-14 15:30:20.154","caller":"storage/storage_manager.go:694","msg":"open task metadata error: open <cacheDir>/dynconfig/daemon/metadata: not a directory","action":"reload","stage":"read metadata","taskID":"dynconfig","peerID":"daemon"
```

### Expected behavior:

No error.

### How to reproduce it:

Start a download on dfdaemon v2.0.9 in proxy mode

### Environment:

- Dragonfly version: v2.0.9

**Comment by gaius-qi** [comment]
The new version has been fixed.
