### ISSUE TITLE
关于云服务提供商对于dragonfly的使用疑问

### ISSUE THREAD

**Issue by wangqu123456** [dragonflyoss/Dragonfly2#2702]
我在项目文件中看到了使用dragonfly的云服务提供商，本来准备在阿里云的容器服务中实际体验一下，但是发现他们的ack-acr-acceleration-p2p应用使用的实际上是dadi这个项目，我现在比较困惑，阿里云到底有没有用到dragonfly这个项目呢。

**Comment by gaius-qi** [comment]
这个是阿里云的 Dragonfly 使用文档: https://www.alibabacloud.com/help/en/acr/user-guide/use-the-p2p-acceleration-feature-in-ask-and-ack-clusters

DADI 和 Dragonfly 实际上是不同的，DADI 是按需下载，Dragonfly 是 P2P 分发。
