### ISSUE TITLE
Add unit test for manager handlers

### ISSUE THREAD

**Issue by gaius-qi** [dragonflyoss/Dragonfly2#2705]
### Feature request:
https://github.com/dragonflyoss/Dragonfly2/tree/main/manager/handlers

**Comment by RISHIKESHk07** [comment]
hey @gaius-qi i would like to try , could you tell me what i would i need to  do i am total beginner

**Comment by gaius-qi** [comment]
> hey @gaius-qi i would like to try , could you tell me what i would i need to do i am total beginner

Just write it according to Golang’s unit testing specifications, refer to https://github.com/dragonflyoss/Dragonfly2/blob/main/scheduler/service/service_v2_test.go.

**Comment by RISHIKESHk07** [comment]
@gaius-qi would I have to make an unit test for every handler  file in handlers folder

**Comment by gaius-qi** [comment]
> @gaius-qi would I have to make an unit test for every handler  file in handlers folder
> 
> 
Yes

**Comment by BruceAko** [comment]
@gaius-qi Could you please assign the task to me? I'd like to try it as my first entry-level task in `Dragonfly2` for OSPP, thanks :)

**Comment by gaius-qi** [comment]
> @gaius-qi Could you please assign the task to me? I'd like to try it as my first entry-level task in `Dragonfly2`, thanks :)

@BruceAko PR is welcome.

**Comment by BruceAko** [comment]
Hey @gaius-qi, I have a question. The manager **handlers** will call **service** which will operate on database with a call chain like `h.CreateApplication -> h.service.CreateApplication -> s.db.Create()`. My question is that when I write a unit test for a handler, which of the following approaches should I take to implement the CRUD operations on the service.db:
1. connect to a real database and operate on it
2. mock db's create(), update(), etc. methods
3. mock service's CreateApplication(), etc. methods

related code:
```go
// The method I want to write a unit test for:
func (h *Handlers) CreateApplication(ctx *gin.Context) {
	var json types.CreateApplicationRequest
	if err := ctx.ShouldBindJSON(&json); err != nil {
		ctx.JSON(http.StatusUnprocessableEntity, gin.H{"errors": err.Error()})
		return
	}

	application, err := h.service.CreateApplication(ctx.Request.Context(), json)
	if err != nil {
		ctx.Error(err)
		return
	}

	ctx.JSON(http.StatusOK, application)
}
```

```go
// service's method which is called
func (s *service) CreateApplication(ctx context.Context, json types.CreateApplicationRequest) (*models.Application, error) {
        /*omitted codes*/

	if err := s.db.WithContext(ctx).Create(&application).Error; err != nil {
		return nil, err
	}

	return &application, nil
}
```
Thanks!

**Comment by gaius-qi** [comment]
Testing the handler requires mocking the Service's functions. 
Testing the Service's requires mocking the db with third-party libraries.
