### ISSUE TITLE
Out of tree customize protocol resource support

### ISSUE THREAD

**Issue by jim3ma** [dragonflyoss/Dragonfly2#276]
### Feature request:

Currently, when need implement custom protocol resource downloading, we must make it in tree.
Sometimes, we can not make our private code in tree, so we need a mechanism to do this.

[go plugin](https://golang.org/pkg/plugin/) can make private code out of tree. 

Code example:

```
package main

import (
	"bytes"
	"io"
)

type client struct {
}

func (c *client) GetContentLength(url string, headers map[string]string) (int64, error) {
	return 11, nil
}

func (c *client) IsSupportRange(url string, headers map[string]string) (bool, error) {
	return false, nil
}

func (c *client) IsExpired(url string, headers, expireInfo map[string]string) (bool, error) {
	return false, nil
}

func (c *client) Download(url string, headers map[string]string) (io.ReadCloser, map[string]string, error) {
	return io.NopCloser(bytes.NewBufferString("hello world")), map[string]string{}, nil
}

func DragonflyPluginInit() (interface{}, map[string]string, error) {
	return &client{}, map[string]string{"schema": "afs"}, nil
}
```

### Use case:

Custom protocol resource plugin: `d7y-resource-plugin-afs.so`, location: `dfpath.WorkHome/plugins`

When download `afs://example.com/dir/object` from source, dragonfly cdn and client load this plugin and invoke `ResourceClient` downloading API.

### UI Example:

N/A

**Comment by gaius-qi** [comment]
It is recommended that plugin be a separate package. It is easier to manage interface types and plugin storage path.

```golang
import (
	"plugin"
)

const (
    AFSResourcePlugin = "d7y-resource-plugin-afs"
)

type Plugin struct {
}

type AFSResourcePluginInterface interface{
}

type OSSResourcePluginInterface interface{
}

func LoadPlugin() (interface{}, error) {
}
```
