### ISSUE TITLE
Preheat failed rpc error: code = DeadlineExceeded desc = context deadline exceeded

### ISSUE THREAD

**Issue by safeAndSound3** [dragonflyoss/Dragonfly2#2968]
Preheat failed.

![image](https://github.com/dragonflyoss/Dragonfly2/assets/146302624/09680bed-bc16-45d2-b5f8-ffbfdb65ac93)
![image](https://github.com/dragonflyoss/Dragonfly2/assets/146302624/043ffe92-5a15-4138-94d5-f99932c89e7c)

**Comment by gaius-qi** [comment]
@safeAndSound3 Please provide complete log.

**Comment by safeAndSound3** [comment]
I used Docker Compose installation to see which container is suitable
![image](https://github.com/dragonflyoss/Dragonfly2/assets/146302624/24ed9701-6f6b-4ef9-b7cd-e41a621dc5a9)

**Comment by safeAndSound3** [comment]
manager => /var/log/dragonfly/manager/core.log
{"level":"info","ts":"2023-12-22 08:34:30.588","caller":"job/job.go:135","msg":"task is not succeeded: &tasks.TaskState{TaskUUID:\"task_6a7d2dec-f785-49b8-917d-36e0c3e743ac\", TaskName:\"preheat\", State:\"PENDING\", Results:[]*tasks.TaskResult(nil), Error:\"\", CreatedAt:time.Date(2023, time.December, 22, 8, 8, 9, 484666404, time.UTC), TTL:0}","groupID":"group_47f7bdb5-0e56-41c3-b30a-b00a78727217","taskID":"task_6a7d2dec-f785-49b8-917d-36e0c3e743ac"}
{"level":"debug","ts":"2023-12-22 08:34:30.589","caller":"service/job.go:138","msg":"trace","elapsed":0.000789998,"rows":1,"sql":"SELECT * FROM `job` WHERE `job`.`id` = 5 AND `job`.`is_del` = 0 AND `job`.`id` = 5 ORDER BY `job`.`id` LIMIT 1"}
{"level":"debug","ts":"2023-12-22 08:34:30.591","caller":"service/job.go:138","msg":"trace","elapsed":0.002426496,"rows":1,"sql":"UPDATE `job` SET `updated_at`='2023-12-22 08:34:30.59',`state`='PENDING',`result`='{\"CreatedAt\":\"2023-12-22T08:08:09.484666404Z\",\"GroupUUID\":\"group_47f7bdb5-0e56-41c3-b30a-b00a78727217\",\"JobStates\":[{\"CreatedAt\":\"2023-12-22T08:08:09.484666404Z\",\"Error\":\"\",\"Results\":null,\"State\":\"PENDING\",\"TTL\":0,\"TaskName\":\"preheat\",\"TaskUUID\":\"task_6a7d2dec-f785-49b8-917d-36e0c3e743ac\"},{\"CreatedAt\":\"2023-12-22T08:08:09.485413003Z\",\"Error\":\"\",\"Results\":null,\"State\":\"STARTED\",\"TTL\":0,\"TaskName\":\"preheat\",\"TaskUUID\":\"task_7c3d316d-d81d-43bc-b17f-f3a6618c2311\"},{\"CreatedAt\":\"2023-12-22T08:08:09.490455764Z\",\"Error\":\"\",\"Results\":null,\"State\":\"PENDING\",\"TTL\":0,\"TaskName\":\"preheat\",\"TaskUUID\":\"task_be8bdc67-7295-48fb-85e8-c46441bfcbb0\"},{\"CreatedAt\":\"2023-12-22T08:08:09.493411564Z\",\"Error\":\"\",\"Results\":null,\"State\":\"PENDING\",\"TTL\":0,\"TaskName\":\"preheat\",\"TaskUUID\":\"task_6dce9c3a-eda7-476d-a9d9-cb0a3f87f87b\"},{\"CreatedAt\":\"2023-12-22T08:08:09.494758344Z\",\"Error\":\"\",\"Results\":null,\"State\":\"PENDING\",\"TTL\":0,\"TaskName\":\"preheat\",\"TaskUUID\":\"task_b7239318-fe1d-4894-a724-96c788355d6e\"},{\"CreatedAt\":\"2023-12-22T08:08:09.495046721Z\",\"Error\":\"\",\"Results\":null,\"State\":\"PENDING\",\"TTL\":0,\"TaskName\":\"preheat\",\"TaskUUID\":\"task_c7e5577b-abd4-4cd3-a040-2523c7d6eb06\"},{\"CreatedAt\":\"2023-12-22T08:08:09.495319529Z\",\"Error\":\"\",\"Results\":null,\"State\":\"PENDING\",\"TTL\":0,\"TaskName\":\"preheat\",\"TaskUUID\":\"task_6d8c5f6e-6dd6-4b24-a02c-0a5ca40f8947\"},{\"CreatedAt\":\"2023-12-22T08:08:09.495627294Z\",\"Error\":\"\",\"Results\":null,\"State\":\"PENDING\",\"TTL\":0,\"TaskName\":\"preheat\",\"TaskUUID\":\"task_1876e990-418c-4fe8-a483-a5f6fa2f6bb3\"},{\"CreatedAt\":\"2023-12-22T08:08:09.49589875Z\",\"Error\":\"\",\"Results\":null,\"State\":\"PENDING\",\"TTL\":0,\"TaskName\":\"preheat\",\"TaskUUID\":\"task_0e9117df-605e-4e99-bfe5-35a6af39b4cb\"}],\"State\":\"PENDING\"}' WHERE `job`.`id` = 5 AND `job`.`is_del` = 0 AND `job`.`id` = 5 AND `id` = 5 ORDER BY `job`.`id` LIMIT 1"}
{"level":"info","ts":"2023-12-22 08:34:30.592","caller":"service/job.go:168","msg":"polling job state is PENDING","groupID":"group_47f7bdb5-0e56-41c3-b30a-b00a78727217","jobID":"5"}
{"level":"error","ts":"2023-12-22 08:34:39.289","caller":"job/job.go:123","msg":"task is failed: &tasks.TaskState{TaskUUID:\"task_7c3d316d-d81d-43bc-b17f-f3a6618c2311\", TaskName:\"preheat\", State:\"FAILURE\", Results:[]*tasks.TaskResult(nil), Error:\"rpc error: code = DeadlineExceeded desc = context deadline exceeded\", CreatedAt:time.Date(2023, time.December, 22, 8, 8, 9, 485413003, time.UTC), TTL:0}","groupID":"group_47f7bdb5-0e56-41c3-b30a-b00a78727217","taskID":"task_7c3d316d-d81d-43bc-b17f-f3a6618c2311","stacktrace":"d7y.io/dragonfly/v2/internal/job.(*Job).GetGroupJobState\n\t/go/src/d7y.io/dragonfly/v2/internal/job/job.go:123\nd7y.io/dragonfly/v2/manager/service.(*service).pollingJob.func1\n\t/go/src/d7y.io/dragonfly/v2/manager/service/job.go:139\nd7y.io/dragonfly/v2/pkg/retry.Run\n\t/go/src/d7y.io/dragonfly/v2/pkg/retry/retry.go:41\nd7y.io/dragonfly/v2/manager/service.(*service).pollingJob\n\t/go/src/d7y.io/dragonfly/v2/manager/service/job.go:138"}
{"level":"debug","ts":"2023-12-22 08:34:39.290","caller":"service/job.go:138","msg":"trace","elapsed":0.000748431,"rows":1,"sql":"SELECT * FROM `job` WHERE `job`.`id` = 5 AND `job`.`is_del` = 0 AND `job`.`id` = 5 ORDER BY `job`.`id` LIMIT 1"}
{"level":"debug","ts":"2023-12-22 08:34:39.298","caller":"service/job.go:138","msg":"trace","elapsed":0.008373438,"rows":1,"sql":"UPDATE `job` SET `updated_at`='2023-12-22 08:34:39.29',`state`='FAILURE',`result`='{\"CreatedAt\":\"2023-12-22T08:08:09.485413003Z\",\"GroupUUID\":\"group_47f7bdb5-0e56-41c3-b30a-b00a78727217\",\"JobStates\":[{\"CreatedAt\":\"2023-12-22T08:08:09.484666404Z\",\"Error\":\"\",\"Results\":null,\"State\":\"PENDING\",\"TTL\":0,\"TaskName\":\"preheat\",\"TaskUUID\":\"task_6a7d2dec-f785-49b8-917d-36e0c3e743ac\"},{\"CreatedAt\":\"2023-12-22T08:08:09.485413003Z\",\"Error\":\"rpc error: code = DeadlineExceeded desc = context deadline exceeded\",\"Results\":null,\"State\":\"FAILURE\",\"TTL\":0,\"TaskName\":\"preheat\",\"TaskUUID\":\"task_7c3d316d-d81d-43bc-b17f-f3a6618c2311\"},{\"CreatedAt\":\"2023-12-22T08:08:09.490455764Z\",\"Error\":\"\",\"Results\":null,\"State\":\"STARTED\",\"TTL\":0,\"TaskName\":\"preheat\",\"TaskUUID\":\"task_be8bdc67-7295-48fb-85e8-c46441bfcbb0\"},{\"CreatedAt\":\"2023-12-22T08:08:09.493411564Z\",\"Error\":\"\",\"Results\":null,\"State\":\"STARTED\",\"TTL\":0,\"TaskName\":\"preheat\",\"TaskUUID\":\"task_6dce9c3a-eda7-476d-a9d9-cb0a3f87f87b\"},{\"CreatedAt\":\"2023-12-22T08:08:09.494758344Z\",\"Error\":\"\",\"Results\":null,\"State\":\"STARTED\",\"TTL\":0,\"TaskName\":\"preheat\",\"TaskUUID\":\"task_b7239318-fe1d-4894-a724-96c788355d6e\"},{\"CreatedAt\":\"2023-12-22T08:08:09.495046721Z\",\"Error\":\"\",\"Results\":null,\"State\":\"STARTED\",\"TTL\":0,\"TaskName\":\"preheat\",\"TaskUUID\":\"task_c7e5577b-abd4-4cd3-a040-2523c7d6eb06\"},{\"CreatedAt\":\"2023-12-22T08:08:09.495319529Z\",\"Error\":\"\",\"Results\":null,\"State\":\"PENDING\",\"TTL\":0,\"TaskName\":\"preheat\",\"TaskUUID\":\"task_6d8c5f6e-6dd6-4b24-a02c-0a5ca40f8947\"},{\"CreatedAt\":\"2023-12-22T08:08:09.495627294Z\",\"Error\":\"\",\"Results\":null,\"State\":\"PENDING\",\"TTL\":0,\"TaskName\":\"preheat\",\"TaskUUID\":\"task_1876e990-418c-4fe8-a483-a5f6fa2f6bb3\"},{\"CreatedAt\":\"2023-12-22T08:08:09.49589875Z\",\"Error\":\"\",\"Results\":null,\"State\":\"STARTED\",\"TTL\":0,\"TaskName\":\"preheat\",\"TaskUUID\":\"task_0e9117df-605e-4e99-bfe5-35a6af39b4cb\"}],\"State\":\"FAILURE\"}' WHERE `job`.`id` = 5 AND `job`.`is_del` = 0 AND `job`.`id` = 5 AND `id` = 5 ORDER BY `job`.`id` LIMIT 1"}
{"level":"error","ts":"2023-12-22 08:34:39.298","caller":"service/job.go:164","msg":"polling group failed","groupID":"group_47f7bdb5-0e56-41c3-b30a-b00a78727217","jobID":"5","stacktrace":"d7y.io/dragonfly/v2/manager/service.(*service).pollingJob.func1\n\t/go/src/d7y.io/dragonfly/v2/manager/service/job.go:164\nd7y.io/dragonfly/v2/pkg/retry.Run\n\t/go/src/d7y.io/dragonfly/v2/pkg/retry/retry.go:41\nd7y.io/dragonfly/v2/manager/service.(*service).pollingJob\n\t/go/src/d7y.io/dragonfly/v2/manager/service/job.go:138"}
{"level":"debug","ts":"2023-12-22 08:34:39.521","caller":"gin@v1.9.1/context.go:174","msg":"trace","elapsed":0.000804727,"rows":1,"sql":"SELECT * FROM `job` WHERE `job`.`id` = 5 AND `job`.`is_del` = 0 ORDER BY `job`.`id` LIMIT 1"}
{"level":"debug","ts":"2023-12-22 08:35:15.035","caller":"gin@v1.9.1/context.go:174","msg":"trace","elapsed":0.003860679,"rows":1,"sql":"SELECT * FROM `job_scheduler_cluster` WHERE `job_scheduler_cluster`.`job_id` = 5"}
{"level":"debug","ts":"2023-12-22 08:35:15.036","caller":"gin@v1.9.1/context.go:174","msg":"trace","elapsed":0.000607391,"rows":1,"sql":"SELECT * FROM `scheduler_cluster` WHERE `scheduler_cluster`.`id` = 1 AND `scheduler_cluster`.`is_del` = 0"}
{"level":"debug","ts":"2023-12-22 08:35:15.036","caller":"gin@v1.9.1/context.go:174","msg":"trace","elapsed":0.000457962,"rows":0,"sql":"SELECT * FROM `job_seed_peer_cluster` WHERE `job_seed_peer_cluster`.`job_id` = 5"}
{"level":"debug","ts":"2023-12-22 08:35:15.036","caller":"gin@v1.9.1/context.go:174","msg":"trace","elapsed":0.010192178,"rows":1,"sql":"SELECT * FROM `job` WHERE `job`.`id` = 5 AND `job`.`is_del` = 0 ORDER BY `job`.`id` LIMIT 1"}
{"level":"warn","ts":"2023-12-22 08:35:24.361","caller":"rpcserver/manager_server_v2.go:362","msg":"manager:schedulers:1-0b2308edab9f-62.234.0.198 cache miss because of cache: key is missing","hostname":"0b2308edab9f","ip":"62.234.0.198","stacktrace":"d7y.io/dragonfly/v2/manager/rpcserver.(*managerServerV2).GetScheduler\n\t/go/src/d7y.io/dragonfly/v2/manager/rpcserver/manager_server_v2.go:362\nd7y.io/api/v2/pkg/apis/manager/v2._Manager_GetScheduler_Handler.func1\n\t/go/pkg/mod/d7y.io/api/v2@v2.0.70/pkg/apis/manager/v2/manager_grpc.pb.go:360\ngithub.com/grpc-ecosystem/go-grpc-middleware/recovery.UnaryServerInterceptor.func1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/recovery/interceptors.go:33\nd7y.io/dragonfly/v2/pkg/rpc/manager/server.New.ChainUnaryServer.func5.1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:48\nd7y.io/dragonfly/v2/pkg/rpc/manager/server.New.UnaryServerInterceptor.func3\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/validator/validator.go:47\nd7y.io/dragonfly/v2/pkg/rpc/manager/server.New.ChainUnaryServer.func5.1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:48\ngithub.com/grpc-ecosystem/go-grpc-middleware/logging/zap.UnaryServerInterceptor.func1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/logging/zap/server_interceptors.go:31\nd7y.io/dragonfly/v2/pkg/rpc/manager/server.New.ChainUnaryServer.func5.1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:48\ngithub.com/grpc-ecosystem/go-grpc-prometheus.init.(*ServerMetrics).UnaryServerInterceptor.func3\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/server_metrics.go:107\nd7y.io/dragonfly/v2/pkg/rpc/manager/server.New.ChainUnaryServer.func5.1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:48\nd7y.io/dragonfly/v2/pkg/rpc/manager/server.New.UnaryServerInterceptor.func2\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/ratelimit/ratelimit.go:24\nd7y.io/dragonfly/v2/pkg/rpc/manager/server.New.ChainUnaryServer.func5\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:53\nd7y.io/api/v2/pkg/apis/manager/v2._Manager_GetScheduler_Handler\n\t/go/pkg/mod/d7y.io/api/v2@v2.0.70/pkg/apis/manager/v2/manager_grpc.pb.go:362\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/go/pkg/mod/google.golang.org/grpc@v1.61.0-dev/server.go:1369\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/go/pkg/mod/google.golang.org/grpc@v1.61.0-dev/server.go:1780\ngoogle.golang.org/grpc.(*Server).serveStreams.func2.1\n\t/go/pkg/mod/google.golang.org/grpc@v1.61.0-dev/server.go:1013"}
{"level":"debug","ts":"2023-12-22 08:35:24.364","caller":"recovery/interceptors.go:33","msg":"trace","elapsed":0.000435985,"rows":1,"sql":"SELECT * FROM `seed_peer_cluster_scheduler_cluster` WHERE `seed_peer_cluster_scheduler_cluster`.`scheduler_cluster_id` = 1"}

**Comment by safeAndSound3** [comment]
I use Harbor and Dragonfly to configure the preheating, which will automatically trigger Dragonfly's preheating when pushed to the Harbor warehouse, but now it sometimes fails

**Comment by gaius-qi** [comment]
@safeAndSound3 Please send me the complete log file of the service compressed into .zip and the image version.

**Comment by safeAndSound3** [comment]
[log.tar.gz](https://github.com/dragonflyoss/Dragonfly2/files/13750737/log.tar.gz)
docker image tag is latest
![image](https://github.com/dragonflyoss/Dragonfly2/assets/146302624/34783edb-f313-4c4b-a8d7-fa0350213417)

Could you please check if it is complete enough

**Comment by gaius-qi** [comment]
@safeAndSound3 Try the new version https://github.com/dragonflyoss/Dragonfly2/tree/v2.1.27.

**Comment by daijiezou** [comment]
[dragonfly-log.zip](https://github.com/dragonflyoss/Dragonfly2/files/13757796/dragonfly-log.zip)
I have updated dragonfly to v2.1.27，but still preheat failed rpc error

**Comment by daijiezou** [comment]
I have updated dragonfly to v2.1.27,but still preheat failed rpc error
[dragonfly-log.zip](https://github.com/dragonflyoss/Dragonfly2/files/13757812/dragonfly-log.zip)

**Comment by safeAndSound3** [comment]
I also tested version v2.1.27, but the preheating function still has timeout tasks. Is it related to the size of the image? Also, how can I modify the time zone of Dragonfly and only add it in Docker-Compose.yml
![image](https://github.com/dragonflyoss/Dragonfly2/assets/146302624/1de77c3d-da9f-4e4a-a23a-e75a73258a6e)

**Comment by gaius-qi** [comment]
@safeAndSound3 Please try v2.1.30.
