### ISSUE TITLE
Question about handling EOF from registry

### ISSUE THREAD

**Issue by supakornbabe** [dragonflyoss/Dragonfly2#2978]
### Bug report:

Greetings from Agoda! We're facing an issue with Dragonfly v2.0.3. When a network problem occurs and requests to our Harbor registry only returns EOF, it appears Dragonfly is caching that EOF response. This results in an unexpected EOF error anytime users attempt to pull that image layer.

Error displayed:
```
Failed to pull image "reg-as.agodadev.io/papi/content/content-platform/release:0.8.555": rpc error: code = Unknown desc = failed to pull and unpack image "reg-as.agodadev.io/papi/content/content-platform/release:0.8.555": failed to read expected number of bytes: unexpected EOF
```

Could you please help clarify:
- Does Dragonfly refrain from caching a layer if EOF is returned from the registry?
- Will upgrading to the latest version resolve this issue?

### Expected behavior:

Dragonfly should not cache if EOF is returned from the registry.

### How to reproduce it:

Create a scenario of network instability, such as blocking access from Dragonfly nodes to registry nodes.

### Environment:

- Dragonfly version: 2.0.3
- OS: Centos 7
- Kernel (e.g. `uname -a`): `Linux 3.10.0-1160.53.1.el7.x86_64 #1 SMP Fri Jan 14 13:59:45 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
- Others: -

If any information needed please let me know.
Thank you for creating and maintaining such an excellent product.

Merry Christmas 🎄 and Happy new year 🥳

**Comment by MouseSun846** [comment]
I also encountered the same problem, how to solve it?

**Comment by CormickKneey** [comment]
> I also encountered the same problem, how to solve it?

Hi, the version you are using is outdated. Please try using the latest version. If you encounter any issues adapting to the new version, feel free to ask at any time~ 
@supakornbabe @MouseSun846

**Comment by CormickKneey** [comment]
> > > I also encountered the same problem, how to solve it?
> > 
> > 
> > Hi, the version you are using is outdated. Please try using the latest version. If you encounter any issues adapting to the new version, feel free to ask at any time~ @supakornbabe @MouseSun846
> 
> The version I am using is V2.16.0.

Could you provide the tag link under https://github.com/dragonflyoss/Dragonfly2/releases?  
If you still encounter this issue under [v2.1.63](https://github.com/dragonflyoss/Dragonfly2/releases/tag/v2.1.63), please provide more information(how to reproduce the issue) please~
