### ISSUE TITLE
trigger seed peer timeout

### ISSUE THREAD

**Issue by daijiezou** [dragonflyoss/Dragonfly2#3022]
### Bug report:
After the service has been running for about 30 minutes,scheduler call to seedpeer timeout  with a high probability

### Environment:

- Dragonfly version: 2.1.24
- OS: ubuntu18.04
- Kernel (e.g. `uname -a`):4.15.0-112-generic
- Others:

**Comment by daijiezou** [comment]
[grpc.zip](https://github.com/dragonflyoss/Dragonfly2/files/13918457/grpc.zip)

**Comment by daijiezou** [comment]
<img width="430" alt="企业微信截图_17050511632048" src="https://github.com/dragonflyoss/Dragonfly2/assets/53129911/ce2aad9a-8bd4-4865-a059-488488ca144a">
view tcp connections in the seed-peer pod,a connection to the scheduler was found to be interrupted after 30 minutes of service start

**Comment by gaius-qi** [comment]
@daijiezou Please try v2.1.30.
