### ISSUE TITLE
Dragonfly web management page unable to view preheating details 

### ISSUE THREAD

**Issue by zsksy123** [dragonflyoss/Dragonfly2#3033]
![image](https://github.com/dragonflyoss/Dragonfly2/assets/58408116/2cc875d2-7b3b-479e-b8f3-36bf789c67f1)
Failed and ongoing preheating tasks cannot view preheating details
![image](https://github.com/dragonflyoss/Dragonfly2/assets/58408116/4996fae2-7057-4bb1-951b-6a5bb3f2db89)
![image](https://github.com/dragonflyoss/Dragonfly2/assets/58408116/81b09ea5-e559-44bb-9860-00dbb4367a9e)
![image](https://github.com/dragonflyoss/Dragonfly2/assets/58408116/79125edc-92cb-4b60-adb8-c49d204fc680)

Successful preheating tasks can view detailed preheating information
![image](https://github.com/dragonflyoss/Dragonfly2/assets/58408116/31760481-7acc-4e36-8f5a-e4b9751ef9a8)

**Comment by gaius-qi** [comment]
@Liam-Zhao

**Comment by Liam-Zhao** [comment]
@zsksy123 Please send preheat failure response data

**Comment by zsksy123** [comment]
> Please send preheat failure response data

After investigation, it was found that the preheating task was not a failed one and detailed information cannot be viewed

When the API is used to view the preheating information, the detailed information of the preheating task without the Authorization field cannot be displayed on the web page
The details are as follows.

![image](https://github.com/dragonflyoss/Dragonfly2/assets/58408116/bf1c63df-4a17-49a0-a59c-0931e10f1d67)
![image](https://github.com/dragonflyoss/Dragonfly2/assets/58408116/3992e8f9-2851-47f7-845d-dad9f761a765)

**Comment by zsksy123** [comment]
Preheating through the Open API will not work even if the Authorization field is added, but preheating tasks created through the console will

**Comment by Liam-Zhao** [comment]
@zsksy123 

The error occurred because you set headers to null, so the page cannot be accessed. This problem has been fixed.

**Comment by zsksy123** [comment]
> The error occurred because you set headers to null, so the page cannot be accessed. This problem has been fixed.

I can't access it this way either

curl --location --request POST "http://${host}/api/v1/jobs" \
--header 'Content-Type: application/json' \
--header "Authorization: ${bearer_token}" \
--data-raw '{
    "type": "preheat",
    "args": {
        "type": "image",
        "url": "https://ghcr.io/v2/dragonflyoss/dragonfly2/manager/manifests/v2.0.5"
    }
}'
