### ISSUE TITLE
dragonfly console 刷新界面报错

### ISSUE THREAD

**Issue by allen-gf** [dragonflyoss/Dragonfly2#3104]
### Bug report:

长时间未退出控制台，再次刷新会报错
![image](https://github.com/dragonflyoss/Dragonfly2/assets/151538872/d955d8bc-346b-49df-8e13-eaef474595d4)

### Environment:

- Dragonfly version: [v2.1.34](https://github.com/dragonflyoss/Dragonfly2/releases/tag/v2.1.34)
k8s容器环境，官方镜像

**Comment by gaius-qi** [comment]
@allen-gf Please use English.
