### ISSUE TITLE
manager console：Error and unfriendly message when deleting cluster

### ISSUE THREAD

**Issue by dreamniu** [dragonflyoss/Dragonfly2#3213]
### Bug report:

<img width="1436" alt="image" src="https://github.com/dragonflyoss/Dragonfly2/assets/17829472/e24eb4e5-f585-47f1-9c49-6db3756d51bc">

Request：
```
Request URL:
https://dragonfly-manager-internal.cnc.xxx.com/api/v1/clusters/4
Request Method:
DELETE
Status Code:
500 Internal Server Error
```

Response:
`{"message":"scheduler cluster exists scheduler"}`

### Environment:

- Dragonfly version: v2.1.0
- OS:
- Kernel (e.g. `uname -a`):
- Others:

**Comment by Liam-Zhao** [comment]
The current version is too low, this problem has been fixed in the new version.
