### ISSUE TITLE
Dragonfly Manager console job preheat blank page

### ISSUE THREAD

**Issue by mansoncui** [dragonflyoss/Dragonfly2#3226]
Python Code: 
#!/usr/bin/python
import requests

url = 'http://dragonfly.test.xxx.com/oapi/v1/jobs'

headers = {
    'Content-Type': 'application/json',
    'Authorization': 'Bearer YTBhM2Y2ZWQtYzUwYS00NGxxxxxxxxMtNTk3ZjI2NDI2N2Rk'
}
data = {
    "type": "preheat",
    "args": {
        "type": "image",
        "url": "https://harbor.test.xxx.com/v2/init-images/centos/manifests/7",
        "filteredQueryParams": "Expires&Signature",
        "username": "admin",
        "password": "xxxxx"
    }
}
response = requests.post(url, headers=headers, json=data)
print(response.status_code)
print(response.text)

![Uploading dragonfly.png…]()

![Uploading image.png…]()

### Environment:
- Dragonfly version: 2.1.30 (helm:1.1.26)
- OS: ubuntu18.04 
- Kernel (e.g. `uname -a`): 5.4.193-0504193-generic 
- Others: helm 安装

**Comment by Liam-Zhao** [comment]
The current version is too low, please upgrade to the latest version.

**Comment by mansoncui** [comment]
helm upgrade 1.1.48

**Comment by mansoncui** [comment]
Already solved
