### ISSUE TITLE
Dragonfly not preheat  harbor 2.6

### ISSUE THREAD

**Issue by mansoncui** [dragonflyoss/Dragonfly2#3231]
The harbor configuration is a public warehouse, and no job task warm-up is created in harbor

docker push  harbor.test.xxx.com/init-images/busybox:latest

<img width="1161" alt="image" src="https://github.com/dragonflyoss/Dragonfly2/assets/29750171/1ff7508e-7c26-4826-bafb-1f55342f6789">

dfdaemon  No error message found 

### Environment:
- Dragonfly version: 2.1.42 (old version 2.1.28)
- OS: ubuntu 18.04 
- Kernel (e.g. `uname -a`): 5.4.193-0504193-generic
- Others: helm install, kubernetes version 1.23.6 run-time :containerd 1.6  image is harbor 2.6

**Comment by gaius-qi** [comment]
@mansoncui  mansoncui Please provide manager logs and scheduler logs.

**Comment by mansoncui** [comment]
manager info:
ND state = 'active' AND `scheduler`.`is_del` = 0"}
{"level":"debug","ts":"2024-04-25 07:46:36.145","caller":"recovery/interceptors.go:33","msg":"trace","elapsed":0.000319262,"rows":1,"sql":"SELECT * FROM `seed_peer_cluster_scheduler_cluster` WHERE `seed_peer_cluster_scheduler_cluster`.`scheduler_cluster_id` = 1"}
{"level":"debug","ts":"2024-04-25 07:46:36.146","caller":"recovery/interceptors.go:33","msg":"trace","elapsed":0.000313925,"rows":1,"sql":"SELECT * FROM `seed_peer` WHERE `seed_peer`.`seed_peer_cluster_id` = 1 AND state = 'active' AND `seed_peer`.`is_del` = 0"}
{"level":"debug","ts":"2024-04-25 07:46:36.146","caller":"recovery/interceptors.go:33","msg":"trace","elapsed":0.000829378,"rows":1,"sql":"SELECT * FROM `seed_peer_cluster` WHERE `seed_peer_cluster`.`id` = 1 AND `seed_peer_cluster`.`is_del` = 0"}
{"level":"debug","ts":"2024-04-25 07:46:36.146","caller":"recovery/interceptors.go:33","msg":"trace","elapsed":0.002427169,"rows":1,"sql":"SELECT * FROM `scheduler_cluster` WHERE `scheduler_cluster`.`is_del` = 0"}
{"level":"debug","ts":"2024-04-25 07:46:36.146","caller":"rpcserver/manager_server_v1.go:579","msg":"list scheduler clusters [cluster-1] with hostInfo map[string]string{\"idc\":\"\", \"location\":\"\"}","hostname":"ops-k8s-testwxnode7.wxxdc","ip":"10.2.55.39"}
{"level":"debug","ts":"2024-04-25 07:46:36.146","caller":"rpcserver/manager_server_v1.go:594","msg":"find matching scheduler cluster [cluster-1]","hostname":"ops-k8s-testwxnode7.wxxdc","ip":"10.2.55.39"}
{"level":"debug","ts":"2024-04-25 07:46:56.159","caller":"rpcserver/manager_server_v2.go:345","msg":"manager:schedulers:1-dragonfly-scheduler-0.scheduler.dragonfly-system.svc.cluster.local-10.222.87.143 cache hit","hostname":"dragonfly-scheduler-0.scheduler.dragonfly-system.svc.cluster.local","ip":"10.222.87.143"}
{"level":"warn","ts":"2024-04-25 07:46:56.160","caller":"rpcserver/manager_server_v2.go:670","msg":"manager:applications cache miss because of cache: key is missing","hostname":"dragonfly-scheduler-0.scheduler.dragonfly-system.svc.cluster.local","ip":"10.222.87.143","stacktrace":"d7y.io/dragonfly/v2/manager/rpcserver.(*managerServerV2).ListApplications\n\t/go/src/d7y.io/dragonfly/v2/manager/rpcserver/manager_server_v2.go:670\nd7y.io/api/v2/pkg/apis/manager/v2._Manager_ListApplications_Handler.func1\n\t/go/pkg/mod/d7y.io/api/v2@v2.0.110/pkg/apis/manager/v2/manager_grpc.pb.go:366\ngithub.com/grpc-ecosystem/go-grpc-middleware/recovery.UnaryServerInterceptor.func1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/recovery/interceptors.go:33\nd7y.io/dragonfly/v2/pkg/rpc/manager/server.New.ChainUnaryServer.func5.1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:48\nd7y.io/dragonfly/v2/pkg/rpc/manager/server.New.UnaryServerInterceptor.func3\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/validator/validator.go:47\nd7y.io/dragonfly/v2/pkg/rpc/manager/server.New.ChainUnaryServer.func5.1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:48\ngithub.com/grpc-ecosystem/go-grpc-middleware/logging/zap.UnaryServerInterceptor.func1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/logging/zap/server_interceptors.go:31\nd7y.io/dragonfly/v2/pkg/rpc/manager/server.New.ChainUnaryServer.func5.1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:48\ngithub.com/grpc-ecosystem/go-grpc-prometheus.init.(*ServerMetrics).UnaryServerInterceptor.func3\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/server_metrics.go:107\nd7y.io/dragonfly/v2/pkg/rpc/manager/server.New.ChainUnaryServer.func5.1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:48\nd7y.io/dragonfly/v2/pkg/rpc/manager/server.New.UnaryServerInterceptor.func2\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/ratelimit/ratelimit.go:24\nd7y.io/dragonfly/v2/pkg/rpc/manager/server.New.ChainUnaryServer.func5\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:53\nd7y.io/api/v2/pkg/apis/manager/v2._Manager_ListApplications_Handler\n\t/go/pkg/mod/d7y.io/api/v2@v2.0.110/pkg/apis/manager/v2/manager_grpc.pb.go:368\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/go/pkg/mod/google.golang.org/grpc@v1.63.2/server.go:1369\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/go/pkg/mod/google.golang.org/grpc@v1.63.2/server.go:1780\ngoogle.golang.org/grpc.(*Server).serveStreams.func2.1\n\t/go/pkg/mod/google.golang.org/grpc@v1.63.2/server.go:1019"}
{"level":"debug","ts":"2024-04-25 07:46:56.161","caller":"recovery/interceptors.go:33","msg":"trace","elapsed":0.000590327,"rows":0,"sql":"SELECT * FROM `application` WHERE priority != '' AND `application`.`is_del` = 0"}


schedule info:
{"level":"info","ts":"2024-04-25 07:05:56.257","caller":"service/service_v1.go:576","msg":"announce new host: &scheduler.AnnounceHostRequest{state:impl.MessageState{NoUnkeyedLiterals:pragma.NoUnkeyedLiterals{}, DoNotCompare:pragma.DoNotCompare{}, DoNotCopy:pragma.DoNotCopy{}, atomicMessageInfo:(*impl.MessageInfo)(0xc000834360)}, sizeCache:0, unknownFields:[]uint8(nil), Id:\"bb7a4549944882100f060ee91acf68710aa845a65bac5f103350c54a38e57cb9\", Type:\"normal\", Hostname:\"ops-k8s-testwxnode11.wxxdc\", Ip:\"10.2.55.13\", Port:65000, DownloadPort:65002, Os:\"linux\", Platform:\"alpine\", PlatformFamily:\"alpine\", PlatformVersion:\"3.17.7\", KernelVersion:\"5.4.193-0504193-generic\", Cpu:(*scheduler.CPU)(0xc000c1aaf0), Memory:(*scheduler.Memory)(0xc000897d40), Network:(*scheduler.Network)(0xc000c1ab40), Disk:(*scheduler.Disk)(0xc000c38150), Build:(*scheduler.Build)(0xc000c381c0), SchedulerClusterId:0x1, ObjectStoragePort:0}","hostID":"bb7a4549944882100f060ee91acf68710aa845a65bac5f103350c54a38e57cb9","hostname":"ops-k8s-testwxnode11.wxxdc","ip":"10.2.55.13"}
{"level":"info","ts":"2024-04-25 07:05:56.634","caller":"service/service_v1.go:576","msg":"announce new host: &scheduler.AnnounceHostRequest{state:impl.MessageState{NoUnkeyedLiterals:pragma.NoUnkeyedLiterals{}, DoNotCompare:pragma.DoNotCompare{}, DoNotCopy:pragma.DoNotCopy{}, atomicMessageInfo:(*impl.MessageInfo)(0xc000834360)}, sizeCache:0, unknownFields:[]uint8(nil), Id:\"c5ed19cba33dc1623cf0d02dcec730a6eec8201b19404833b21bed566b4c3121\", Type:\"normal\", Hostname:\"ops-k8s-testwxnode9.wxxdc\", Ip:\"10.2.55.17\", Port:65000, DownloadPort:65002, Os:\"linux\", Platform:\"alpine\", PlatformFamily:\"alpine\", PlatformVersion:\"3.17.7\", KernelVersion:\"5.4.193-0504193-generic\", Cpu:(*scheduler.CPU)(0xc00149c870), Memory:(*scheduler.Memory)(0xc000ebbc20), Network:(*scheduler.Network)(0xc00149c8c0), Disk:(*scheduler.Disk)(0xc0006eafc0), Build:(*scheduler.Build)(0xc0006eb030), SchedulerClusterId:0x1, ObjectStoragePort:0}","hostID":"c5ed19cba33dc1623cf0d02dcec730a6eec8201b19404833b21bed566b4c3121","hostname":"ops-k8s-testwxnode9.wxxdc","ip":"10.2.55.17"}
{"level":"info","ts":"2024-04-25 07:06:06.083","caller":"service/service_v1.go:576","msg":"announce new host: &scheduler.AnnounceHostRequest{state:impl.MessageState{NoUnkeyedLiterals:pragma.NoUnkeyedLiterals{}, DoNotCompare:pragma.DoNotCompare{}, DoNotCopy:pragma.DoNotCopy{}, atomicMessageInfo:(*impl.MessageInfo)(0xc000834360)}, sizeCache:0, unknownFields:[]uint8(nil), Id:\"15d2e80da569e129ca64af0c4a06b614e6ced31153224f557c53c069b1562183\", Type:\"normal\", Hostname:\"ops-k8s-testwxnode6.wxxdc\", Ip:\"10.2.55.37\", Port:65000, DownloadPort:65002, Os:\"linux\", Platform:\"alpine\", PlatformFamily:\"alpine\", PlatformVersion:\"3.17.7\", KernelVersion:\"5.4.193-0504193-generic\", Cpu:(*scheduler.CPU)(0xc0009cc550), Memory:(*scheduler.Memory)(0xc0000dc8a0), Network:(*scheduler.Network)(0xc0009cc5a0), Disk:(*scheduler.Disk)(0xc000698070), Build:(*scheduler.Build)(0xc0006980e0), SchedulerClusterId:0x1, ObjectStoragePort:0}","hostID":"15d2e80da569e129ca64af0c4a06b614e6ced31153224f557c53c069b1562183","hostname":"ops-k8s-testwxnode6.wxxdc","ip":"10.2.55.37"}
{"level":"info","ts":"2024-04-25 07:06:06.181","caller":"service/service_v1.go:576","msg":"announce new host: &scheduler.AnnounceHostRequest{state:impl.MessageState{NoUnkeyedLiterals:pragma.NoUnkeyedLiterals{}, DoNotCompare:pragma.DoNotCompare{}, DoNotCopy:pragma.DoNotCopy{}, atomicMessageInfo:(*impl.MessageInfo)(0xc000834360)}, sizeCache:0, unknownFields:[]uint8(nil), Id:\"535cb92fa0e82e131db899f4f69c10a57165833cf62c03e4d06553ad2f1808da\", Type:\"normal\", Hostname:\"ops-k8s-testwxnode7.wxxdc\", Ip:\"10.2.55.39\", Port:65000, DownloadPort:65002, Os:\"linux\", Platform:\"alpine\", PlatformFamily:\"alpine\", PlatformVersion:\"3.17.7\", KernelVersion:\"5.4.193-0504193-generic\", Cpu:(*scheduler.CPU)(0xc00073f270), Memory:(*scheduler.Memory)(0xc0014a5560), Network:(*scheduler.Network)(0xc00073f2c0), Disk:(*scheduler.Disk)(0xc0006f0770), Build:(*scheduler.Build)(0xc0006f0850), SchedulerClusterId:0x1, ObjectStoragePort:0}","hostID":"535cb92fa0e82e131db899f4f69c10a57165833cf62c03e4d06553ad2f1808da","hostname":"ops-k8s-testwxnode7.wxxdc","ip":"10.2.55.39"}
{"level":"info","ts":"2024-04-25 07:06:17.606","caller":"resource/seed_peer_client.go:149","msg":"addresses have been updated: []dfnet.NetAddr{dfnet.NetAddr{Type:\"tcp\", Addr:\"10.222.87.172:65000\"}}"}

**Comment by mansoncui** [comment]
> manager info: ND state = 'active' AND `scheduler`.`is_del` = 0"} {"level":"debug","ts":"2024-04-25 07:46:36.145","caller":"recovery/interceptors.go:33","msg":"trace","elapsed":0.000319262,"rows":1,"sql":"SELECT * FROM `seed_peer_cluster_scheduler_cluster` WHERE `seed_peer_cluster_scheduler_cluster`.`scheduler_cluster_id` = 1"} {"level":"debug","ts":"2024-04-25 07:46:36.146","caller":"recovery/interceptors.go:33","msg":"trace","elapsed":0.000313925,"rows":1,"sql":"SELECT * FROM `seed_peer` WHERE `seed_peer`.`seed_peer_cluster_id` = 1 AND state = 'active' AND `seed_peer`.`is_del` = 0"} {"level":"debug","ts":"2024-04-25 07:46:36.146","caller":"recovery/interceptors.go:33","msg":"trace","elapsed":0.000829378,"rows":1,"sql":"SELECT * FROM `seed_peer_cluster` WHERE `seed_peer_cluster`.`id` = 1 AND `seed_peer_cluster`.`is_del` = 0"} {"level":"debug","ts":"2024-04-25 07:46:36.146","caller":"recovery/interceptors.go:33","msg":"trace","elapsed":0.002427169,"rows":1,"sql":"SELECT * FROM `scheduler_cluster` WHERE `scheduler_cluster`.`is_del` = 0"} {"level":"debug","ts":"2024-04-25 07:46:36.146","caller":"rpcserver/manager_server_v1.go:579","msg":"list scheduler clusters [cluster-1] with hostInfo map[string]string{"idc":"", "location":""}","hostname":"ops-k8s-testwxnode7.wxxdc","ip":"10.2.55.39"} {"level":"debug","ts":"2024-04-25 07:46:36.146","caller":"rpcserver/manager_server_v1.go:594","msg":"find matching scheduler cluster [cluster-1]","hostname":"ops-k8s-testwxnode7.wxxdc","ip":"10.2.55.39"} {"level":"debug","ts":"2024-04-25 07:46:56.159","caller":"rpcserver/manager_server_v2.go:345","msg":"manager:schedulers:1-dragonfly-scheduler-0.scheduler.dragonfly-system.svc.cluster.local-10.222.87.143 cache hit","hostname":"dragonfly-scheduler-0.scheduler.dragonfly-system.svc.cluster.local","ip":"10.222.87.143"} {"level":"warn","ts":"2024-04-25 07:46:56.160","caller":"rpcserver/manager_server_v2.go:670","msg":"manager:applications cache miss because of cache: key is missing","hostname":"dragonfly-scheduler-0.scheduler.dragonfly-system.svc.cluster.local","ip":"10.222.87.143","stacktrace":"d7y.io/dragonfly/v2/manager/rpcserver.(*managerServerV2).ListApplications\n\t/go/src/d7y.io/dragonfly/v2/manager/rpcserver/manager_server_v2.go:670\nd7y.io/api/v2/pkg/apis/manager/v2._Manager_ListApplications_Handler.func1\n\t/go/pkg/mod/d7y.io/api/v2@v2.0.110/pkg/apis/manager/v2/manager_grpc.pb.go:366\ngithub.com/grpc-ecosystem/go-grpc-middleware/recovery.UnaryServerInterceptor.func1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/recovery/interceptors.go:33\nd7y.io/dragonfly/v2/pkg/rpc/manager/server.New.ChainUnaryServer.func5.1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:48\nd7y.io/dragonfly/v2/pkg/rpc/manager/server.New.UnaryServerInterceptor.func3\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/validator/validator.go:47\nd7y.io/dragonfly/v2/pkg/rpc/manager/server.New.ChainUnaryServer.func5.1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:48\ngithub.com/grpc-ecosystem/go-grpc-middleware/logging/zap.UnaryServerInterceptor.func1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/logging/zap/server_interceptors.go:31\nd7y.io/dragonfly/v2/pkg/rpc/manager/server.New.ChainUnaryServer.func5.1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:48\ngithub.com/grpc-ecosystem/go-grpc-prometheus.init.(*ServerMetrics).UnaryServerInterceptor.func3\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/server_metrics.go:107\nd7y.io/dragonfly/v2/pkg/rpc/manager/server.New.ChainUnaryServer.func5.1\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:48\nd7y.io/dragonfly/v2/pkg/rpc/manager/server.New.UnaryServerInterceptor.func2\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/ratelimit/ratelimit.go:24\nd7y.io/dragonfly/v2/pkg/rpc/manager/server.New.ChainUnaryServer.func5\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:53\nd7y.io/api/v2/pkg/apis/manager/v2._Manager_ListApplications_Handler\n\t/go/pkg/mod/d7y.io/api/v2@v2.0.110/pkg/apis/manager/v2/manager_grpc.pb.go:368\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/go/pkg/mod/google.golang.org/grpc@v1.63.2/server.go:1369\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/go/pkg/mod/google.golang.org/grpc@v1.63.2/server.go:1780\ngoogle.golang.org/grpc.(*Server).serveStreams.func2.1\n\t/go/pkg/mod/google.golang.org/grpc@v1.63.2/server.go:1019"} {"level":"debug","ts":"2024-04-25 07:46:56.161","caller":"recovery/interceptors.go:33","msg":"trace","elapsed":0.000590327,"rows":0,"sql":"SELECT * FROM `application` WHERE priority != '' AND `application`.`is_del` = 0"}
> 
> schedule info: {"level":"info","ts":"2024-04-25 07:05:56.257","caller":"service/service_v1.go:576","msg":"announce new host: &scheduler.AnnounceHostRequest{state:impl.MessageState{NoUnkeyedLiterals:pragma.NoUnkeyedLiterals{}, DoNotCompare:pragma.DoNotCompare{}, DoNotCopy:pragma.DoNotCopy{}, atomicMessageInfo:(*impl.MessageInfo)(0xc000834360)}, sizeCache:0, unknownFields:[]uint8(nil), Id:"bb7a4549944882100f060ee91acf68710aa845a65bac5f103350c54a38e57cb9", Type:"normal", Hostname:"ops-k8s-testwxnode11.wxxdc", Ip:"10.2.55.13", Port:65000, DownloadPort:65002, Os:"linux", Platform:"alpine", PlatformFamily:"alpine", PlatformVersion:"3.17.7", KernelVersion:"5.4.193-0504193-generic", Cpu:(*scheduler.CPU)(0xc000c1aaf0), Memory:(*scheduler.Memory)(0xc000897d40), Network:(*scheduler.Network)(0xc000c1ab40), Disk:(*scheduler.Disk)(0xc000c38150), Build:(*scheduler.Build)(0xc000c381c0), SchedulerClusterId:0x1, ObjectStoragePort:0}","hostID":"bb7a4549944882100f060ee91acf68710aa845a65bac5f103350c54a38e57cb9","hostname":"ops-k8s-testwxnode11.wxxdc","ip":"10.2.55.13"} {"level":"info","ts":"2024-04-25 07:05:56.634","caller":"service/service_v1.go:576","msg":"announce new host: &scheduler.AnnounceHostRequest{state:impl.MessageState{NoUnkeyedLiterals:pragma.NoUnkeyedLiterals{}, DoNotCompare:pragma.DoNotCompare{}, DoNotCopy:pragma.DoNotCopy{}, atomicMessageInfo:(*impl.MessageInfo)(0xc000834360)}, sizeCache:0, unknownFields:[]uint8(nil), Id:"c5ed19cba33dc1623cf0d02dcec730a6eec8201b19404833b21bed566b4c3121", Type:"normal", Hostname:"ops-k8s-testwxnode9.wxxdc", Ip:"10.2.55.17", Port:65000, DownloadPort:65002, Os:"linux", Platform:"alpine", PlatformFamily:"alpine", PlatformVersion:"3.17.7", KernelVersion:"5.4.193-0504193-generic", Cpu:(*scheduler.CPU)(0xc00149c870), Memory:(*scheduler.Memory)(0xc000ebbc20), Network:(*scheduler.Network)(0xc00149c8c0), Disk:(*scheduler.Disk)(0xc0006eafc0), Build:(*scheduler.Build)(0xc0006eb030), SchedulerClusterId:0x1, ObjectStoragePort:0}","hostID":"c5ed19cba33dc1623cf0d02dcec730a6eec8201b19404833b21bed566b4c3121","hostname":"ops-k8s-testwxnode9.wxxdc","ip":"10.2.55.17"} {"level":"info","ts":"2024-04-25 07:06:06.083","caller":"service/service_v1.go:576","msg":"announce new host: &scheduler.AnnounceHostRequest{state:impl.MessageState{NoUnkeyedLiterals:pragma.NoUnkeyedLiterals{}, DoNotCompare:pragma.DoNotCompare{}, DoNotCopy:pragma.DoNotCopy{}, atomicMessageInfo:(*impl.MessageInfo)(0xc000834360)}, sizeCache:0, unknownFields:[]uint8(nil), Id:"15d2e80da569e129ca64af0c4a06b614e6ced31153224f557c53c069b1562183", Type:"normal", Hostname:"ops-k8s-testwxnode6.wxxdc", Ip:"10.2.55.37", Port:65000, DownloadPort:65002, Os:"linux", Platform:"alpine", PlatformFamily:"alpine", PlatformVersion:"3.17.7", KernelVersion:"5.4.193-0504193-generic", Cpu:(*scheduler.CPU)(0xc0009cc550), Memory:(*scheduler.Memory)(0xc0000dc8a0), Network:(*scheduler.Network)(0xc0009cc5a0), Disk:(*scheduler.Disk)(0xc000698070), Build:(*scheduler.Build)(0xc0006980e0), SchedulerClusterId:0x1, ObjectStoragePort:0}","hostID":"15d2e80da569e129ca64af0c4a06b614e6ced31153224f557c53c069b1562183","hostname":"ops-k8s-testwxnode6.wxxdc","ip":"10.2.55.37"} {"level":"info","ts":"2024-04-25 07:06:06.181","caller":"service/service_v1.go:576","msg":"announce new host: &scheduler.AnnounceHostRequest{state:impl.MessageState{NoUnkeyedLiterals:pragma.NoUnkeyedLiterals{}, DoNotCompare:pragma.DoNotCompare{}, DoNotCopy:pragma.DoNotCopy{}, atomicMessageInfo:(*impl.MessageInfo)(0xc000834360)}, sizeCache:0, unknownFields:[]uint8(nil), Id:"535cb92fa0e82e131db899f4f69c10a57165833cf62c03e4d06553ad2f1808da", Type:"normal", Hostname:"ops-k8s-testwxnode7.wxxdc", Ip:"10.2.55.39", Port:65000, DownloadPort:65002, Os:"linux", Platform:"alpine", PlatformFamily:"alpine", PlatformVersion:"3.17.7", KernelVersion:"5.4.193-0504193-generic", Cpu:(*scheduler.CPU)(0xc00073f270), Memory:(*scheduler.Memory)(0xc0014a5560), Network:(*scheduler.Network)(0xc00073f2c0), Disk:(*scheduler.Disk)(0xc0006f0770), Build:(*scheduler.Build)(0xc0006f0850), SchedulerClusterId:0x1, ObjectStoragePort:0}","hostID":"535cb92fa0e82e131db899f4f69c10a57165833cf62c03e4d06553ad2f1808da","hostname":"ops-k8s-testwxnode7.wxxdc","ip":"10.2.55.39"} {"level":"info","ts":"2024-04-25 07:06:17.606","caller":"resource/seed_peer_client.go:149","msg":"addresses have been updated: []dfnet.NetAddr{dfnet.NetAddr{Type:"tcp", Addr:"10.222.87.172:65000"}}"}

@gaius-qi

**Comment by gaius-qi** [comment]
@mansoncui  Please provide manager log files(/var/log/dragonfly/manager) and scheduler log files(/var/log/dragonfly/scheduler).

**Comment by mansoncui** [comment]
> @mansoncui Please provide manager log files(/var/log/dragonfly/manager) and scheduler log files(/var/log/dragonfly/scheduler).

[scheduler-core.log](https://github.com/dragonflyoss/Dragonfly2/files/15107317/scheduler-core.log)
[manager-core.log](https://github.com/dragonflyoss/Dragonfly2/files/15107322/manager-core.log)
@gaius-qi

**Comment by gaius-qi** [comment]
I can not find the preheat information in the manager logs. Please confirm that the manager preheating port `8080` in harbor is configured correctly.

**Comment by mansoncui** [comment]
> I can't find the warm-up information in the manager logs. Make sure that the port manager preheats the port correctly.`8080`

<img width="586" alt="image" src="https://github.com/dragonflyoss/Dragonfly2/assets/29750171/f845188f-9b25-48b0-a20b-b16fc3c2c5fc">

<img width="1402" alt="image" src="https://github.com/dragonflyoss/Dragonfly2/assets/29750171/4f964035-aa8d-4b2d-9e2a-2b14bfad117f">

I checked that the configuration is normal and no abnormalities were found. I rolled back to version 1.1.26 and the preheating cannot be triggered. Same configuration 
configure :
scheduler:
  replicas: 1
  metrics:
    enable: true
  config:
    verbose: true
    pprofPort: 18066

seedPeer:
  replicas: 1
  metrics:
    enable: true
  config:
    verbose: true
    pprofPort: 18066
    download:
      prefetch: true

dfdaemon:
  hostNetwork: true
  metrics:
    enable: true
  config:
    verbose: true
    pprofPort: 18066
    download:
      prefetch: true
    proxy:
      defaultFilter: 'Expires&Signature&ns'
      security:
        insecure: true
      tcpListen:
        listen: 0.0.0.0
        port: 65001
      registryMirror:
        dynamic: true
        url: https://harbor.test.xxx.com
      proxies:
        - regx: blobs/sha256.*

manager:
  replicas: 1
  metrics:
    enable: true
  config:
    verbose: true
    pprofPort: 18066
    job:
      syncPeers:
        interval: 13h
        timeout: 10m
      preheat:
        registryTimeout: 1m
        tls:
          # caCert is the CA certificate for preheat tls handshake, it can be path or PEM format string.
          caCert: |           
jaeger:
  enable: true

**Comment by mansoncui** [comment]
@gaius-qi

**Comment by gaius-qi** [comment]
> @gaius-qi 

I can't find preheat info in your manager logs. Please check harbor logs.

**Comment by mansoncui** [comment]
ok
