### ISSUE TITLE
dfget 从对象存储下载文件没走p2p

### ISSUE THREAD

**Issue by lihuawei321** [dragonflyoss/Dragonfly2#3278]
1. 在dfdaemon的Pod1中第一次去dfget
![image](https://github.com/dragonflyoss/Dragonfly2/assets/31987918/6ab10857-a24c-44dc-8593-b31282d5e76f)

scheduler里可以看到日志
![image](https://github.com/dragonflyoss/Dragonfly2/assets/31987918/81e491d0-12bf-496a-8f07-b8c04f85a725)

2. 在dfdaemon的pod2 中去dfget，速度就快了，且scheduler仍可以看到日志

![image](https://github.com/dragonflyoss/Dragonfly2/assets/31987918/3d902119-aa39-4d79-bdd9-799801283faf)
![image](https://github.com/dragonflyoss/Dragonfly2/assets/31987918/e66a8138-0610-46ea-85c2-c5f1093fd142)

3. 但是在自己的测试pod中安装dfget命令去dfget下载，速度慢且scheduler中看不到有日志产生，看起来没走p2p。
![image](https://github.com/dragonflyoss/Dragonfly2/assets/31987918/7ca0e998-cbd6-45ef-a5ff-e9b78afc757a)

**Comment by gaius-qi** [comment]
Please use English.
