### ISSUE TITLE
The dfget downloads from object storage in my pod did not use P2P

### ISSUE THREAD

**Issue by lihuawei321** [dragonflyoss/Dragonfly2#3279]
1. Use dfget in dfdaemon Pod1 for the first time
![image](https://github.com/dragonflyoss/Dragonfly2/assets/31987918/6ab10857-a24c-44dc-8593-b31282d5e76f)

You can see the logs in the scheduler
![image](https://github.com/dragonflyoss/Dragonfly2/assets/31987918/81e491d0-12bf-496a-8f07-b8c04f85a725)

2. Using dfget in dfdaemon's pod2 is faster, and the scheduler logs are still visible
![image](https://github.com/dragonflyoss/Dragonfly2/assets/31987918/3d902119-aa39-4d79-bdd9-799801283faf)
![image](https://github.com/dragonflyoss/Dragonfly2/assets/31987918/e66a8138-0610-46ea-85c2-c5f1093fd142)

3. However, when installing the dfget command in my own test pod to download, the speed is slow and no logs are generated in the scheduler, which indicates that P2P is not being used。
![image](https://github.com/dragonflyoss/Dragonfly2/assets/31987918/7ca0e998-cbd6-45ef-a5ff-e9b78afc757a)

**Comment by gaius-qi** [comment]
Please provide `test pod` daemon log.

**Comment by lihuawei321** [comment]
> Please provide `test pod` daemon log.
It seems like the scheduler address is unreachable. Where should this address be configured? I installed the dfget RPM package directly in the pod using yum install.

![image](https://github.com/dragonflyoss/Dragonfly2/assets/31987918/3c0392ae-d887-4d7f-8a8d-587e282e37ff)

**Comment by lihuawei321** [comment]
I found the issue. Although dfget is installed in my pod, the dfget configuration hasn't been changed.
