### ISSUE TITLE
The manager cannot start and there are no logs

### ISSUE THREAD

**Issue by yetone** [dragonflyoss/Dragonfly2#3377]
### Bug report:

The manager cannot start, and no logs are visible. I copied a pod to run the manager manually in the container, but still couldn't see any logs.

![image](https://github.com/user-attachments/assets/6864bba1-fa4f-4c3a-bdb8-fe16c40bfe22)
<img width="741" alt="image" src="https://github.com/user-attachments/assets/dbcf5403-4d14-4a8b-919e-dd5aec32a162">
<img width="478" alt="image" src="https://github.com/user-attachments/assets/33c91b2b-add2-4f55-b44b-a1b3a8df46a6">

### Expected behavior:

Hope the manager can start normally.

### Environment:

- Dragonfly version: v2.1.29
- OS:
- Kernel (e.g. `uname -a`):
- Others:

**Comment by gaius-qi** [comment]
Edit `console: true` in manager config.

![image](https://github.com/user-attachments/assets/17907a73-c5af-4d58-95b1-5dfc1cdeafe6)

**Comment by yetone** [comment]
‌‌‌‌Thank you for the help, now the logs can be displayed. Is redis cluster mode not supported? But looking at this [PR](https://github.com/dragonflyoss/Dragonfly2/pull/1667), it has been supporting redis cluster mode since two years ago.

<img width="2119" alt="image" src="https://github.com/user-attachments/assets/cd993299-f664-42a9-a9af-1616af8c3d30">
