### ISSUE TITLE
Manager front-end features

### ISSUE THREAD

**Issue by gaius-qi** [dragonflyoss/Dragonfly2#339]
### Feature request:
- Manager front-end features.

### Use case:
N/A

### UI Example:
N/A

**Comment by gaius-qi** [comment]
Feature design: https://yuque.antfin.com/docs/share/bbff6687-36cd-455b-9ecc-9b4042e49d23?#

**Comment by yxxhero** [comment]
> Feature design: https://yuque.antfin.com/docs/share/bbff6687-36cd-455b-9ecc-9b4042e49d23?#

Can I read this design?

**Comment by lengrongfu** [comment]
Can the design be shared?
