### ISSUE TITLE
dfget卡顿

### ISSUE THREAD

**Issue by alohaHZ** [dragonflyoss/Dragonfly2#3405]
### Bug report:

docker pull命令拉取镜像后在某层的layer被卡住。

### Environment:

- Dragonfly version:  v2.1.45
- OS:  Suse linux  version 12

(1)经查日志，发现是下载失败，"peer/piece manager.go:232", "msg":"put piece to storage failed, piece num: 17, wrote: 3465496, error: read tcp 172.17.0.7:38810->122.220.203.28:65002:read:connection reset by peer"
(2)而后没有发现 client/daemon/peer/peertask conductor.go 的函数 downloadPiece(1117行 pt.PieceManager.DownloadPiece)没有被调用。
(3)在同样的环境下使用最新版本v2.1.52产生上面(1)的报错，但是后面(2)中的函数被重新调用，因而没有被卡住。

**Comment by gaius-qi** [comment]
@alohaHZ Please use the latest version. Thanks!
