### ISSUE TITLE
Typo in dashboard

### ISSUE THREAD

**Issue by 4everming** [dragonflyoss/Dragonfly2#3538]
### Bug report:

Misspell the word "schedulers" in the dashboard. 

### Expected behavior:
Use "schedulers" instead of "schdulers"

### How to reproduce it:
Click the "Cluster" menu on the left, then click an existing cluster's arrow button to go to the cluster detail page.

<img width="803" alt="image" src="https://github.com/user-attachments/assets/d38ef6de-e3e7-4113-ac9e-a4e891f3ab20">

### Environment:

- Dragonfly version: latest main branch.

**Comment by gaius-qi** [comment]
@Liam-Zhao

**Comment by Liam-Zhao** [comment]
https://github.com/dragonflyoss/console/pull/398 PR fixed
