### ISSUE TITLE
Infinite recursion in MkDirAll

### ISSUE THREAD

**Issue by jim3ma** [dragonflyoss/Dragonfly2#359]
### Bug report:

https://github.com/dragonflyoss/Dragonfly2/blob/main/client/config/dfget.go#L197

When `dir == "/"`, `MkDirAll` does infinite recursion.

### Environment:
- Dragonfly version:
- OS:
- Kernel (e.g. `uname -a`):
- Others:

**Comment by lengrongfu** [comment]
/ sign

**Comment by lengrongfu** [comment]
Can this issue be assigned to me? I hope to be able to participate in the project. @jim3ma
