### ISSUE TITLE
GC remove current running image related task data

### ISSUE THREAD

**Issue by ppancake** [dragonflyoss/Dragonfly2#3633]
### Bug report:

GC remove current running image associated task data

### Expected behavior:

When triggering GC, retain tasks data associated with running images.

### How to reproduce it:

Set up a local cluster using kind and configured the /var/lib/dragonfly data directory in dfget.yaml to be 50M in size. I started a custom BusyBox pod, and observed task data in the directory. Then, I pulled multiple images, causing the directory size to exceed 50M, which triggered GC. After the GC, I found that the /var/lib/dragonfly directory was emptied. Looking at the TryGC code block, the task.Done is cleaned up. The data for the BusyBox was marked as done after the pull was completed. I hope that tasks for images that are still running are not cleaned up.

### Environment:

- Dragonfly version: v2.1.0
- OS: 22.04.1-Ubuntu
- Kernel (e.g. `uname -a`):  Linux kind-worker 6.8.0-47-generic 47~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Oct  2 16:16:55 UTC 2 x86_64 GNU/Linux
- Others:

**Comment by gaius-qi** [comment]
@ppancake Please use English, thanks.

**Comment by ppancake** [comment]
thanks, i will try it later.
