### ISSUE TITLE
dragonfly manager connection leak

### ISSUE THREAD

**Issue by daijiezou** [dragonflyoss/Dragonfly2#3635]
### Bug report:
dragonfly manager number of links continues to rise, with no downward trend.I suspect there's been a connection leak

### Environment:

- Dragonfly version:2.1.30
- OS:
- Kernel (e.g. `uname -a`):
- Others:

**Comment by gaius-qi** [comment]
@daijiezou Has the number of peer nodes increased?

**Comment by daijiezou** [comment]
<img width="1836" alt="image" src="https://github.com/user-attachments/assets/51d26915-9d2d-4e32-82bc-712caaf5a605">


> @daijiezou Has the number of peer nodes increased?

Recently we went live with a new cluster, adding one peer and two seedpeers

**Comment by daijiezou** [comment]
After I turned off the preheat image, this upward trend stopped, but the number of connections did not start to fall.
<img width="1860" alt="image" src="https://github.com/user-attachments/assets/4192c384-a31f-4ff6-be1f-2c902fbb069b">

**Comment by daijiezou** [comment]
![企业微信截图_6c643821-38e7-4b83-af52-d832ee30b8ed](https://github.com/user-attachments/assets/4cc4c6b9-2a87-4b9e-a66f-a265088cca77)
I looked at the connections and found that they were almost always between docker-registry(port 32402) and registry-authServer(port 32612).

**Comment by gaius-qi** [comment]
Need to control the connection pool in https://github.com/dragonflyoss/Dragonfly2/blob/main/manager/job/preheat.go#L399.
