### ISSUE TITLE
 error decoding response body  这个报错应该如何排查

### ISSUE THREAD

**Issue by WaterAndBread** [dragonflyoss/Dragonfly2#3663]
### Bug report:

通过api job 接口 create preheat  ,single_peer ,发生如下报错，应该如何解决，可能的原因是什么？
![image](https://github.com/user-attachments/assets/5ebe9a8f-4b50-4e2a-bc89-dd2915601d9d)
![image](https://github.com/user-attachments/assets/365e5e14-2ca9-4829-a542-92380b996dbe)
[df.log](https://github.com/user-attachments/files/17899605/df.log)

### Environment:

- Dragonfly version: v2.1.63
- OS: linux
- Kernel (e.g. `uname -a`): 5.10.0-136.12.0.88.ctl3.x86_64
- Others:

**Comment by gaius-qi** [comment]
@WaterAndBread Please use English, thanks.

**Comment by MouseSun846** [comment]
I also encountered the same problem, how to solve it?

**Comment by gaius-qi** [comment]
@MouseSun846 https://github.com/dragonflyoss/Dragonfly2/issues/3676
