### ISSUE TITLE
x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by gnr1227** [dragonflyoss/Dragonfly2#3678]
### Bug report:

Getting x509 certificate issue, when downloading image from harbor registry.

### Pull command: 
singularity pull oras://private-harbor-registry.com/image:tag

### Error:
------
INFO[0000] trying next host                              error="failed to do request: Head \"https://private-harbor-registry.com/image:tag": x509: certificate signed by unknown authority" host=private-harbor-registry.com
FATAL:   While pulling image from oci registry: error fetching image to cache: failed to get checksum for oras://private-harbor-registry.com/image:tag: while resolving reference: failed to do request: Head "https://private-harbor-registry.com/image:tag": x509: certificate signed by unknown authority

2024-12-02T08:16:17.381864852-08:00  INFO handler:https_handler: dragonfly-client/src/proxy/mod.rs:420: handle HTTPS request: Request { method: CONNECT, uri: private-harbor-registry.com:443, version: HTTP/1.1, headers: {"host": "private-harbor-registry.com:443", "user-agent": "Go-http-client/1.1"}, body: Body(Empty) } uri="private-harbor-registry.com:443" method="CONNECT"
2024-12-02T08:16:17.381948271-08:00  INFO upgraded_tunnel: dragonfly-client/src/proxy/mod.rs:478: generate simple self-signed certificate
2024-12-02T08:16:17.391504962-08:00 ERROR dragonfly-client/src/proxy/mod.rs:440: server io error: received fatal alert: BadCertificate

### Environment:

- Dragonfly version: 2.1.64
- OS: SLES15

Can we have an option "isecureSkipVerify" from client and seed-client as well. Currently I can see this option for only manager during preheat.

**Comment by gaius-qi** [comment]
![image](https://github.com/user-attachments/assets/dcad26e0-ac20-49bf-bb9f-1cf7c3ad6653)
This is the configuration of containerd. You can find whether singularity has this configuration.

**Comment by gnr1227** [comment]
@gaius-qi  Singularity has multiple ways to bypass TLS.

We can enable in ~/.singularity/remote.yaml
OrasRegistries:
  - uri: http://myregistry.local
    insecure: true

**We have even tried by adding the cert file. still getting same error**

INFO[0000] trying next host error="failed to do request: Head "https://private-harbor-registry.com/image:tag": x509: certificate signed by unknown authority" host=private-harbor-registry.com
FATAL: While pulling image from oci registry: error fetching image to cache: failed to get checksum for oras://private-harbor-registry.com/image:tag: while resolving reference: failed to do request: Head "https://private-harbor-registry.com/image:tag": x509: certificate signed by unknown authority

**dfdaemon.yaml**

host:
  idc: ""
  location: ""
server:
  cacheDir: /tmp/cache/dragonfly/dfdaemon/
  pluginDir: /tmp/cache/dragonfly/plugins/dfdaemon/
download:
  concurrentPieceCount: 16
  pieceTimeout: 30s
  rateLimit: 50GiB
  server:
    socketPath: /var/run/dragonfly/dfdaemon.sock
upload:
  rateLimit: 50GiB
  server:
    port: 4000
manager:
  addr: http://dragonfly-manager.com
scheduler:
  announceInterval: 1m
  maxScheduleCount: 5
  scheduleTimeout: 30s
seedPeer:
  clusterID: 1
  enable: false
  keepaliveInterval: 15s
  type: super
dynconfig:
  refreshInterval: 1m
storage:
  dir: /tmp/cache/dragonfly/
  keep: false
  readBufferSize: 131072
  writeBufferSize: 131072
gc:
  interval: 900s
  policy:
    distHighThresholdPercent: 80
    distLowThresholdPercent: 60
    taskTTL: 168h
proxy:
  disableBackToSource: false
  prefetch: false
  readBufferSize: 32768
  registryMirror:
    addr: https://harbor-registry.com
    cert: "/etc/dragonfly/ca/cert.crt"
  rules:
  - regex: blobs/sha256.*
    useTLS: false
  server:
    port: 4001
health:
  server:
    port: 4003
metrics:
  server:
    port: 4002
stats:
  server:
    port: 4004

**Command is using to pull the image:**
setenv NO_PROXY ''; setenv no_proxy '';  setenv HTTPS_PROXY 127.0.0.1:4001; singularity pull -F --disable-cache oras://registry:image

Did I miss something in the config file?

**Comment by gnr1227** [comment]
Here am trying to proxy the download request based on http proxy. I am not sure if we need to think of singularity configuration.

**Comment by gaius-qi** [comment]
@gnr1227 Please add certs in client config, refer to https://d7y.io/docs/next/operations/integrations/container-runtime/containerd/#harbor-create-dragonfly-cluster-based-on-helm-charts.
