### ISSUE TITLE
[UI] Loss of query parameters during paging queries

### ISSUE THREAD

**Issue by chlins** [dragonflyoss/Dragonfly2#3681]
### Bug report:

Search the cluster from UI:

First time query cluster by `test` is normal: `https://example.dragonfly.com/clusters?search=test`

Second time query cluster lost the `search` keyword: `https://example.dragonfly.com/clusters?page=2`

### Expected behavior:

Filter the clusters by query keywords.

### Environment:

- Dragonfly version: latest
- OS: Linux
- Kernel (e.g. `uname -a`):
- Others:

**Comment by gaius-qi** [comment]
Fixed https://github.com/dragonflyoss/console/pull/415.
