### ISSUE TITLE
Manager user logic design

### ISSUE THREAD

**Issue by yxxhero** [dragonflyoss/Dragonfly2#376]
### Feature request:
Manager user logic design.

### User Table:
|字段|键类型|为空|索引|默认|备注|
|----|----|----|----|----|----|
|id|int|no|PRI|AUTO_INCREMENT|用户id|
|email|varchar|no|UNI||用户邮箱|
|name|varchar|no|UNI||用户昵称|
|encryptedPassword|varchar|no|||加密密码|
|avatar|varchar|no|||头像地址|
|phone|varchar|yes|UNI||手机号|
|passwordSalt|varchar|no|||密码salt|
|privateToken|varchar|no|||Token|
|createdAt|timestamp|no||当前时间|创建时间|
|updatedAt|timestamp|no||当前时间|更新时间|
|deletedAt|timestamp|no||当前时间|删除时间|
|state|varchar|on||enable|账户状态||
|bio|varchar|on||||
|location|varchar|on||||
### User token:
jwt: https://github.com/golang-jwt/jwt

### RBAC:
rbac: https://github.com/casbin/casbin

**Comment by yxxhero** [comment]
@gaius-qi

**Comment by lengrongfu** [comment]
@yxxhero @gaius-qi I can do this.

**Comment by gaius-qi** [comment]
- Need to add:
  - `email`
  - `encrypted_password `
  - `password_salt`
  - `private_token`
  - `deleted_at`
  - `state`
  - `bio`
  - `location`
- Change `avatarUrl` to `avatar`.
- Remove `enable`.
- `name` adds a unique index.

**Comment by yxxhero** [comment]
https://github.com/grafana/grafana/tree/main/pkg/services/accesscontrol

**Comment by yxxhero** [comment]
1.role
* admin: project admin.
* writer: read and writer any configuration.
* viewer: only read configuration.
