### ISSUE TITLE
Add editable containerd pull registry config  when deploy dragonfly2

### ISSUE THREAD

**Issue by Louhwz** [dragonflyoss/Dragonfly2#394]
### Feature request:
Now when deploying deagonfly2 in containerd environment, there are two steps. 
First, use helm or something similar to deploy dragonfly2. 
Second, edit hosts containerd config which default is "/etc/containerd/config.toml". 
Step 2 is not non-automated and when there are 1000 nodes in cluster. You need to manually edit the config file which is stupid. And also when you want to change the registry or change the 65001 port, you need to edit again in all 1000 nodes.

### How to improve
I want to add a configmap which represents some host config like which registry you want dragonfly2 to proxy and which port is dragonfly daemon running. Then using a light daemon set to watch the change about the configmap. When the configmap is changed, daemonset will change the config in node.

**Comment by jim3ma** [comment]
A longtime light daemon set is not a good idea. The BroadcastJob from OpenKruise maybe useful. https://openkruise.io/en-us/docs/broadcastjob.html#broadcastjob
