### ISSUE TITLE
Report peer to scheduler failing

### ISSUE THREAD

**Issue by ish-xyz** [dragonflyoss/Dragonfly2#657]
### Bug report:
I'm running dragonfly v2.0.0 in "headless" mode (only scheduler, cdn and dfdaemons). Everything works, but I keep seeing these errors on the peers console.

```
2021-09-16T14:05:13.967Z        ERROR   peer/peertask_stream_callback.go:111    step 3: report successful peer result, error: rpc error: code = Canceled desc = context canceled        {"peer": "10.4.14.44-9-be7bbab9-d903-4c23-81d8-01bc17bc1d24", "task": "3213d96fde2b46057f62be9ad3132513eaaf1633660b6e2650f7e1bb15d66a9b", "component": "streamPeerTask"}
d7y.io/dragonfly/v2/client/daemon/peer.(*streamPeerTaskCallback).Done
        /go/src/d7y.io/dragonfly/v2/client/daemon/peer/peertask_stream_callback.go:111
d7y.io/dragonfly/v2/client/daemon/peer.(*streamPeerTask).finish.func1
        /go/src/d7y.io/dragonfly/v2/client/daemon/peer/peertask_stream.go:382
sync.(*Once).doSlow
        /usr/local/go/src/sync/once.go:68
sync.(*Once).Do
        /usr/local/go/src/sync/once.go:59
d7y.io/dragonfly/v2/client/daemon/peer.(*streamPeerTask).finish
        /go/src/d7y.io/dragonfly/v2/client/daemon/peer/peertask_stream.go:374
d7y.io/dragonfly/v2/client/daemon/peer.(*streamPeerTask).SetContentLength
        /go/src/d7y.io/dragonfly/v2/client/daemon/peer/peertask_stream.go:417
d7y.io/dragonfly/v2/client/daemon/peer.(*pieceManager).DownloadSource
        /go/src/d7y.io/dragonfly/v2/client/daemon/peer/piece_manager.go:398
d7y.io/dragonfly/v2/client/daemon/peer.(*streamPeerTask).backSource
        /go/src/d7y.io/dragonfly/v2/client/daemon/peer/peertask_stream.go:458
d7y.io/dragonfly/v2/client/daemon/peer.(*peerTask).backSource
        /go/src/d7y.io/dragonfly/v2/client/daemon/peer/peertask_base.go:189
d7y.io/dragonfly/v2/client/daemon/peer.(*peerTask).waitFirstPeerPacket
        /go/src/d7y.io/dragonfly/v2/client/daemon/peer/peertask_base.go:518
d7y.io/dragonfly/v2/client/daemon/peer.(*peerTask).pullPiecesFromPeers
        /go/src/d7y.io/dragonfly/v2/client/daemon/peer/peertask_base.go:376
 ```
 There's connectivity between the peers and scheduler, yet they fail to report to the scheduler.

### Expected behavior:

No errors regarding the report phase.

### How to reproduce it:
I'm running dragonfly v2.0.0 on Kubernetes.

* The scheduler has 1 replica and it runs as StatefulSet. 
* The cdn has 1 replica and it runs as StatefulSet.
* The dfdaemons run with `hostnetwork: true` and DNSPolicy: ClusterFirstWithHostNetwork.
* I've ensured there's connectivity between every component.
* The configurations for IPs advertisement are correct and configured at runtime using downward API and bash commands.

### Environment:
- Dragonfly version: v2.0.0
- OS: Linux (Flatcar)
- Kernel (e.g. `uname -a`): Can't disclose the version, flatcar with k8s.

Other: although I flagged this as bug, it could be a misconfiguration.

**Comment by jim3ma** [comment]
When a peer task done, the context is cancelled, but the context is used to report peer task status.
We have found it already, next version will fix it.

**Comment by ish-xyz** [comment]
Thanks @jim3ma. Will wait for it.
