### ISSUE TITLE
Prometheus metrics scheduler and CDN

### ISSUE THREAD

**Issue by ish-xyz** [dragonflyoss/Dragonfly2#658]
### Feature request:
Have /metrics endpoint for scheduler, CDN and dfdaemon.

### Use case:

Some companies might want to run Dragonfly v2.0.0 in headless mode, meaning without having to install the manager, but still want to have metrics regarding the scheduler, CDN and dfdaemon.

**Comment by gaius-qi** [comment]
I will complete this feature in [v2.0.1](https://github.com/dragonflyoss/Dragonfly2/milestone/5)

**Comment by ish-xyz** [comment]
@gaius-qi Thank you very much.
