### ISSUE TITLE
Can we have a community slack channel?

### ISSUE THREAD

**Issue by ish-xyz** [dragonflyoss/Dragonfly2#664]
To build a stronger community around this product, and allow users to help each others, it'd be nice to have a dedicated official Slack channel.

Can we create one please?

**Comment by gaius-qi** [comment]
it is already planned. Thx 😄😄😄

**Comment by gaius-qi** [comment]
Slack Channel: [#dragonfly](https://cloud-native.slack.com/messages/dragonfly/) on [CNCF Slack](https://slack.cncf.io/)
