### ISSUE TITLE
Can we have a production configuration guide?

### ISSUE THREAD

**Issue by ish-xyz** [dragonflyoss/Dragonfly2#675]
I'd like to have a production config guide, that can help the users understand how to configure the different components. 

For example, how many workers to use in the scheduler configuration? 
Should we enable backSource on the dfdaemons? 
The CDN configurations? 
How many scheduler should we use? 
How much docker images pulls is a given infrastructure able to handle? 
And so on.

A few deep dive, explaining how do you intend the tool to be used and how do you use it, would be nice to have.

**Comment by gaius-qi** [comment]
Please refer to https://d7y.netlify.app
