### ISSUE TITLE
manager: Error: empty cache redis config is not specified 

### ISSUE THREAD

**Issue by hansdcr** [dragonflyoss/Dragonfly2#691]
### Bug report:
manager start error:
version: v0.5.0 /v2.0.0/v2.0.1

Error: empty cache redis config is not specified
Error: empty cache redis config is not specified
Error: empty cache redis config is not specified
Error: empty cache redis config is not specified
Error: empty cache redis config is not specified
Error: empty cache redis config is not specified
Error: empty cache redis config is not specified
Error: empty cache redis config is not specified
Error: empty cache redis config is not specified
Error: empty cache redis config is not specified

how to fix it

**Comment by gaius-qi** [comment]
It is recommended to use helm for deployment .If you must use docker deployment, you need to mount the manager configuration to /etc/dragonfly/manager.yaml
