### ISSUE TITLE
Update the dfdaemon with additional scheduler info without having to restart it

### ISSUE THREAD

**Issue by mohafarooq** [dragonflyoss/Dragonfly2#702]
### Feature request:
In a large environment with many dfdaemon it is important to auto-scale the scheduler based on demand. Currently, if we add more schedulers, the dfdaemon needs to be restarted to take it into effect. Restarting the dfdaemon could momentarily fail the pull requests on that specific client. Can we update the dfdaemon with additional scheduler info without having to restart it? 

### Use case:
Auto-scaling of schedulers based on demand

**Comment by gaius-qi** [comment]
This feature will be added in the future.

**Comment by mohafarooq** [comment]
#812 closed it
