### ISSUE TITLE
When I do 2000 simultaneous pulls at the same time for a 4GB image, the pull fails and I get below error in core.log

### ISSUE THREAD

**Issue by mohafarooq** [dragonflyoss/Dragonfly2#715]
### Bug report:
When I do 2000 simultaneous pulls at the same time for a 4GB image, the pull fails and I get below error in core.log. (I used <ip> and <another_ip> as masks. 

{"level":"error","ts":"2021-10-11 02:44:22.014","caller":"peer/peertask_base.go:809","msg":"send piece result error: <another_ip>-1-
a38c24f5-4b97-478e-8dab-1d938a59af14, code: &{824659379904}","peer":"<ip>-1-a05f1c79-220d-4e79-af81-020ff45d796c","task":"0
cde3188a70fe9fe2ed13572711f928bed5f0aada4ec07b176737259739ba147","component":"streamPeerTask","stacktrace":"d7y.io/dragonfly/v2/clie
nt/daemon/peer.(*peerTask).getPieceTasks.func1\n\t/go/src/d7y.io/dragonfly/v2/client/daemon/peer/peertask_base.go:809\nd7y.io/dragon
fly/v2/pkg/retry.Run\n\t/go/src/d7y.io/dragonfly/v2/pkg/retry/retry.go:41\nd7y.io/dragonfly/v2/client/daemon/peer.(*peerTask).getPie
ceTasks\n\t/go/src/d7y.io/dragonfly/v2/client/daemon/peer/peertask_base.go:779\nd7y.io/dragonfly/v2/client/daemon/peer.(*peerTask).p
reparePieceTasksByPeer\n\t/go/src/d7y.io/dragonfly/v2/client/daemon/peer/peertask_base.go:723\nd7y.io/dragonfly/v2/client/daemon/pee
r.(*peerTask).preparePieceTasks\n\t/go/src/d7y.io/dragonfly/v2/client/daemon/peer/peertask_base.go:698\nd7y.io/dragonfly/v2/client/d
aemon/peer.(*peerTask).pullPiecesFromPeers\n\t/go/src/d7y.io/dragonfly/v2/client/daemon/peer/peertask_base.go:420"}
{"level":"info","ts":"2021-10-11 02:44:22.014","caller":"peer/peertask_base.go:821","msg":"peer <another_ip>-1-a38c24f5-4b97-478e-8d
ab-1d938a59af14 returns success but with empty pieces, retry later","peer":"<ip>-1-a05f1c79-220d-4e79-af81-020ff45d796c","task":"0cde3188a70fe9fe2ed13572711f928bed5f0aada4ec07b176737259739ba147","component":"streamPeerTask"}

### Expected behavior:

All pull to pass. 

### Environment:
- Dragonfly version: 2.0.1.alpha
- OS:
- Kernel (e.g. `uname -a`):
- Others:

**Comment by mohafarooq** [comment]
Below are the errors in scheduler logs. 
Scheduler 1:

grpc.log:

{"level":"error","ts":"2021-10-11 10:02:37.160","caller":"rpc/server.go:226","msg":"peer <peer_ip1>-1-8d6d6a73-f252-45e0-9b10-0b355ab4432e not found","stacktrace":"d7y.io/dragonfly/v2/pkg/rpc.unaryServerInterceptor\n\t/go/src/d7y.io/dragonfly/v2/pkg/rpc/server.go:226\ngoogle.golang.org/grpc.chainUnaryServerInterceptors.func1\n\t/go/pkg/mod/google.golang.org/grpc@v1.39.0/server.go:1119\nd7y.io/dragonfly/v2/pkg/rpc/scheduler._Scheduler_ReportPeerResult_Handler\n\t/go/src/d7y.io/dragonfly/v2/pkg/rpc/scheduler/scheduler_grpc.pb.go:204\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/go/pkg/mod/google.golang.org/grpc@v1.39.0/server.go:1292\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/go/pkg/mod/google.golang.org/grpc@v1.39.0/server.go:1617\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2\n\t/go/pkg/mod/google.golang.org/grpc@v1.39.0/server.go:940"}
{"level":"error","ts":"2021-10-11 10:02:37.160","caller":grpc@v1.39.0/server.go:1119,"msg":"do unary server error: rpc error: code = Unknown desc = [5004]peer <peer_ip1>-1-8d6d6a73-f252-45e0-9b10-0b355ab4432e not found for method: /scheduler.Scheduler/ReportPeerResult","stacktrace":"google.golang.org/grpc.chainUnaryServerInterceptors.func1\n\t/go/pkg/mod/google.golang.org/grpc@v1.39.0/server.go:1119\nd7y.io/dragonfly/v2/pkg/rpc/scheduler._Scheduler_ReportPeerResult_Handler\n\t/go/src/d7y.io/dragonfly/v2/pkg/rpc/scheduler/scheduler_grpc.pb.go:204\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/go/pkg/mod/google.golang.org/grpc@v1.39.0/server.go:1292\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/go/pkg/mod/google.golang.org/grpc@v1.39.0/server.go:1617\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2\n\t/go/pkg/mod/google.golang.org/grpc@v1.39.0/server.go:940"}
{"level":"error","ts":"2021-10-11 10:02:38.570","caller":"rpc/server.go:226","msg":"peer <peer_ip2>-1-1c158f4f-756d-4c67-9be2-198c1b732732 not found","stacktrace":"d7y.io/dragonfly/v2/pkg/rpc.unaryServerInterceptor\n\t/go/src/d7y.io/dragonfly/v2/pkg/rpc/server.go:226\ngoogle.golang.org/grpc.chainUnaryServerInterceptors.func1\n\t/go/pkg/mod/google.golang.org/grpc@v1.39.0/server.go:1119\nd7y.io/dragonfly/v2/pkg/rpc/scheduler._Scheduler_ReportPeerResult_Handler\n\t/go/src/d7y.io/dragonfly/v2/pkg/rpc/scheduler/scheduler_grpc.pb.go:204\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/go/pkg/mod/google.golang.org/grpc@v1.39.0/server.go:1292\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/go/pkg/mod/google.golang.org/grpc@v1.39.0/server.go:1617\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2\n\t/go/pkg/mod/google.golang.org/grpc@v1.39.0/server.go:940"}
{"level":"error","ts":"2021-10-11 10:02:38.570","caller":grpc@v1.39.0/server.go:1119,"msg":"do unary server error: rpc error: code = Unknown desc = [5004]peer <peer_ip2>-1-1c158f4f-756d-4c67-9be2-198c1b732732 not found for method: /scheduler.Scheduler/ReportPeerResult","stacktrace":"google.golang.org/grpc.chainUnaryServerInterceptors.func1\n\t/go/pkg/mod/google.golang.org/grpc@v1.39.0/server.go:1119\nd7y.io/dragonfly/v2/pkg/rpc/scheduler._Scheduler_ReportPeerResult_Handler\n\t/go/src/d7y.io/dragonfly/v2/pkg/rpc/scheduler/scheduler_grpc.pb.go:204\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/go/pkg/mod/google.golang.org/grpc@v1.39.0/server.go:1292\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/go/pkg/mod/google.golang.org/grpc@v1.39.0/server.go:1617\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2\n\t/go/pkg/mod/google.golang.org/grpc@v1.39.0/server.go:940"}

{"level":"info","ts":"2021-10-11 10:05:33.684","caller":"grpclog/grpclog.go:37","msg":"[transport]transport: loopyWriter.run returning. connection error: desc = \"transport is closing\""}
{"level":"info","ts":"2021-10-11 10:06:32.894","caller":"grpclog/grpclog.go:37","msg":"[transport]transport: loopyWriter.run returning. connection error: desc = \"transport is closing\""}


Scheduler 2: 

Core.log:

core-2021-10-11T03-57-39.281.log:{"level":"error","ts":"2021-10-11 02:42:57.903","caller":"core/events.go:95","msg":"reScheduleParent: failed to schedule parent to peer <peer_ip2>-1-bd0f1237-049e-4267-83ce-c9567dcc3fa5, reschedule it later","stacktrace":"d7y.io/dragonfly/v2/scheduler/core.reScheduleParentEvent.apply\n\t/go/src/d7y.io/dragonfly/v2/scheduler/core/events.go:95\nd7y.io/dragonfly/v2/scheduler/core.(*baseWorker).start\n\t/go/src/d7y.io/dragonfly/v2/scheduler/core/worker.go:83"}
core-2021-10-11T03-57-39.281.log:{"level":"error","ts":"2021-10-11 02:42:58.323","caller":"core/events.go:95","msg":"reScheduleParent: failed to schedule parent to peer <peer_ip3>-1-d68e6a6a-8319-4a45-89d2-0a2b3b84326f, reschedule it later","stacktrace":"d7y.io/dragonfly/v2/scheduler/core.reScheduleParentEvent.apply\n\t/go/src/d7y.io/dragonfly/v2/scheduler/core/events.go:95\nd7y.io/dragonfly/v2/scheduler/core.(*baseWorker).start\n\t/go/src/d7y.io/dragonfly/v2/scheduler/core/worker.go:83"}


grpc.log:

{"level":"error","ts":"2021-10-11 10:02:38.569","caller":"rpc/server.go:226","msg":"peer <peer_ip2>-1-1c158f4f-756d-4c67-9be2-198c1b732732 not found","stacktrace":"d7y.io/dragonfly/v2/pkg/rpc.unaryServerInterceptor\n\t/go/src/d7y.io/dragonfly/v2/pkg/rpc/server.go:226\ngoogle.golang.org/grpc.chainUnaryServerInterceptors.func1\n\t/go/pkg/mod/google.golang.org/grpc@v1.39.0/server.go:1119\nd7y.io/dragonfly/v2/pkg/rpc/scheduler._Scheduler_ReportPeerResult_Handler\n\t/go/src/d7y.io/dragonfly/v2/pkg/rpc/scheduler/scheduler_grpc.pb.go:204\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/go/pkg/mod/google.golang.org/grpc@v1.39.0/server.go:1292\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/go/pkg/mod/google.golang.org/grpc@v1.39.0/server.go:1617\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2\n\t/go/pkg/mod/google.golang.org/grpc@v1.39.0/server.go:940"}
{"level":"error","ts":"2021-10-11 10:02:38.569","caller":grpc@v1.39.0/server.go:1119,"msg":"do unary server error: rpc error: code = Unknown desc = [5004]peer <peer_ip2>-1-1c158f4f-756d-4c67-9be2-198c1b732732 not found for method: /scheduler.Scheduler/ReportPeerResult","stacktrace":"google.golang.org/grpc.chainUnaryServerInterceptors.func1\n\t/go/pkg/mod/google.golang.org/grpc@v1.39.0/server.go:1119\nd7y.io/dragonfly/v2/pkg/rpc/scheduler._Scheduler_ReportPeerResult_Handler\n\t/go/src/d7y.io/dragonfly/v2/pkg/rpc/scheduler/scheduler_grpc.pb.go:204\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/go/pkg/mod/google.golang.org/grpc@v1.39.0/server.go:1292\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/go/pkg/mod/google.golang.org/grpc@v1.39.0/server.go:1617\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2\n\t/go/pkg/mod/google.golang.org/grpc@v1.39.0/server.go:940"}
{"level":"info","ts":"2021-10-11 10:05:27.985","caller":"grpclog/grpclog.go:37","msg":"[transport]transport: error closing conn during Close: close tcp <ip4>:8002-><ip5>:44746: use of closed network connection"}

{"level":"error","ts":"2021-10-11 09:55:10.545","caller":otelgrpc@v0.20.0/interceptor.go:368,"msg":"server receive a message: *scheduler.PieceResult error: rpc error: code = Canceled desc = context canceled for method: /scheduler.Scheduler/ReportPieceResult","stacktrace":"go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc.(*serverStream).RecvMsg\n\t/go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc@v0.20.0/interceptor.go:368\nd7y.io/dragonfly/v2/pkg/rpc/scheduler.(*schedulerReportPieceResultServer).Recv\n\t/go/src/d7y.io/dragonfly/v2/pkg/rpc/scheduler/scheduler_grpc.pb.go:183\nd7y.io/dragonfly/v2/scheduler/supervisor.(*Channel).receiveLoop\n\t/go/src/d7y.io/dragonfly/v2/scheduler/supervisor/peer.go:588"}

**Comment by mohafarooq** [comment]
I am attaching a daemon log for a specific task id.
[downloadfailure_bug.txt.gz](https://github.com/dragonflyoss/Dragonfly2/files/7328397/downloadfailure_bug.txt.gz)

**Comment by mohafarooq** [comment]
I have given the details to @jim3ma and @gaius-qi via Ding.

**Comment by jim3ma** [comment]
Can your grep "task .* connection closed" in scheduler log ?

**Comment by mohafarooq** [comment]
There is nothing in the scheduler log matching that pattern. 
# grep -i  "connection closed" *

**Comment by mohafarooq** [comment]
I see this in the scheduler log. is it related? 

core-2021-10-11T04-01-42.729.log:{"level":"info","ts":"2021-10-05 00:33:28.538","caller":"supervisor/cdn.go:158","msg":"task 0cde3188a70fe9fe2ed13572711f928bed5f0aada4ec07b176737259739ba147 init cdn peer &{<CDN_server1>-0cde3188a70fe9fe2ed13572711f928bed5f0aada4ec07b176737259739ba147_CDN 0xc00044bd40 0xc000423b80 {[] 0} 0xc000633638 0xc000633668 {{<nil>} []} 0xc0006a8a20 {{1} []} [] {{<nil>} []} {[] {[] 0}} 0xc000633698 {{0 0} 0 0 0 0}}"}
core-2021-10-11T04-01-42.729.log:{"level":"info","ts":"2021-10-05 00:34:29.036","caller":"supervisor/cdn.go:158","msg":"task 0cde3188a70fe9fe2ed13572711f928bed5f0aada4ec07b176737259739ba147 init cdn peer &{<CDN_server1>-0cde3188a70fe9fe2ed13572711f928bed5f0aada4ec07b176737259739ba147_CDN 0xc0006d45b0 0xc00075c8c0 {[] 0} 0xc000924048 0xc000924078 {{<nil>} []} 0xc0009061e0 {{1} []} [] {{<nil>} []} {[] {[] 0}} 0xc0009240a8 {{0 0} 0 0 0 0}}"}
core-2021-10-11T04-01-42.729.log:{"level":"info","ts":"2021-10-05 03:44:53.016","caller":"supervisor/cdn.go:158","msg":"task 0cde3188a70fe9fe2ed13572711f928bed5f0aada4ec07b176737259739ba147 init cdn peer &{<CDN_server1>-0cde3188a70fe9fe2ed13572711f928bed5f0aada4ec07b176737259739ba147_CDN 0xc0004a6820 0xc00013d360 {[] 0} 0xc000814888 0xc000814948 {{<nil>} []} 0xc00012dc50 {{1} []} [] {{<nil>} []} {[] {[] 0}} 0xc000814ab0 {{0 0} 0 0 0 0}}"}
core-2021-10-11T04-01-42.729.log:{"level":"info","ts":"2021-10-05 03:45:10.837","caller":"supervisor/cdn.go:158","msg":"task 0cde3188a70fe9fe2ed13572711f928bed5f0aada4ec07b176737259739ba147 init cdn peer &{<CDN_server2>-0cde3188a70fe9fe2ed13572711f928bed5f0aada4ec07b176737259739ba147_CDN 0xc000374680 0xc00033ee60 {[] 0} 0xc000ab0720 0xc000ab0750 {{<nil>} []} 0xc000aa3e60 {{1} []} [] {{<nil>} []} {[] {[] 0}} 0xc000ab0780 {{0 0} 0 0 0 0}}"}
core-2021-10-11T04-01-42.729.log:{"level":"info","ts":"2021-10-05 03:46:08.437","caller":"supervisor/cdn.go:158","msg":"task 0cde3188a70fe9fe2ed13572711f928bed5f0aada4ec07b176737259739ba147 init cdn peer &{<CDN_server1>-0cde3188a70fe9fe2ed13572711f928bed5f0aada4ec07b176737259739ba147_CDN 0xc0003eeb60 0xc0000b7540 {[] 0} 0xc000806318 0xc000806348 {{<nil>} []} 0xc000794960 {{1} []} [] {{<nil>} []} {[] {[] 0}} 0xc000806378 {{0 0} 0 0 0 0}}"}
core-2021-10-11T04-01-42.729.log:{"level":"info","ts":"2021-10-05 03:47:54.280","caller":"supervisor/cdn.go:158","msg":"task 0cde3188a70fe9fe2ed13572711f928bed5f0aada4ec07b176737259739ba147 init cdn peer &{<CDN_server1>-0cde3188a70fe9fe2ed13572711f928bed5f0aada4ec07b176737259739ba147_CDN 0xc0006ccf70 0xc0000b7040 {[] 0} 0xc000e32678 0xc000e326a8 {{<nil>} []} 0xc0005815c0 {{1} []} [] {{<nil>} []} {[] {[] 0}} 0xc000e326d8 {{0 0} 0 0 0 0}}"}
core-2021-10-11T04-01-42.729.log:{"level":"info","ts":"2021-10-11 02:41:58.485","caller":"supervisor/cdn.go:158","msg":"task 0cde3188a70fe9fe2ed13572711f928bed5f0aada4ec07b176737259739ba147 init cdn peer &{<CDN_server2>-0cde3188a70fe9fe2ed13572711f928bed5f0aada4ec07b176737259739ba147_CDN 0xc000462dd0 0xc000146640 {[] 0} 0xc0006c7440 0xc0006c7488 {{<nil>} []} 0xc000721050 {{1} []} [] {{<nil>} []} {[] {[] 0}} 0xc0006c74e8 {{0 0} 0 0 0 0}}"}
core-2021-10-12T03-31-54.998.log:{"level":"info","ts":"2021-10-11 09:54:25.427","caller":"supervisor/cdn.go:158","msg":"task 23c4567c005ffaafa85a77bba56d07e7d2a87db6b8dea4ad54ba049ec5b93b41 init cdn peer &{<CDN_server3>-23c4567c005ffaafa85a77bba56d07e7d2a87db6b8dea4ad54ba049ec5b93b41_CDN 0xc0004768f0 0xc000146780 {[] 0} 0xc0007d5e78 0xc0007d5ec0 {{<nil>} []} 0xc0009c6cf0 {{1} []} [] {{<nil>} []} {[] {[] 0}} 0xc0007d5ef0 {{0 0} 0 0 0 0}}"}
core-2021-10-12T03-31-54.998.log:{"level":"info","ts":"2021-10-11 23:59:04.510","caller":"supervisor/cdn.go:158","msg":"task 0cde3188a70fe9fe2ed13572711f928bed5f0aada4ec07b176737259739ba147 init cdn peer &{<CDN_server2>-0cde3188a70fe9fe2ed13572711f928bed5f0aada4ec07b176737259739ba147_CDN 0xc000662b60 0xc00019af00 {[] 0} 0xc000ab3dd0 0xc000ab3e90 {{<nil>} []} 0xc000434ae0 {{1} []} [] {{<nil>} []} {[] {[] 0}} 0xc000ab3f20 {{0 0} 0 0 0 0}}"}
core-2021-10-12T03-40-20.253.log:{"level":"info","ts":"2021-10-12 03:39:47.443","caller":"supervisor/cdn.go:158","msg":"task 23c4567c005ffaafa85a77bba56d07e7d2a87db6b8dea4ad54ba049ec5b93b41 init cdn peer &{<CDN_server3>-23c4567c005ffaafa85a77bba56d07e7d2a87db6b8dea4ad54ba049ec5b93b41_CDN 0xc0002f6a90 0xc0000b7220 {[] 0} 0xc0007fa648 0xc0007fa678 {{<nil>} []} 0xc0007657d0 {{1} []} [] {{<nil>} []} {[] {[] 0}} 0xc0007fa6c0 {{0 0} 0 0 0 0}}"}
core.log:{"level":"info","ts":"2021-10-12 03:40:59.482","caller":"supervisor/cdn.go:158","msg":"task 23c4567c005ffaafa85a77bba56d07e7d2a87db6b8dea4ad54ba049ec5b93b41 init cdn peer &{<CDN_server3>-23c4567c005ffaafa85a77bba56d07e7d2a87db6b8dea4ad54ba049ec5b93b41_CDN 0xc0003ce820 0xc000145220 {[] 0} 0xc000483800 0xc000483830 {{<nil>} []} 0xc000892120 {{1} []} [] {{<nil>} []} {[] {[] 0}} 0xc000483860 {{0 0} 0 0 0 0}}"}
core.log:{"level":"info","ts":"2021-10-12 03:41:58.463","caller":"supervisor/cdn.go:158","msg":"task 23c4567c005ffaafa85a77bba56d07e7d2a87db6b8dea4ad54ba049ec5b93b41 init cdn peer &{<CDN_server3>-23c4567c005ffaafa85a77bba56d07e7d2a87db6b8dea4ad54ba049ec5b93b41_CDN 0xc0003f55f0 0xc0004035e0 {[] 0} 0xc00071e2b8 0xc00071e2e8 {{<nil>} []} 0xc0005bf0b0 {{1} []} [] {{<nil>} []} {[] {[] 0}} 0xc00071e318 {{0 0} 0 0 0 0}}"}
core.log:{"level":"info","ts":"2021-10-12 03:42:59.118","caller":"supervisor/cdn.go:158","msg":"task 23c4567c005ffaafa85a77bba56d07e7d2a87db6b8dea4ad54ba049ec5b93b41 init cdn peer &{<CDN_server3>-23c4567c005ffaafa85a77bba56d07e7d2a87db6b8dea4ad54ba049ec5b93b41_CDN 0xc00033e820 0xc000493040 {[] 0} 0xc00000cb10 0xc00000cb40 {{<nil>} []} 0xc0006caf90 {{1} []} [] {{<nil>} []} {[] {[] 0}} 0xc00000cb70 {{0 0} 0 0 0 0}}"}
core.log:{"level":"info","ts":"2021-10-12 03:43:59.528","caller":"supervisor/cdn.go:158","msg":"task 23c4567c005ffaafa85a77bba56d07e7d2a87db6b8dea4ad54ba049ec5b93b41 init cdn peer &{<CDN_server3>-23c4567c005ffaafa85a77bba56d07e7d2a87db6b8dea4ad54ba049ec5b93b41_CDN 0xc0006e69c0 0xc00019b0e0 {[] 0} 0xc000640378 0xc0006403a8 {{<nil>} []} 0xc00088f050 {{1} []} [] {{<nil>} []} {[] {[] 0}} 0xc0006403d8 {{0 0} 0 0 0 0}}"}

**Comment by mohafarooq** [comment]
edited my last message.
