### ISSUE TITLE
Warning while reloading the tasks for the disk

### ISSUE THREAD

**Issue by mohafarooq** [dragonflyoss/Dragonfly2#726]
### Bug report:

Warning while reloading the tasks for the disk. Anything to be worried about?

{"level":"warn","ts":"2021-10-13 04:01:09.440","caller":"storage/storage_manager.go:483","msg":"load task from disk error: unexpected end of JSON input","
action":"reload","stage":"parse metadata","taskID":"0cde3188a70fe9fe2ed13572711f928bed5f0aada4ec07b176737259739ba147","peerID":"x.y.z.a-1-09276e30-8
ac7-4e53-a436-18ada458e58f","stacktrace":"d7y.io/dragonfly/v2/client/daemon/storage.(*storageManager).ReloadPersistentTask\n\t/go/src/d7y.io/dragonfly/v2/
client/daemon/storage/storage_manager.go:483\nd7y.io/dragonfly/v2/client/daemon/storage.NewStorageManager\n\t/go/src/d7y.io/dragonfly/v2/client/daemon/sto
rage/storage_manager.go:165\nd7y.io/dragonfly/v2/client/daemon.New\n\t/go/src/d7y.io/dragonfly/v2/client/daemon/daemon.go:111\nd7y.io/dragonfly/v2/cmd/dfg
et/cmd.runDaemon\n\t/go/src/d7y.io/dragonfly/v2/cmd/dfget/cmd/daemon.go:144\nd7y.io/dragonfly/v2/cmd/dfget/cmd.glob..func1\n\t/go/src/d7y.io/dragonfly/v2/
cmd/dfget/cmd/daemon.go:70\ngithub.com/spf13/cobra.(*Command).execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850\ngithub.com/spf13/cobra.
(*Command).ExecuteC\n\t/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958\ngithub.com/spf13/cobra.(*Command).Execute\n\t/go/pkg/mod/github.com/spf13
/cobra@v1.1.1/command.go:895\nd7y.io/dragonfly/v2/cmd/dfget/cmd.Execute\n\t/go/src/d7y.io/dragonfly/v2/cmd/dfget/cmd/root.go:107\nmain.main\n\t/go/src/d7y
.io/dragonfly/v2/cmd/dfget/main.go:28\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225"}
{"level":"warn","ts":"2021-10-13 04:01:09.440","caller":"storage/storage_manager.go:483","msg":"load task from disk error: unexpected end of JSON input","
action":"reload","stage":"parse metadata","taskID":"0cde3188a70fe9fe2ed13572711f928bed5f0aada4ec07b176737259739ba147","peerID":"x.y.z.a-1-0a877d17-4
fdb-4f05-8be2-6363eaa042ec","stacktrace":"d7y.io/dragonfly/v2/client/daemon/storage.(*storageManager).ReloadPersistentTask\n\t/go/src/d7y.io/dragonfly/v2/
client/daemon/storage/storage_manager.go:483\nd7y.io/dragonfly/v2/client/daemon/storage.NewStorageManager\n\t/go/src/d7y.io/dragonfly/v2/client/daemon/sto
rage/storage_manager.go:165\nd7y.io/dragonfly/v2/client/daemon.New\n\t/go/src/d7y.io/dragonfly/v2/client/daemon/daemon.go:111\nd7y.io/dragonfly/v2/cmd/dfg
et/cmd.runDaemon\n\t/go/src/d7y.io/dragonfly/v2/cmd/dfget/cmd/daemon.go:144\nd7y.io/dragonfly/v2/cmd/dfget/cmd.glob..func1\n\t/go/src/d7y.io/dragonfly/v2/
cmd/dfget/cmd/daemon.go:70\ngithub.com/spf13/cobra.(*Command).execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850\ngithub.com/spf13/cobra.
(*Command).ExecuteC\n\t/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958\ngithub.com/spf13/cobra.(*Command).Execute\n\t/go/pkg/mod/github.com/spf13
/cobra@v1.1.1/command.go:895\nd7y.io/dragonfly/v2/cmd/dfget/cmd.Execute\n\t/go/src/d7y.io/dragonfly/v2/cmd/dfget/cmd/root.go:107\nmain.main\n\t/go/src/d7y
.io/dragonfly/v2/cmd/dfget/main.go:28\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225"}

### Environment:
- Dragonfly version: v2.0.1-alpha.1
- OS:
- Kernel (e.g. `uname -a`):
- Others:

**Comment by jim3ma** [comment]
Search logs for `x.y.z.a-1-0a877d17-4fdb-4f05-8be2-6363eaa042ec`, it seems `x.y.z.a-1-0a877d17-4fdb-4f05-8be2-6363eaa042ec` is not done.

**Comment by mohafarooq** [comment]
Warning about incomplete downloads. closing the issue.
