### ISSUE TITLE
Image downloads are going on for more than 1 hour

### ISSUE THREAD

**Issue by mfarooq-tech** [dragonflyoss/Dragonfly2#729]
### Bug report:

Long download time for the task 0cde3188a70fe9fe2ed13572711f928bed5f0aada4ec07b176737259739ba147 . It seems like download is going on in a loop. It took ~ 1 hour and 40 minutes and the download is still going on. The dfdaemon log for this task is attached. 

### Environment:
- Dragonfly version:
- OS:
- Kernel (e.g. `uname -a`):
- Others

:

**Comment by mohafarooq** [comment]
Relevant dfget.yaml:

` download service option
download:
  # calculate digest when transfer files, set false to save memory
  calculateDigest: true
  # total download limit per second
  totalRateLimit: 20000Mi
  # per peer task download limit per second
  perPeerRateLimit: 10000Mi
  # download piece timeout
  pieceDownloadTimeout: 30s
  # download grpc option
  downloadGRPC:
    # security option
    security:
      insecure: true
      cacert: ""
      cert: ""
      key: ""
      tlsConfig: null
    # download service listen address
    # current, only support unix domain socket
    unixListen:
      # in linux, default value is /var/run/dfdaemon.sock
      # in macos(just for testing), default value is /tmp/dfdaemon.sock
      socket: /var/run/dfdaemon.sock
  # peer grpc option
  # peer grpc service send pieces info to other peers
  peerGRPC:
    security:
      insecure: true
      cacert: ""
      cert: ""
      key: ""
    tcpListen:
      # listen address
      listen: 0.0.0.0
      # listen port, daemon will try to listen
      # when this port is not available, daemon will try next port
      port: 65000
      # if want to limit upper port, please use blow format
#     port:
#       start: 65000
#       end: 65009

# upload service option
upload:
  # upload limit per second
  rateLimit: 20000Mi
  security:
    insecure: true
    cacert: ""
    cert: ""
    key: ""
  tcpListen:
    # listen address
    listen: 0.0.0.0
    # listen port, daemon will try to listen
    # when this port is not available, daemon will try next port
    port: 65002
    # if want to limit upper port, please use blow format
#   port:
#     start: 65020
#     end: 65029
`

scheduler.yaml: 

`# This file is the template of scheduler configuration file.
# You can configure your scheduler by change the parameter according your requirement.

# scheduler policy configuration
scheduler:
  # abtest whether to open ab test
  # default: false
  abtest: false
  # aevaluator specify which evaluator is used when taskID suffix with _A
  # only take effect when abtest is true
  # default: ""
  aevaluator: ""
  # bevaluator specify which evaluator is used when taskID suffix with _B
  # only take effect when abtest is true
  # default: ""
  bevaluator: ""
  # workerNum is the number of goroutines that perform scheduling tasks
  # default:
  workerNum: 12
  # backSourceCount is the number of back-to-origin clients when the CDN is disable or unavailable
  # default: 3
  backSourceCount: 3
  # accessWindow is access interval window that can trigger CDN back to the source again
  # default: 3m
  accessWindow: 3m
  # candidateParentCount is number of candidate parent nodes
  # default: 10
  candidateParentCount: 10
  # scheduler is currently effective scheduling policy
  # default: basic
  scheduler: basic
  # cdnLoad is CDN host can provide the maximum upload load
  # default: 100
  cdnLoad: 100
  # clientLoad is client host can provide the maximum upload load
  # default: 10
  clientLoad: 10
  # openMonitor Whether to enable monitoring, currently only the current peer list status information is monitored
  # default: false
  openMonitor: false
  # gc metadata configuration
  gc:
    # peerGCInterval peer's gc interval
    peerGCInterval: 1m
    # peerTTL peer's TTL duration
    peerTTL: 10h
    # peerTTI peer's TTI duration
    peerTTI: 3h
    # taskGCInterval task's gc interval
    taskGCInterval: 1m
    # taskTTL task's TTL duration
    taskTTL: 10h
    # taskTTI task's TTI duration
    taskTTI: 3h

# server scheduler instance configuration
server:
  # ip
  ip:
  # host
  host:
  # ListenPort is the ip and port scheduler server listens on.
  # default: 8002
  port: 8002


# dynamic data configuration
dynConfig:
  # type
  type: manager
  # expireTime
  expireTime:
  # cdnDirPath
  cdnDirPath:
  # data
  data: {}

# manager configuration
manager:
  # addr manager access address
  addr: <managerIPs>:65003
  # schedulerClusterID cluster id to which scheduler instance belongs
  schedulerClusterID: 1
  # keepAlive keep alive configuration
  keepAlive:
    # interval
    interval: 5s

# host scheduler host configuration
host:
  # location is the location of scheduler instance
  location: ""
  # idc is the idc of scheduler instance
  idc: ""

# machinery async job configuration, see https://github.com/RichardKnop/machinery
job:
  # globalWorkerNum
  globalWorkerNum: 2
  # schedulerWorkerNum
  schedulerWorkerNum: 3
  # localWorkerNum
  localWorkerNum: 3
  # redis configuration
  redis:
    # host
    host: <host>
    # port
    port: 6379
    # password
    password: "<passwrd>"
    # brokerDB
    brokerDB: ""
    # backendDB
    backendDB: ""

# Whether to disable CDN
# default: false
disableCDN: false

# Console shows log on console
# default: false
console: false

# Whether to enable debug level logger and enable pprof
# default: false
verbose: true

# listen port for pprof, only valid when the verbose option is true
# default is -1. If it is 0, pprof will use a random port.
pprofPort: -1

# jaeger endpoint url
# default: ""
jaeger: "http://<jaegerip>:14268/api/traces"

# service name used in tracer
# default: dragonfly-scheduler
service-name: dragonfly-scheduler
`

**Comment by jim3ma** [comment]
> For some of the slow downloads, I see below message in the dfdaemon log. Is this slowness due to it is being downloaded from the source? Can you confirm this?
> 
> ```
> {"level":"info","ts":"2021-10-14 05:19:24.504","caller":"peer/peertask_base.go:508","msg":"start download from source due to dfcodes.SchedNeedBackSourc
> e","peer":"x.y.z.12-1-2fed0ac7-2d68-4d9f-ace1-1588fc57f706","task":"0cde3188a70fe9fe2ed13572711f928bed5f0aada4ec07b176737259739ba147","component":
> "streamPeerTask"}
> ```

Yes, when the cdn load is high, the scheduler will let peer back source.

scheduler config:
```
  # backSourceCount is the number of back-to-origin clients when the CDN is disable or unavailable
  # default: 3
  backSourceCount: 3
```

@244372610 It only be used when `the CDN is disable or unavailable` ?

**Comment by mohafarooq** [comment]
Even if the CDN was loaded, shouldn’t it get the image from the peers? Why is it going back to the source? Many of the peers already had this image, and it didn’t download the images from the peer.

**Comment by mohafarooq** [comment]
Log. 

[peerPacket.log](https://github.com/dragonflyoss/Dragonfly2/files/7364529/peerPacket.log)

**Comment by mohafarooq** [comment]
Uploaded logs for x.y.z.14-1-fb87537d-9ccc-42d4-b2db-53f28f66c1af.
[x.y.z.14-1-fb87537d-9ccc-42d4-b2db-53f28f66c1af.log](https://github.com/dragonflyoss/Dragonfly2/files/7364901/x.y.z.14-1-fb87537d-9ccc-42d4-b2db-53f28f66c1af.log)

**Comment by gaius-qi** [comment]
Set client load limit:
![image](https://user-images.githubusercontent.com/15955374/138043245-4f1805dc-36c9-400d-bf87-77bf9ad49b08.png)

Set cdn load limit:
![image](https://user-images.githubusercontent.com/15955374/138043282-b08d4f4e-486a-4967-9c09-cf7deeeadbb3.png)
