### ISSUE TITLE
error: context deadline exceeded (Client.Timeout or context cancellation while reading body)

### ISSUE THREAD

**Issue by mohafarooq** [dragonflyoss/Dragonfly2#775]
### Bug report:

{"level":"error","ts":"2021-10-29 07:15:29.591","caller":"peer/piece_manager.go:154","msg":"put piece to storage failed, piece num: 40, wrote: 0, error: context deadline exceeded (Client.Timeout or context cancellation while reading body)","peer":"x.y.z.5-1-4ead15eb-1198-4ae7-bf93-7270a414724e","task":"0cde3188a70fe9fe2ed13572711f928bed5f0aada4ec07b176737259739ba147","component":"streamPeerTask","stacktrace":"d7y.io/dragonfly/v2/client/daemon/peer.(*pieceManager).DownloadPiece\n\t/go/src/d7y.io/dragonfly/v2/client/daemon/peer/piece_manager.go:154\nd7y.io/dragonfly/v2/client/daemon/peer.(*peerTask).downloadPieceWorker\n\t/go/src/d7y.io/dragonfly/v2/client/daemon/peer/peertask_base.go:664"}

### Environment:
- Dragonfly version: alpha.7
- OS:
- Kernel (e.g. `uname -a`):
- Others:

dfdaemon:
[x.y.z.5-1-4ead15eb-1198-4ae7-bf93-7270a414724e.log](https://github.com/dragonflyoss/Dragonfly2/files/7442680/x.y.z.5-1-4ead15eb-1198-4ae7-bf93-7270a414724e.log)

scheduler:
[scheduler_1.log](https://github.com/dragonflyoss/Dragonfly2/files/7442766/scheduler_1.log)

**Comment by gaius-qi** [comment]
Download piece timeout caused this error. The default download piece timeout time is 30s, you can refer to [dfdaemon configuration](https://github.com/dragonflyoss/Dragonfly2/blob/main/docs/en/deployment/configuration/dfget.yaml#L67) to modify.
