### ISSUE TITLE
Scale-out a single task across multiple CDN 

### ISSUE THREAD

**Issue by mohafarooq** [dragonflyoss/Dragonfly2#788]
### Feature request:

Currently, in a scale execution, the CDN can become a bottleneck because the hash ring assigns one CDN per task and when there are multiple concurrent downloads for an image, the CDN n/w usage reaches 100%, and downloads slow down. It improves when the peer gets the image. However, for a few minutes, the NW load on CDN is high and the download speed is slow. 
There should be a way to scale out a single task to multiple CDN if the n/w bandwidth usage on the CDN goes beyond the threshold.

**Comment by mohafarooq** [comment]
@jim3ma @244372610 : Any updates on this?

**Comment by jim3ma** [comment]
@244372610 is working on this feature.

**Comment by 244372610** [comment]
https://github.com/dragonflyoss/Dragonfly2/pull/801/files

**Comment by mohafarooq** [comment]
Thanks. I see that the PR #801 gives CDN low priority. Let us consider a scenario. I have 2000 pulls for a 5GB image at the same  time. All the pieces has to come from CDN and none of the peers have pieces. The CDN network bandwidth will be 100% used. Can another CDN in the network take the load at this this scenario?

**Comment by mohafarooq** [comment]
Hi @jim3ma @244372610 : This is not closed. There is no scaleout for CDN.
