### ISSUE TITLE
gc stopped working on the clients/dfdaemon

### ISSUE THREAD

**Issue by mfarooq-intel** [dragonflyoss/Dragonfly2#789]
### Bug report:

The taskExpireTime is set to 3m and gc interval is at 1m. The dfdaemon dc doesn't get triggered. Even restarting the dfdaemon is not solving the issue.

### Environment:
- Dragonfly version: alpha.9
- OS:
- Kernel (e.g. `uname -a`):
- Others:

**Comment by mohafarooq** [comment]
Attached the dfdaemon log.
[core.log.gz](https://github.com/dragonflyoss/Dragonfly2/files/7518132/core.log.gz)

**Comment by gaius-qi** [comment]
Please try latest version.
