### ISSUE TITLE
High CPU usage by dfget process

### ISSUE THREAD

**Issue by mfarooq-intel** [dragonflyoss/Dragonfly2#803]
### Bug report:

@jim3ma : I have executed pprof to find out the CPU utilization of dfget.

40 seconds:
[pprof.dfget.samples.cpu.002.pb.gz](https://github.com/dragonflyoss/Dragonfly2/files/7544611/pprof.dfget.samples.cpu.002.pb.gz)

20 seconds:

[pprof.dfget.samples.cpu.003.pb.gz](https://github.com/dragonflyoss/Dragonfly2/files/7544612/pprof.dfget.samples.cpu.003.pb.gz)

### Environment:
- Dragonfly version:
- OS:
- Kernel (e.g. `uname -a`):
- Others:

**Comment by jim3ma** [comment]
According the flame graph, above 70% cpu time is cost in `tls` encryption, another 30% is cost in reading file.
I think all of these need to offload the tls encryption and decryption into kernel using `ktls`.

<img width="1353" alt="Screen Shot 2021-11-16 at 8 38 19 PM" src="https://user-images.githubusercontent.com/1567113/141987269-c14979bf-8955-4f78-a7c5-0a0974678697.png">

**Comment by jim3ma** [comment]
A workaround - disable tls when upload data to other peers.

**Comment by mohafarooq** [comment]
> A workaround - disable tls when upload data to other peers.

How to do that?

**Comment by jim3ma** [comment]
> > A workaround - disable tls when upload data to other peers.
> 
> How to do that?

See https://github.com/dragonflyoss/Dragonfly2/blob/main/docs/en/deployment/configuration/dfget.yaml#L106
By default, tls is disabled, you can have a try.

**Comment by mohafarooq** [comment]
> > > A workaround - disable tls when upload data to other peers.
> > 
> > 
> > How to do that?
> 
> See https://github.com/dragonflyoss/Dragonfly2/blob/main/docs/en/deployment/configuration/dfget.yaml#L106 By default, tls is disabled, you can have a try.

I already have it

```
upload:
  # upload limit per second
  rateLimit: 10G
  security:
    insecure: true
    cacert: ""
    cert: ""
    key: ""
  tcpListen:
    # listen address
```
