### ISSUE TITLE
Scale-out a single task across multiple CDN 

### ISSUE THREAD

**Issue by mfarooq-intel** [dragonflyoss/Dragonfly2#810]
### Feature request:

Currently, in a scale execution, the CDN can become a bottleneck because the hash ring assigns one CDN per task and when there are multiple concurrent downloads for an image, the CDN n/w usage reaches 100%, and downloads slow down. It improves when the peer gets the image. However, for a few minutes, the NW load on CDN is high and the download speed is slow.
There should be a way to scale out a single task to multiple CDN if the n/w bandwidth usage on the CDN goes beyond the threshold.

Issue #788 didn't solve this. 

@jim3ma @gaius-qi

**Comment by gaius-qi** [comment]
Feature #801 has been released in `v2.0.1-beta.3`.

**Comment by gaius-qi** [comment]
@244372610 #788
