### ISSUE TITLE
dfget stuck for long time

### ISSUE THREAD

**Issue by wangxiaoq** [dragonflyoss/Dragonfly2#826]
### Bug report:

please see: https://github.com/dragonflyoss/Dragonfly/issues/1157

### Expected behavior:

please see: https://github.com/dragonflyoss/Dragonfly/issues/1157

### How to reproduce it:

please see: https://github.com/dragonflyoss/Dragonfly/issues/1157

### Environment:
- Dragonfly version:
- OS:
- Kernel (e.g. `uname -a`):
- Others:

**Comment by wangxiaoq** [comment]
Hi, it's a bug in dragonfly 1 repository, is this problem solved in dragonfly2, thanks

**Comment by wangxiaoq** [comment]
I think it's a really serious problem, because it could affect the system stability, hope to receive your reply, thanks in advance

**Comment by gaius-qi** [comment]
Dragonfly 1 will not be maintained, it is recommended to upgrade to dragonfly 2.
