### ISSUE TITLE
when the download task occur an error, the recycle of dfget client fails

### ISSUE THREAD

**Issue by litianxi** [dragonflyoss/Dragonfly2#836]
### Bug report:

**dfget client failed to exit, when dfget encountered this error "context done due to context canceled"**
#### dfget log (/var/log/dragonfly/daemon/core.log)
{"level":"info","ts":"2021-11-29 18:06:00.543","caller":"peer/peertask_base.go:461","msg":"all pieces requests send, just wait failed pieces","peer":"10.221.113.204-193-fae315fc-ce74-47bc-9ed7-34b50dc46317","task":"709f18bdb3610220731c0cd
0c86323b10d5df32d79e4e33507be248c2627899e","component":"filePeerTask"}
{"level":"info","ts":"2021-11-29 18:07:08.747","caller":"rpcserver/rpcserver.go:212","msg":"context done due to context canceled","peer":"10.221.113.204-193-fae315fc-ce74-47bc-9ed7-34b50dc46317","component":"downloadService"}
{"level":"error","ts":"2021-11-29 18:07:08.747","caller":"peer/peertask_file_callback.go:123","msg":"file peer task failed, code: 1500, reason: unknown","peer":"10.221.113.204-193-fae315fc-ce74-47bc-9ed7-34b50dc46317","task":"709f18bdb361
0220731c0cd0c86323b10d5df32d79e4e33507be248c2627899e","component":"filePeerTask","stacktrace":"d7y.io/dragonfly/v2/client/daemon/peer.(*filePeerTaskCallback).Fail\n\t/home/xxxxxxxxxxxxx/Dragonfly2/client/daemon/peer/peertask_file_callback.
go:123\nd7y.io/dragonfly/v2/client/daemon/peer.(*filePeerTask).cleanUnfinished.func1\n\t/home/xxxxxxxxxxxxx/Dragonfly2/client/daemon/peer/peertask_file.go:371\nsync.(*Once).doSlow\n\t/usr/local/go/src/sync/once.go:68\nsync.(*Once).Do\n\t/u
sr/local/go/src/sync/once.go:59\nd7y.io/dragonfly/v2/client/daemon/peer.(*filePeerTask).cleanUnfinished\n\t/home/xxxxxxxxxxxxx/Dragonfly2/client/daemon/peer/peertask_file.go:364\nd7y.io/dragonfly/v2/client/daemon/peer.(*peerTask).pullPiece
sFromPeers.func1\n\t/home/xxxxxxxxxxxxx/Dragonfly2/client/daemon/peer/peertask_base.go:373\nd7y.io/dragonfly/v2/client/daemon/peer.(*peerTask).pullPiecesFromPeers\n\t/home/xxxxxxxxxxxxx/Dragonfly2/client/daemon/peer/peertask_base.go:470"}
{"level":"error","ts":"2021-11-29 18:07:08.824","caller":"peer/peertask_base.go:249","msg":"receive peer packet failed: rpc error: code = Canceled desc = context canceled","peer":"10.221.113.204-193-fae315fc-ce74-47bc-9ed7-34b50dc46317","
task":"709f18bdb3610220731c0cd0c86323b10d5df32d79e4e33507be248c2627899e","component":"filePeerTask","stacktrace":"d7y.io/dragonfly/v2/client/daemon/peer.(*peerTask).receivePeerPacket\n\t/home/xxxxxxxxxxxxx/Dragonfly2/client/daemon/peer/pee
rtask_base.go:249"}
{"level":"error","ts":"2021-11-29 18:07:08.824","caller":"client/client.go:175","msg":"ReportPeerResult: report peer result to scheduler dns:///xxxxxxxxxxxxxxxxxxxxx:7002 failed: rpc error: code = Canceled desc = context canceled",
"taskId":"709f18bdb3610220731c0cd0c86323b10d5df32d79e4e33507be248c2627899e","peerID":"10.221.113.204-193-fae315fc-ce74-47bc-9ed7-34b50dc46317","stacktrace":"d7y.io/dragonfly/v2/pkg/rpc/scheduler/client.(*schedulerClient).ReportPeerResult\
n\t/home/xxxxxxxxxxxxx/Dragonfly2/pkg/rpc/scheduler/client/client.go:175\nd7y.io/dragonfly/v2/client/daemon/peer.(*filePeerTaskCallback).Fail\n\t/home/xxxxxxxxxxxxx/Dragonfly2/client/daemon/peer/peertask_file_callback.go:126\nd7y.io/dragonf
ly/v2/client/daemon/peer.(*filePeerTask).cleanUnfinished.func1\n\t/home/xxxxxxxxxxxxx/Dragonfly2/client/daemon/peer/peertask_file.go:371\nsync.(*Once).doSlow\n\t/usr/local/go/src/sync/once.go:68\nsync.(*Once).Do\n\t/usr/local/go/src/sync/o
nce.go:59\nd7y.io/dragonfly/v2/client/daemon/peer.(*filePeerTask).cleanUnfinished\n\t/home/xxxxxxxxxxxxx/Dragonfly2/client/daemon/peer/peertask_file.go:364\nd7y.io/dragonfly/v2/client/daemon/peer.(*peerTask).pullPiecesFromPeers.func1\n\t/h
ome/xxxxxxxxxxxxx/Dragonfly2/client/daemon/peer/peertask_base.go:373\nd7y.io/dragonfly/v2/client/daemon/peer.(*peerTask).pullPiecesFromPeers\n\t/home/xxxxxxxxxxxxx/Dragonfly2/client/daemon/peer/peertask_base.go:470"}
{"level":"error","ts":"2021-11-29 18:07:08.824","caller":"peer/peertask_file_callback.go:142","msg":"step 3: report fail peer result, error: rpc error: code = Canceled desc = context canceled","peer":"10.221.113.204-193-fae315fc-ce74-47bc
-9ed7-34b50dc46317","task":"709f18bdb3610220731c0cd0c86323b10d5df32d79e4e33507be248c2627899e","component":"filePeerTask","stacktrace":"d7y.io/dragonfly/v2/client/daemon/peer.(*filePeerTaskCallback).Fail\n\t/home/xxxxxxxxxxxxx/Dragonfly2/cl
ient/daemon/peer/peertask_file_callback.go:142\nd7y.io/dragonfly/v2/client/daemon/peer.(*filePeerTask).cleanUnfinished.func1\n\t/home/xxxxxxxxxxxxx/Dragonfly2/client/daemon/peer/peertask_file.go:371\nsync.(*Once).doSlow\n\t/usr/local/go/sr
c/sync/once.go:68\nsync.(*Once).Do\n\t/usr/local/go/src/sync/once.go:59\nd7y.io/dragonfly/v2/client/daemon/peer.(*filePeerTask).cleanUnfinished\n\t/home/xxxxxxxxxxxxx/Dragonfly2/client/daemon/peer/peertask_file.go:364\nd7y.io/dragonfly/v2/
client/daemon/peer.(*peerTask).pullPiecesFromPeers.func1\n\t/home/xxxxxxxxxxxxx/Dragonfly2/client/daemon/peer/peertask_base.go:373\nd7y.io/dragonfly/v2/client/daemon/peer.(*peerTask).pullPiecesFromPeers\n\t/home/xxxxxxxxxxxxx/Dragonfly2/cli
ent/daemon/peer/peertask_base.go:470"}
{"level":"info","ts":"2021-11-29 18:07:08.824","caller":"peer/peertask_file.go:395","msg":"try to send unfinished progress, completed length: 2781816968, state: (false, 1500, unknown)","peer":"10.221.113.204-193-fae315fc-ce74-47bc-9ed7-34
b50dc46317","task":"709f18bdb3610220731c0cd0c86323b10d5df32d79e4e33507be248c2627899e","component":"filePeerTask"}
{"level":"warn","ts":"2021-11-29 18:07:08.824","caller":"peer/peertask_file.go:411","msg":"wait progress stopped failed, context done, but progress not stopped","peer":"10.221.113.204-193-fae315fc-ce74-47bc-9ed7-34b50dc46317","task":"709f
18bdb3610220731c0cd0c86323b10d5df32d79e4e33507be248c2627899e","component":"filePeerTask","stacktrace":"d7y.io/dragonfly/v2/client/daemon/peer.(*filePeerTask).cleanUnfinished.func1\n\t/home/xxxxxxxxxxxxx/Dragonfly2/client/daemon/peer/peerta
sk_file.go:411\nsync.(*Once).doSlow\n\t/usr/local/go/src/sync/once.go:68\nsync.(*Once).Do\n\t/usr/local/go/src/sync/once.go:59\nd7y.io/dragonfly/v2/client/daemon/peer.(*filePeerTask).cleanUnfinished\n\t/home/xxxxxxxxxxxxx/Dragonfly2/client
/daemon/peer/peertask_file.go:364\nd7y.io/dragonfly/v2/client/daemon/peer.(*peerTask).pullPiecesFromPeers.func1\n\t/home/xxxxxxxxxxxxx/Dragonfly2/client/daemon/peer/peertask_base.go:373\nd7y.io/dragonfly/v2/client/daemon/peer.(*peerTask).p
ullPiecesFromPeers\n\t/home/xxxxxxxxxxxxx/Dragonfly2/client/daemon/peer/peertask_base.go:470"}

#### cdn log
11月 29 18:05:59  cdn[8955]: 2021-11-29T18:05:59.824+0800        INFO        rpcserver/rpcserver.go:201        get piece tasks: task_id:"709f18bdb3610220731c0cd0c86323b10d5df32d79e4e33507be248c2627899e"  src_pid:"xxxxxxxxxxxxxxxxxxxxx-fae315fc-ce74-47bc-9ed7-34b50dc46317"  dst_pid:"-709f18bdb3610220731c0cd0c86323b10d5df32d79e4e33507be248c2627899e_CDN"  start_num:655  limit:16
11月 29 18:06:55  cdn[8955]: 2021-11-29T18:06:55.331+0800        INFO        gc/manager.go:71        start the disk storage gc job        {"type": "disk"}
11月 29 18:06:55  cdn[8955]: 2021-11-29T18:06:55.331+0800        INFO        gc/manager.go:71        at most 0 tasks can be cleaned up, actual gc 0 tasks        {"type": "disk"}
11月 29 18:07:01  cdn[8955]: 2021-11-29T18:07:01.331+0800        DEBUG        task/manager.go:209        start the task meta gc job
11月 29 18:07:01  cdn[8955]: 2021-11-29T18:07:01.331+0800        INFO        gc/manager.go:71        gc tasks: successfully full gc task count(0), remainder count(28)        {"type": "meta"}
11月 29 18:07:02  cdn[8955]: 2021-11-29T18:07:02.441+0800        INFO        grpclog/grpclog.go:37        [transport]transport: loopyWriter.run returning. connection error: desc = "transport is closing"
11月 29 18:07:09  cdn[8955]: 2021-11-29T18:07:09.764+0800        INFO        grpclog/grpclog.go:37        [transport]transport: loopyWriter.run returning. connection error: desc = "transport is closing"
11月 29 18:07:14  cdn[8955]: 2021-11-29T18:07:14.242+0800        INFO        rpcserver/rpcserver.go:201        get piece tasks: task_id:"709f18bdb3610220731c0cd0c86323b10d5df32d79e4e33507be248c2627899e"  src_pid:"xxxxxxxxxxxxxxxxxxxxx-f8ab4221-bd35-4481-ad47-f177c2d5c24e"  dst_pid:"-709f18bdb3610220731c0cd0c86323b10d5df32d79e4e33507be248c2627899e_CDN"  limit:16
11月 29 18:07:14  cdn[8955]: 2021-11-29T18:07:14.245+0800        INFO        rpcserver/rpcserver.go:201        get piece tasks: task_id:"709f18bdb3610220731c0cd0c86323b10d5df32d79e4e33507be248c2627899e"  src_pid:"xxxxxxxxxxxxxxxxxxxxx-f8ab4221-bd35-4481-ad47-f177c2d5c24e"  dst_pid:"-709f18bdb3610220731c0cd0c86323b10d5df32d79e4e33507be248c2627899e_CDN"  start_num:16  limit:16

### Expected behavior:

dfget will exit regardless of whether the download task is abnormal or not

### How to reproduce it:

Downloading large files exceeding 2G may reproduce

### Environment:
- Dragonfly version: v2.0
- OS: Centos7
- Kernel (e.g. `uname -a`): 5.15.2-1.el7.elrepo.x86_64
- Others: 

If you need more detailed logs, please contact me, I will continue to pay attention

**Comment by gaius-qi** [comment]
Please use the latest version.
