### ISSUE TITLE
manager console is giving permission error for root user

### ISSUE THREAD

**Issue by mohafarooq** [dragonflyoss/Dragonfly2#845]
### Bug report:
manager console is giving permission error for root user

![image](https://user-images.githubusercontent.com/81506422/144171480-bb75ae53-7eee-42ea-ae30-1c592046c57f.png)

![image](https://user-images.githubusercontent.com/81506422/144171442-691ee1a6-66ab-4cd8-b71d-fe989f025742.png)

Manager core.log:
[core.log](https://github.com/dragonflyoss/Dragonfly2/files/7630842/core.log)

Manager gin.log:
[gin.log](https://github.com/dragonflyoss/Dragonfly2/files/7630845/gin.log)

### Environment:
- Dragonfly version: rc.2
- OS:
- Kernel (e.g. `uname -a`):
- Others:

**Comment by mohafarooq** [comment]
```
> select * from casbin_rule;
+----+-------+-------+--------------------+------+------+------+------+
| id | ptype | v0    | v1                 | v2   | v3   | v4   | v5   |
+----+-------+-------+--------------------+------+------+------+------+
| 26 | g     | 2     | guest              |      |      |      |      |
| 30 | p     | guest | applications       | read |      |      |      |
| 10 | p     | guest | cdn-clusters       | read |      |      |      |
| 12 | p     | guest | cdns               | read |      |      |      |
| 23 | p     | guest | configs            | read |      |      |      |
| 25 | p     | guest | jobs               | read |      |      |      |
| 16 | p     | guest | oauth              | read |      |      |      |
| 18 | p     | guest | permissions        | read |      |      |      |
| 20 | p     | guest | preheats           | read |      |      |      |
| 14 | p     | guest | roles              | read |      |      |      |
|  2 | p     | guest | scheduler-clusters | read |      |      |      |
|  4 | p     | guest | schedulers         | read |      |      |      |
|  6 | p     | guest | security-groups    | read |      |      |      |
| 28 | p     | guest | security-rules     | read |      |      |      |
|  8 | p     | guest | users              | read |      |      |      |
| 29 | p     | root  | applications       | *    |      |      |      |
|  9 | p     | root  | cdn-clusters       | *    |      |      |      |
| 11 | p     | root  | cdns               | *    |      |      |      |
| 22 | p     | root  | configs            | *    |      |      |      |
| 24 | p     | root  | jobs               | *    |      |      |      |
| 15 | p     | root  | oauth              | *    |      |      |      |
| 17 | p     | root  | permissions        | *    |      |      |      |
| 19 | p     | root  | preheats           | *    |      |      |      |
| 13 | p     | root  | roles              | *    |      |      |      |
|  1 | p     | root  | scheduler-clusters | *    |      |      |      |
|  3 | p     | root  | schedulers         | *    |      |      |      |
|  5 | p     | root  | security-groups    | *    |      |      |      |
| 27 | p     | root  | security-rules     | *    |      |      |      |
|  7 | p     | root  | users              | *    |      |      |      |
+----+-------+-------+--------------------+------+------+------+------+
```

**Comment by gaius-qi** [comment]
I think you have deleted the root user premission, there is no role associated with the root user in your `casbin_rule` table.

**Comment by mohafarooq** [comment]
how to fix it?

**Comment by gaius-qi** [comment]
> how to fix it?

@yxxhero

**Comment by yxxhero** [comment]
@mohafarooq  insert a record into the casbin_rule table, like below:
```bash
+----+-------+-------+--------------------+------+------+------+------+
| id | ptype | v0    | v1                 | v2   | v3   | v4   | v5   |
+----+-------+-------+--------------------+------+------+------+------+
| 25 | g     | 1     | root               |      |      |      |      |
```
`1` is the admin user uid.

**Comment by mohafarooq** [comment]
I did that. It didn't solve the issue. I inserted id 21. 

`> select * from casbin_rule order by  id;
+----+-------+-------+--------------------+------+------+------+------+
| id | ptype | v0    | v1                 | v2   | v3   | v4   | v5   |
+----+-------+-------+--------------------+------+------+------+------+
|  1 | p     | root  | scheduler-clusters | *    |      |      |      |
|  2 | p     | guest | scheduler-clusters | read |      |      |      |
|  3 | p     | root  | schedulers         | *    |      |      |      |
|  4 | p     | guest | schedulers         | read |      |      |      |
|  5 | p     | root  | security-groups    | *    |      |      |      |
|  6 | p     | guest | security-groups    | read |      |      |      |
|  7 | p     | root  | users              | *    |      |      |      |
|  8 | p     | guest | users              | read |      |      |      |
|  9 | p     | root  | cdn-clusters       | *    |      |      |      |
| 10 | p     | guest | cdn-clusters       | read |      |      |      |
| 11 | p     | root  | cdns               | *    |      |      |      |
| 12 | p     | guest | cdns               | read |      |      |      |
| 13 | p     | root  | roles              | *    |      |      |      |
| 14 | p     | guest | roles              | read |      |      |      |
| 15 | p     | root  | oauth              | *    |      |      |      |
| 16 | p     | guest | oauth              | read |      |      |      |
| 17 | p     | root  | permissions        | *    |      |      |      |
| 18 | p     | guest | permissions        | read |      |      |      |
| 19 | p     | root  | preheats           | *    |      |      |      |
| 20 | p     | guest | preheats           | read |      |      |      |
| 21 | g     | 1     | root               |      |      |      |      |
| 22 | p     | root  | configs            | *    |      |      |      |
| 23 | p     | guest | configs            | read |      |      |      |
| 24 | p     | root  | jobs               | *    |      |      |      |
| 25 | p     | guest | jobs               | read |      |      |      |
| 26 | g     | 2     | guest              |      |      |      |      |
| 27 | p     | root  | security-rules     | *    |      |      |      |
| 28 | p     | guest | security-rules     | read |      |      |      |
| 29 | p     | root  | applications       | *    |      |      |      |
| 30 | p     | guest | applications       | read |      |      |      |
+----+-------+-------+--------------------+------+------+------+------+
`

**Comment by mohafarooq** [comment]
@yxxhero

**Comment by yxxhero** [comment]
@mohafarooq logout and login

**Comment by mohafarooq** [comment]
> @mohafarooq logout and login

I tried that. It is not helping..

**Comment by mohafarooq** [comment]
@yxxhero :I restarted the service and it is working now.. 
Can you tell me how to change the root user's password? The default password for the root user is a security concern.
