### ISSUE TITLE
Preheat failure

### ISSUE THREAD

**Issue by mfarooq-intel** [dragonflyoss/Dragonfly2#847]
### Bug report:

{"level":"error","ts":"2021-11-30 21:07:31.436","caller":"service/job.go:128","msg":"polling job 3 and task group_7a3df382-f0cc-424b-bb43-bd816f0a78a8 fa
iled polling job 3 and task group_7a3df382-f0cc-424b-bb43-bd816f0a78a8 status is PENDING","stacktrace":"d7y.io/dragonfly/v2/manager/service.(*rest).polli
ngJob\n\t/go/src/d7y.io/dragonfly/v2/manager/service/job.go:128"}
{"level":"error","ts":"2021-11-30 21:07:31.437","caller":"service/job.go:139","msg":"polling job 3 and task group_7a3df382-f0cc-424b-bb43-bd816f0a78a8 ti
meout","stacktrace":"d7y.io/dragonfly/v2/manager/service.(*rest).pollingJob\n\t/go/src/d7y.io/dragonfly/v2/manager/service/job.go:139"}

Manager log:

[core.log](https://github.com/dragonflyoss/Dragonfly2/files/7631898/core.log)

### Environment:
- Dragonfly version: rc.3
- OS:
- Kernel (e.g. `uname -a`):
- Others:

**Comment by gaius-qi** [comment]
Please provide me with the cdn and scheduler log, the manager sees that the download process has timedout.

**Comment by mohafarooq** [comment]
Attached. 
[scheduler.log](https://github.com/dragonflyoss/Dragonfly2/files/7631997/scheduler.log)
[cdn_core.log](https://github.com/dragonflyoss/Dragonfly2/files/7632029/cdn_core.log)

**Comment by gaius-qi** [comment]
CDN not found.

```text
{"level":"error","ts":"2021-11-30 20:53:16.094","caller":"cmd/root.go:71","msg":"new refreshable cdn client: address list of cdn is empty","stacktrace":"d7y.io/dragonfly/v2/cmd/scheduler/cmd.Execute\n\t/go/src/d7y.io/dragonfly/v2/cmd/scheduler/cmd/root.go:71\nmain.main\n\t/go/src/d7y.io/dragonfly/v2/cmd/scheduler/main.go:25\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225"}
```

**Comment by mohafarooq** [comment]
CDN is configured. I am not sure why this error is coming.

**Comment by gaius-qi** [comment]
You can see if mysql has an active cdn.

**Comment by mohafarooq** [comment]
Yes. Manager console is also showing that CDN  is active.

**Comment by gaius-qi** [comment]
Please use the latest version.
