### ISSUE TITLE
Single Sign On (SSO) feature and AD integration for Manager console 

### ISSUE THREAD

**Issue by mfarooq-intel** [dragonflyoss/Dragonfly2#851]
### Feature request:

Currently, the manager web console requires its own user id and passwords. Also, dragonfly stores user passwords. It is good to have a manager console integrated with AD accounts, groups, and entitlement for enterprise use cases. Similar to how harbor works for example.

**Comment by mfarooq-intel** [comment]
@gaius-qi : can this be enabled?

**Comment by gaius-qi** [comment]
Fix in `v2.0.2`
