### ISSUE TITLE
dfdaemon back to source for all images and not using CDN

### ISSUE THREAD

**Issue by mohafarooq** [dragonflyoss/Dragonfly2#925]
### Bug report:

dfdaemon back to source for all images and not using CDN.

[dfdaemon_core.log](https://github.com/dragonflyoss/Dragonfly2/files/7708871/dfdaemon_core.log)

### Environment:
- Dragonfly version: v2.0.1
- OS:
- Kernel (e.g. `uname -a`):
- Others:

**Comment by mohafarooq** [comment]
CDN Log:
[cdn_core.log](https://github.com/dragonflyoss/Dragonfly2/files/7708940/cdn_core.log)

Scheduler 1 log:
[sched_core1.log](https://github.com/dragonflyoss/Dragonfly2/files/7708944/sched_core1.log)

Scheduler 2 log:

**Comment by gaius-qi** [comment]
The log shows that the cdn download failed. @244372610 

```text
{"level":"info","ts":"2021-12-13 20:52:12.704","caller":"task/manager.go:82","msg":"failed to add or update task with req: &types.TaskRegisterRequest{URL:\"https://registry.com/v2/project/repo/image/blobs/sha256:a125d416d6c8d4693d88b6a69090de33969fa096593a0a5df4ef55117633a00b\", TaskID:\"0cde3188a70fe9fe2ed13572711f928bed5f0aada4ec07b176737259739ba147\", Digest:\"\", Filter:[]string{\"\"}, Header:map[string]string{\"Accept\":\"application/vnd.sylabs.sif.layer.v1.sif, */*\", \"Authorization\":\"Bearer}
```
