### ISSUE TITLE
Grafana dashboard template wanted.

### ISSUE THREAD

**Issue by EDGsheryl** [dragonflyoss/Dragonfly2#947]
### Feature request:

A Grafana dashboard provides a way of displaying metrics and log data in the form of visualizations and reporting dashboards. And the official dashboard template can provide the best practice to using the Dragonfly and make the debug work easier.

**Comment by wangxiaoq** [comment]
+1

**Comment by anjia0532** [comment]
+1

**Comment by gaius-qi** [comment]
Please refer to https://github.com/dragonflyoss/monitoring/tree/main/grafana
