### ISSUE TITLE
cdn running but not working

### ISSUE THREAD

**Issue by hongfeioo** [dragonflyoss/Dragonfly2#961]
### Bug report:

 ```
[root@tj1-kubekey-test01 dragonfly]# kubectl get pod  -ndragonfly-system
NAME                                 READY   STATUS             RESTARTS   AGE
dragonfly-cdn-0                      1/1     Running            0          23m
dragonfly-cdn-1                      1/1     Running            0          22m
dragonfly-cdn-2                      1/1     Running            0          22m
dragonfly-dfdaemon-4jcpn             0/1     CrashLoopBackOff   9          23m
dragonfly-dfdaemon-gkj7g             0/1     CrashLoopBackOff   9          23m
dragonfly-dfdaemon-mk79f             0/1     CrashLoopBackOff   9          23m
dragonfly-dfdaemon-p9mxf             0/1     CrashLoopBackOff   9          23m
dragonfly-dfdaemon-tjwhf             0/1     CrashLoopBackOff   9          23m
dragonfly-dfdaemon-tmzjt             0/1     CrashLoopBackOff   9          23m
dragonfly-manager-786c69d9b4-5h29g   1/1     Running            0          23m
dragonfly-manager-786c69d9b4-6ps9n   1/1     Running            0          23m
dragonfly-manager-786c69d9b4-wqrj4   1/1     Running            0          23m
dragonfly-mysql-0                    1/1     Running            0          23m
dragonfly-redis-master-0             1/1     Running            0          23m
dragonfly-redis-slave-0              1/1     Running            0          23m
dragonfly-redis-slave-1              1/1     Running            0          23m
dragonfly-scheduler-0                0/1     CrashLoopBackOff   9          23m
dragonfly-scheduler-1                0/1     CrashLoopBackOff   9          22m

[root@tj1-kubekey-test01 dragonfly]# kc logs dragonfly-scheduler-0  -ndragonfly-system
Error: new refreshable cdn client: address list of cdn is empty

[root@tj1-kubekey-test01 dragonfly]# kc logs dragonfly-dfdaemon-4jcpn -n dragonfly-system
Error: rpc error: code = NotFound desc = scheduler cluster not found


[root@tj1-kubekey-test01 dragonfly]# kubectl exec -it dragonfly-mysql-0 -ndragonfly-system -- /bin/sh
mysql> select * from cdn
    -> ;
+----+---------------------+---------------------+--------+--------------------------------------------------------+------+----------+-------------+------+---------------+----------+----------------+
| id | created_at          | updated_at          | is_del | host_name                                              | idc  | location | ip          | port | download_port | state    | cdn_cluster_id |
+----+---------------------+---------------------+--------+--------------------------------------------------------+------+----------+-------------+------+---------------+----------+----------------+
|  1 | 2021-12-27 08:11:02 | 2021-12-27 11:32:46 |      0 | dragonfly-cdn-0.cdn.dragonfly-system.svc.cluster.local |      |          | 10.x.x.158 | 8003 |          8001 | inactive |              1 |
|  2 | 2021-12-27 08:11:19 | 2021-12-27 11:32:58 |      0 | dragonfly-cdn-1.cdn.dragonfly-system.svc.cluster.local |      |          | 10.x.x.160 | 8003 |          8001 | inactive |              1 |
|  3 | 2021-12-27 08:11:31 | 2021-12-27 11:33:15 |      0 | dragonfly-cdn-2.cdn.dragonfly-system.svc.cluster.local |      |          | 10.x.x.34 | 8003 |          8001 | inactive |              1 |
+----+---------------------+---------------------+--------+--------------------------------------------------------+------+----------+-------------+------+---------------+----------+----------------+


[root@tj1-kubekey-test01 dragonfly]# kubectl exec -it dragonfly-cdn-0  -ndragonfly-system -- /bin/sh
Defaulted container "cdn" out of: cdn, wait-for-manager (init)
/ # netstat -ntlp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:8001            0.0.0.0:*               LISTEN      9/nginx: master pro

```

### Expected behavior:
netstat -ntlp  in cdn

80003  not  listenning

### Environment:
- Dragonfly version: v2.0.1 , heml v0.5.24
- OS: centos7
- Kernel (e.g. `uname -a`):  5.4.54-1.0.0.std7c.el7.2.x86_64
- Others:

**Comment by jim3ma** [comment]
Can you check the cdn log in `/var/log/dragonfly/cdn/*.log` ?

**Comment by hongfeioo** [comment]
/ # cat /var/log/dragonfly/cdn/core.log
{"level":"info","ts":"2021-12-27 11:32:45.919","caller":"cmd/root.go:74","msg":"Version:\nMajor: 2, Minor: 0, GitVersion: v2.0.1, GitCommit: f275eeb, Platform: linux, BuildTime: 2021-12-26T13:11:57Z, GoVersion: go1.17.3 linux/amd64, Gotags: none, Gogcflags: none"}
{"level":"info","ts":"2021-12-27 11:32:45.919","caller":"cmd/root.go:78","msg":"cdn system configuration:\nconsole: false\nverbose: false\npprof-port: -1\njaeger: \"\"\nservice-name: dragonfly-cdn\nbase:\n    listenPort: 8003\n    downloadPort: 8001\n    systemReservedBandwidth: 20.0MB\n    maxBandwidth: 200.0MB\n    advertiseIP: 10.46.8.158\n    failAccessInterval: 3m0s\n    gcInitialDelay: 24h0m0s\n    gcMetaInterval: 24h0m0s\n    taskExpireTime: 3m0s\n    storageMode: disk\n    manager:\n        addr: dragonfly-manager.dragonfly-system.svc.cluster.local:65003\n        cdnClusterID: 1\n        keepAlive:\n            interval: 5s\n    host:\n        location: \"\"\n        idc: \"\"\n    metrics: null\nplugins:\n    storagedriver:\n        - name: disk\n          enable: true\n          config:\n            baseDir: /tmp/cdn\n    storagemanager:\n        - name: disk\n          enable: true\n          config:\n            driverConfigs:\n                disk:\n                    gcConfig:\n                        cleanRatio: 1\n                        fullGCThreshold: 5G\n                        intervalThreshold: 2h\n                        youngGCThreshold: 100G\n            gcInitialDelay: 5s\n            gcInterval: 15s\n"}
{"level":"info","ts":"2021-12-27 11:32:45.919","caller":"plugins/plugins.go:46","msg":"add plugin[storagedriver][disk] success"}
{"level":"info","ts":"2021-12-27 11:32:45.919","caller":"plugins/plugins.go:46","msg":"add plugin[storagemanager][disk] success"}


/ # cat  /var/log/dragonfly/cdn/gc.log
{"level":"info","ts":"2021-12-27 11:33:05.986","caller":"gc/manager.go:71","msg":"start the disk storage gc job","type":"disk"}
{"level":"info","ts":"2021-12-27 11:33:06.007","caller":"gc/manager.go:71","msg":"at most 0 tasks can be cleaned up, actual gc 0 tasks","type":"disk"}
{"level":"info","ts":"2021-12-27 11:33:20.987","caller":"gc/manager.go:71","msg":"start the disk storage gc job","type":"disk"}
{"level":"info","ts":"2021-12-27 11:33:20.988","caller":"gc/manager.go:71","msg":"at most 0 tasks can be cleaned up, actual gc 0 tasks","type":"disk"}
{"level":"info","ts":"2021-12-27 11:33:35.985","caller":"gc/manager.go:71","msg":"start the disk storage gc job","type":"disk"}
{"level":"info","ts":"2021-12-27 11:33:35.986","caller":"gc/manager.go:71","msg":"at most 0 tasks can be cleaned up, actual gc 0 tasks","type":"disk"}

**Comment by hongfeioo** [comment]
/ # nc -w 1 127.0.0.1  8001  < /dev/null && echo " ok" || echo " error"
 ok
/ # nc -w 1 127.0.0.1  8003  < /dev/null && echo " ok" || echo " error"
 error

**Comment by jim3ma** [comment]
It seems the cdn process has exited unexpected.
I can not find any error in cdn logs. You can get stdout from the cdn pod and check it.

**Comment by hongfeioo** [comment]
@jim3ma   thx :)  

dragonfly2  update to v2.0.2-alpha-6  ,  the problem disappeared     .
